AdaptiveConsulting/ReactiveTraderCloud

- src/client/src/ui/header/views/headerView.jsx
Fix for #220.  This removes the link and adds the user's first and surname back.
> Username in Header fixes

- src/client/src/ui/footer/model/footerModel.js
- src/client/src/ui/footer/model/index.js
- src/client/src/ui/footer/views/footer.scss
- src/client/src/ui/footer/views/footerView.jsx
- src/client/src/ui/footer/views/index.js
> Add Footer

- src/client/src/ui/spotTile/views/priceButton.jsx
> suffix decimal point to integer big figures

- src/client/src/ui/blotter/views/blotter.scss
- src/client/src/ui/spotTile/views/notionalInput.jsx
- src/client/src/ui/spotTile/views/notionalInput.scss
- src/client/src/ui/spotTile/views/spotTile.scss
- src/client/src/ui/spotTile/views/spotTileView.jsx
- src/client/src/ui/spotTile/views/tradeNotification.jsx
- src/client/src/ui/spotTile/views/tradeNotification.scss
> make spot tiles styling more in line with design

- src/client/src/ui/blotter/views/blotter.scss
- src/client/src/ui/blotter/views/blotterView.jsx
- src/client/src/ui/common/styles/_fonts.scss
- src/client/src/ui/regions/views/workspace/workspaceItemContainer.scss
- src/client/src/ui/shell/views/shell.scss
Style blotter so its closer to original design
Add styling for scrollbars
#106
> Blotter styling

- src/client/src/ui/spotTile/views/notionalInput.jsx
- src/client/src/ui/spotTile/views/notionalInput.scss
> automatically select amount when clicking on the notional input

- src/client/src/ui/spotTile/views/spotTile.scss
- src/client/src/ui/spotTile/views/spotTileView.jsx
> correct notification position

- src/client/src/ui/common/components/modal/modal.jsx
- src/client/src/ui/common/components/modal/modal.scss
- src/client/src/ui/common/styles/_base.scss
- src/client/src/ui/shell/views/shell.scss
- src/client/src/ui/shell/views/shellView.js
> refactor modal styling

- src/client/src/services/model/trade.js
- src/client/src/ui/blotter/model/blotterModel.js
- src/client/src/ui/blotter/views/blotter.scss
- src/client/src/ui/blotter/views/blotterView.jsx
> highlight new trade in blotter

- src/client/src/services/model/applicationStatusConst.js
- src/client/src/services/model/index.js
- src/client/src/ui/footer/model/footerModel.js
- src/client/src/ui/footer/model/index.js
- src/client/src/ui/footer/views/footer.scss
- src/client/src/ui/footer/views/footerView.jsx
- src/client/src/ui/spotTile/model/spotTileModel.js
> refactor service status display

- src/client/src/ui/shell/views/shell.scss
- src/client/src/ui/shell/views/shellView.js
- src/client/webpack.config.js
> display splash screen

- src/client/src/bootstrapper.js
- src/client/src/services/model/tradeStatus.js
- src/client/src/ui/spotTile/model/spotTileModel.js
- src/client/src/ui/spotTile/spotTileFactory.js
- src/client/src/ui/spotTile/views/tradeNotification.jsx
Also, remove obsolete code in spot tile model.
Closes #223
> Auto dismiss trade notification

- src/client/src/services/blotterService.js
- src/client/src/services/executionService.js
- src/client/src/services/mappers/tradeMapper.js
- src/client/src/services/model/trade.js
- src/client/src/ui/blotter/model/blotterModel.js
Don't flash trades when receiving state of the world
#228
> fix issue with current implementation of flashing new trades

- src/client/src/ui/spotTile/views/notionalInput.jsx
- src/client/src/ui/spotTile/views/notionalInput.scss
- src/client/src/ui/spotTile/views/spotTile.scss
- src/client/src/ui/spotTile/views/spotTileView.jsx
> Display server date value

- src/client/src/ui/spotTile/views/spotTileView.jsx
> display correct spot date

- src/client/src/ui/spotTile/views/spotTile.scss
- src/client/src/ui/spotTile/views/spotTileView.jsx
> disable execution if service is down. Put tile in stale mode only if pricing is down

- src/client/src/ui/shell/model/shellModel.js
- src/client/src/ui/shell/views/shell.scss
- src/client/src/ui/shell/views/shellView.js
- src/client/webpack.config.js
> display application version in splash screen

- src/client/src/bootstrapper.js
- src/client/src/services/compositeStatusService.js
- src/client/src/services/mappers/connectionTypeMapper.js
- src/client/src/services/mappers/index.js
- src/client/src/services/model/connectionType.js
- src/client/src/services/model/index.js
- src/client/src/system/service/autobahnConnectionProxy.js
- src/client/src/system/service/connection.js
- src/client/src/ui/footer/model/footerModel.js
- src/client/src/ui/footer/views/footerView.jsx
display connection type in footer
#82 #83
> Configure long polling fallback

- src/client/src/ui/analytics/views/analytics.scss
- src/client/src/ui/analytics/views/analyticsBarChart.jsx
- src/client/src/ui/analytics/views/analyticsView.jsx
- src/client/src/ui/regions/views/workspace/workspaceItemContainer.scss
- src/client/src/ui/shell/views/shell.scss
- src/client/src/ui/shell/views/shellView.js
> improve layout responsiveness on smaller screens

- src/server/Adaptive.ReactiveTrader.Server.Pricing/MeanReversionRandomWalkPriceGenerator.cs
- src/server/Adaptive.ReactiveTrader.Server.Pricing/PriceSource.cs
- src/server/Adaptive.ReactiveTrader.Server.Pricing/RandomExtensions.cs
- src/server/Adaptive.ReactiveTrader.Server.Pricing/RandomWalkPriceGenerator.cs
AdaptiveConsulting/ReactiveTraderCloud#293 for dev
> Resubmit "Improve price generation" to dev branch

- src/client/src/ui/spotTile/views/notionalInput.jsx
solution that is as per spec (may break on older safari)
> removing jquery from build

- deploy/config
- deploy/docker/build/crossbar/build.sh
- deploy/docker/build/crossbar/template.install.sh
- src/server/.crossbar/config.json
> Upgrade crossbar

- .gitignore
- src/server/Adaptive.ReactiveTrader.Messaging/WAMP/RpcOperation.cs
- src/server/Adaptive.ReactiveTrader.Messaging/WAMP/RpcResponseOperation.cs
> Execution fix

- deploy/kubernetes/templates/web/svc.yml
- src/client/src/system/service/autobahnConnectionProxy.js
> add nsgate ports for https and wss

- src/client/src/system/utils.js
- src/client/src/ui/spotTile/model/spotTileModel.js
- src/client/src/ui/spotTile/views/notionalInput.jsx
- src/client/src/ui/spotTile/views/spotTileView.jsx
> Notional fix

- deploy/docker/build/web/nginx/dev.nginx.conf
- deploy/docker/build/web/nginx/prod.nginx.conf
> set no-cache for web

- src/client/src/ui/spotTile/views/spotTileView.jsx
> fix existing typo when unmounting spot tile

- src/server/Adaptive.ReactiveTrader.Messaging/Broker.cs
- src/server/Adaptive.ReactiveTrader.Messaging/WAMP/RpcOperation.cs
- src/server/Adaptive.ReactiveTrader.Messaging/WAMP/RpcResponseOperation.cs
- src/server/Adaptive.ReactiveTrader.Server.Pricing/PricingServiceHost.cs
> pricing service investigation

- docs/client.md
> update npm target documentation

- src/client/src/system/openFin/openFin.js
> Credit check

- src/client/src/app.json
> fix openfin version

- src/client/src/ui/blotter/model/blotterModel.js
> sort trade descendingly on load

- src/client/src/ui/spotTile/model/spotTileModel.js
- src/client/src/ui/spotTile/views/spotTile.scss
> disable trade buttons if trade is in flight

- src/client/src/ui/common/components/browserChrome/browserChrome.scss
- src/client/src/ui/regions/views/singleItem/singleItemRegionView.jsx
- src/client/src/ui/regions/views/workspace/workspaceRegionView.jsx
- src/client/src/ui/shell/views/shell.scss
- src/client/src/ui/shell/views/shellView.jsx
> expand workspace area when poping analytics out

- src/client/src/system/openFin/openFin.js
- src/client/src/ui/spotTile/model/spotTileModel.js
- src/client/src/ui/spotTile/views/spotTileView.jsx
remove animation timeout in spot tile view, and hook into application launch callback to work out when it has finished loading
> refactor openfin chart launch

- src/client/src/appBootstrapper.js
- src/client/src/services/model/index.js
- src/client/src/services/model/regionSettings.js
- src/client/src/ui/analytics/model/analyticsModel.js
- src/client/src/ui/blotter/model/blotterModel.js
- src/client/src/ui/common/regionManagerHelper.js
- src/client/src/ui/regions/regionManager.js
- src/client/src/ui/spotTile/model/spotTileModel.js
- src/client/src/ui/spotTile/spotTileFactory.js
> Persist open windows

- src/server/Adaptive.ReactiveTrader.Server.Pricing/MeanReversionRandomWalkPriceGenerator.cs
- src/server/Adaptive.ReactiveTrader.Server.Pricing/PriceSource.cs
- src/server/Adaptive.ReactiveTrader.Server.Pricing/RandomExtensions.cs
use single scheduler with timing operators to prevent lots of threads
protect access to random
don't use while loop to protect against 0
slow down pricing
> Price Threading Tidy

- src/client/src/ui/shell/model/shellModel.js
- src/client/src/ui/shell/views/shell.scss
- src/client/src/ui/shell/views/shellView.jsx
> expand workspace and analytics panels when tearing blotter out

- src/client/src/ui/spotTile/views/spotTile.scss
- src/client/src/ui/spotTile/views/tradeNotification.scss
> css adjustments for when spot tile is in stale mode

- src/client/src/system/openFin/openFin.js
> bring app to front when receiving notification

- src/client/src/ui/common/popout/openfinPopoutService.js
> fix window depth issue

- src/client/lib/dockingManager.js
- src/client/src/ui/common/popout/openfinPopoutService.js
> reopen windows in their docked state

- src/client/src/ui/analytics/views/analytics.scss
- src/client/src/ui/common/components/openFinChrome/openFinChrome.jsx
- src/client/src/ui/common/components/openFinChrome/openFinChrome.scss
- src/client/src/ui/common/popout/openfinPopoutService.js
- src/client/src/ui/spotTile/model/spotTileModel.js
- src/client/src/ui/spotTile/views/spotTile.scss
> remove chrome header for openfin popouts

- src/client/src/ui/shell/views/shell.scss
- src/client/src/ui/shell/views/shellView.jsx
- src/client/src/ui/sidebar/views/sidebar.scss
> use flexbox to position sidebar and analytics

- src/server/Adaptive.ReactiveTrader.Contract/Events/Trade/TradeCreatedEvent.cs
- src/server/Adaptive.ReactiveTrader.Contract/ExecuteTradeRequestDto.cs
- src/server/Adaptive.ReactiveTrader.Contract/TradeDto.cs
- src/server/Adaptive.ReactiveTrader.Server.Common/Trade.cs
- src/server/Adaptive.ReactiveTrader.Server.TradeExecution/Domain/Trade.cs
> handle decimal notional values on server

- src/client/src/services/executionService.js
> handle execution requests taking longer than expected

- src/client/src/system/environment.js
- src/client/src/system/index.js
- src/client/src/ui/analytics/model/analyticsModel.js
- src/client/src/ui/analytics/views/analyticsView.jsx
- src/client/src/ui/blotter/model/blotterModel.js
- src/client/src/ui/blotter/views/blotterView.jsx
- src/client/src/ui/common/modelBase.js
- src/client/src/ui/spotTile/model/spotTileModel.js
- src/client/src/ui/spotTile/views/spotTileView.jsx
> lift canPopout method from base model 

- src/client/src/ui/analytics/model/pnlChartModel.js
> display one decimal for y axis

- deploy/docker/build/servers/build.sh
- deploy/docker/runAll
- deploy/docker/testAll
- docs/setup/docker-setup.md
> update docker docs

- src/client/src/ui/spotTile/model/spotTileModel.js
- src/client/src/ui/spotTile/views/spotTileView.jsx
> mark price as stale if we dont receive any update for 4 seconds

- src/client/lib/dockingManager.js
- src/client/src/ui/common/components/openFinChrome/openFinChrome.jsx
- src/client/src/ui/common/popout/openfinPopoutService.js
> Handle right click when closing window

- src/client/src/ui/blotter/views/blotterView.jsx
> update blotter dimensions before rendering

- src/client/src/ui/common/styles/_base.scss
- src/client/src/ui/shell/views/shell.scss
> move scrollbar styling to base stylesheet

- src/client/src/ui/analytics/views/analytics.scss
- src/client/src/ui/blotter/views/blotter.scss
- src/client/src/ui/blotter/views/blotterView.jsx
- src/client/src/ui/footer/views/statusIndicator.scss
- src/client/src/ui/sidebar/views/sidebar.scss
> CSS adjustements

- src/client/src/ui/notification/tradeNotificationView.jsx
> fix currency displayed in notifications

- src/client/.storybook/config.js
- src/client/package.json
> Added React Storybook.

- src/client/config/openfin/demo.app.json
- src/client/config/openfin/dev.app.json
- src/client/config/openfin/local.app.json
- src/client/src/system/openFin/openFin.js
- src/client/src/ui/common/components/openFinChrome/openFinChrome.scss
- Fix close icon position (#488)
- Bring app to focus when clicking notification (#487)
- Update app.config to fix scaling issue on windows 10 (#449)
> Fix Openfin issues

- src/client/src/ui/shell/views/shellView.jsx
> move splash container to cover full height of app

- src/client/src/appBootstrapper.js
- src/client/src/services/model/index.js
- src/client/src/services/model/trade.js
- src/client/src/services/model/tradeRow.js
- src/client/src/system/openFin/openFin.js
- src/client/src/ui/blotter/model/blotterModel.js
- src/client/src/ui/blotter/views/blotter.scss
- src/client/src/ui/blotter/views/blotterView.jsx
> hightlight trade row in blotter when clicking on notification

- src/client/src/ui/common/styles/_base.scss
> change default background

- src/client/src/ui/analytics/views/analytics.scss
- src/client/src/ui/analytics/views/analyticsView.jsx
> correct chart tooltip formatting

- src/client/src/ui/spotTile/model/spotTileModel.js
- src/server/Adaptive.ReactiveTrader.Server.Blotter/BlotterServiceHost.cs
- src/server/Adaptive.ReactiveTrader.Server.Pricing/PriceSource.cs
> single pricing timer, limit blotter SOTW count to 50

- src/client/src/ui/blotter/model/blotterModel.js
> fix blotter model

- src/client/config/openfin/demo.app.json
- src/client/config/openfin/dev.app.json
- src/client/config/openfin/local.app.json
> upgrade openfin version to 6.49.17.14

- circle.yml
> update circle ci config to ignore gh-pages

- src/xamarin-client/Adaptive.ReactiveTrader.Client.iOSTab.WatchKitExtension/Adaptive.ReactiveTrader.Client.iOSTab.WatchKitExtension.csproj
- src/xamarin-client/Adaptive.ReactiveTrader.Client.iOSTab.WatchKitExtension/app.config
- src/xamarin-client/Adaptive.ReactiveTrader.Client.iOSTab.WatchKitExtension/packages.config
- src/xamarin-client/Adaptive.ReactiveTrader.Client.iOSTab/Adaptive.ReactiveTrader.Client.iOSTab.csproj
- src/xamarin-client/Adaptive.ReactiveTrader.Client.iOSTab/app.config
- src/xamarin-client/Adaptive.ReactiveTrader.Client.iOSTab/packages.config
Fixing iOS, now it deploys on device
> [Xamarin Client] Fixing iOS builds

- src/client/src/services/pricingService.js
This PR fixes the import for 'SpotPrice' in pricingService.js
> chore: fix import for pricing service

- src/client/src/redux/analytics/analyticsOperations.ts
- src/client/src/redux/blotter/blotterOperations.ts
- Ensure that services wait for updates from the reference service before starting.
> chore: Use redux observable to listen for reference service updates

- src/client/src/services/model/tradeNotification.ts
The numeral wasn't being imported correctly which caused an error stopping the notifications from showing up and the UI to freeze
> Numeral import fix

- deploy/clean
- deploy/docker/build/web/build.sh
- deploy/kubernetes/use-cluster
- deploy/minikube/clean
- deploy/minikube/powershell_library/src/Invoke-ShareHostDrive.ps1
- fix an issue for local builds with CIRCLECI variable not defined
- fix host share with minikube VM
> fix minikube regressions

- src/client/src/ui/shell/OpenFinChromeStyles.scss
Cherry pick openfin fix from #604
> Fix for close button on OpenFin pop-out tile

- src/client/config/openfin/2084.app.json
- src/client/config/openfin/demo.app.json
- src/client/config/openfin/dev.app.json
- src/client/config/openfin/local.app.json
- src/client/yarn.lock
Update openfin version to 8.56.24.41
> update openfin version

- docs/setup/getting-started.md
- docs/setup/reactive-trader-excel.md
Thanks to @bhavesh-desai-scratch I was able to setup the Reactive Trader Excel. As it was a bit tricky I think having some docs on how to setup would be useful.
> Added "Getting Started with Reactive Trader Excel"

- src/client/src/types/trade.ts
- src/client/src/ui/blotter/blotterOperations.ts
> Rxjs refactor: reference data service

- src/client/src/compositeStatusServiceOperations.ts
- src/client/src/system/service/serviceClient.ts
- src/client/src/ui/analytics/analyticsOperations.ts
- src/client/src/ui/blotter/blotterOperations.ts
> Rxjs refactor: serviceClient.createServiceInstanceDictionaryStream

- src/client/src/ui/spotTile/SpotTileContainer.tsx
- src/client/src/ui/spotTile/SpotTileStyles.scss
> Undock external tiles

- src/client/src/connectionStatusOperations.ts
- src/client/src/pricingOperations.ts
- src/client/src/types/connectionStatus.ts
- src/client/src/ui/shell/ShellContainer.tsx
> Rxjs refactor: connectionStatusOperations.

- src/client/src/ui/spotTile/SpotTileContainer.tsx
The previous mapStateToProps function did not have separate instances for each SpotTileContainer. In this fix, each container will receive a unique instance of mapStateToProps, preserving memoization. This will cut down on updates as shown below.
**Before**:
**After**:
> Fixed memoization across multiple components

- src/client/src/ui/analytics/AnalyticsContainer.tsx
It's not intuitive from the code, but this should allow the Analytics Region to pop-out.
> Unhide Analytics Pop-out icon

- src/client/src/ui/spotTile/tradeNotification/TradeNotification.tsx
- src/client/src/ui/spotTile/tradeNotification/TradeNotificationStyles.scss
fixed a small regression - spotTile styles for the rejected status
> spotTile rejected status

- src/client/src/ui/spotTile/tradeNotification/TradeNotification.tsx
> applied formatting to the notional value

- src/client/src/ui/spotTile/reducer.ts
> Show error tile on execution error

- deploy/kubernetes/describe
add the build id label when describing an environment
> Add build ID to describe environment command

- src/client/package-lock.json
- src/client/package.json
- src/client/src/setupTests.ts
- src/client/src/system/logger.ts
- src/client/src/system/service/AutoBahnConnection.ts
- src/client/src/system/service/AutoBahnTypeExtensions.ts
- src/client/src/system/service/__test__/autobahnConnectionProxyStub.ts
- src/client/src/system/service/__test__/connection.spec.ts
- src/client/src/system/service/__test__/serviceClient.spec.ts
- src/client/src/system/service/autobahnConnectionProxy.ts
- src/client/src/system/service/autobahnSessionProxy.ts
- src/client/src/system/service/connection.ts
- src/client/src/system/service/serviceObservableExtensions.ts
- src/client/src/system/service/tsconfig.json
- Core classes compile under strictest TS settings
- Remove redundant code
- Introduce interfaces for testing
- Patch bad Autobahn TS files
- Correct imports for next version of TS
- Type the logger and improve output
> Strongly type cleanup service classes

- src/client/src/main.tsx
- src/client/src/services/executionService.ts
- src/client/src/services/openFin/openFin.ts
- Stop using inner subscriptions
- move openfin out of the execution service
- type the limit checker
- use race for timeout
> cleanup execution service

- src/client/src/ui/common/regions/RegionWrapper.tsx
- src/client/src/ui/common/regions/reducer.ts
- src/client/src/ui/spotTile/reducer.ts
The reducers for spot tiles and regions are now in a split reducer pattern.
> ARTP-89 Cleanup reducers

- deploy/readme.md
This PR fixes the issue: https://github.com/AdaptiveConsulting/ReactiveTraderCloud/issues/747
> [ARTP-125] - Fixed link to deployment documentation.

- src/client/package-lock.json
- src/client/src/ui/blotter/epics/blotterServiceEpic.ts
- src/client/src/ui/spotTile/epics/index.ts
Fixed the openfin master branch issue.
We were not returning a stream in the openfin pricing epic.
> Fixed openfin pricing stream issue

- src/client/src/rt-theme/ExtendedThemeProvider.tsx
- src/client/src/rt-theme/ThemeProvider.tsx
- src/client/src/rt-theme/index.ts
- src/client/src/rt-theme/themes.ts
- src/client/src/ui/theme/Theme.tsx
With these types an inline `<ThemeProvider/>` will correctly resolve to the provided `Theme` type.
Thanks @keshaldesai for your help with typing.
> [ARTP-167] Add types to theme

- src/client/package-lock.json
- src/client/src/rt-components/adaptive-loader/AdaptiveLoader.tsx
- src/client/src/rt-components/flex/Flex.ts
- src/client/src/rt-components/open-fin/OpenFinChrome.tsx
- src/client/src/rt-components/tear-off/Portal.tsx
- src/client/src/rt-styleguide/Button.tsx
- src/client/src/rt-styleguide/rules.ts
- src/client/src/rt-theme/ThemeState.tsx
- src/client/src/rt-theme/emotion.ts
- src/client/src/rt-theme/globals.ts
- src/client/src/rt-theme/index.ts
- src/client/src/rt-theme/styled.tsx
- src/client/src/shell/components/status-bar/Icon.tsx
- src/client/src/shell/components/status-bar/styled.tsx
- src/client/src/ui/analytics/globals/analytics.ts
- src/client/src/ui/analytics/globals/nvd3.ts
- src/client/src/ui/status-bar/Icon.tsx
- src/client/src/ui/status-bar/styled.tsx
The current issue with our portals is that Emotion.js styling does not work in production.
This is a proposed fix for that issue. The fix here relies on setting the speedy value of Emotion to false. While this fix works, there is a performance trade-off.
> [ARTP-189] Fix for styling portals

- src/client/package-lock.json
- src/client/src/rt-theme/globals.ts
Bug: scroll bars show up whether needed or not
Cause: addition of ress.css which sets `overflow-y: scroll` on html
Fix: set `overflow-y: auto` on html
> [ARTP-208] Scroll bars always present

- src/client/src/rt-styleguide/Button.tsx
added back padding but set line-height to 0rem
> Button Fix v2

- src/client/src/shell/layouts/AppLayout.tsx
- src/client/src/shell/layouts/BodyLayout.tsx
- src/client/src/shell/routes/ShellRoute.tsx
- src/client/src/ui/workspace/WorkspaceContainer.tsx
- Responsive grid layout
- Hide analytics on small screens (revisit this in the future, slide in sidebar on mobile?)
> [ARTP-221] Responsive CSS Grid layout

- src/client/install/README.md
Add warning about installers while working in a solution to don't edit the files.
> docs(openfin): Add warning about installers.

- src/client/src/rt-components/tear-off/Portal.tsx
This also fixes ARTP-224 and ARTP-231
> [ARTP-230] Unresponsive analytics close button in OpenFin

- src/client/src/ui/spotTile/components/PriceButton.tsx
> ARTP-245 TradeButton Colour

- src/client/src/rt-components/open-fin/OpenFinChrome.tsx
- src/client/src/rt-components/open-fin/Openfin.stories.tsx
- src/client/src/rt-components/tear-off/Portal.tsx
- src/client/src/rt-components/tear-off/TearOff.tsx
- src/client/src/ui/workspace/selectors.ts
The header and the bottom button are now there
> Fix openfin chrome

- src/client/src/ui/analytics/components/Analytics.tsx
Fixed the double minus at Analytics
> ARTP-241 Analytics Double Minus

- .circleci/config.yml
- deploy/docker/build/web/nginx/dev.nginx.conf
- deploy/docker/build/web/nginx/prod.nginx.conf
Adds SPA path rule to web nginx.conf to fix `/notification` path 404.
> ARTP-255 Fix /notification path

- src/client/src/rt-components/resizer/Resizer.tsx
- src/client/src/rt-components/tear-off/TearOff.tsx
- src/client/src/shell/routes/ShellRoute.tsx
- src/client/src/ui/analytics/components/PNLBar.tsx
- src/client/src/ui/analytics/components/styled.tsx
This PR fixes:
- Tile shifting
- Font shift in tearoffs (font preload again)
- Analytics labels changing colors when resizing
> Workspace fixes

- src/client/src/ui/analytics/components/PNLBar.tsx
- src/client/src/ui/spotTile/components/SpotTile.tsx
- src/client/src/ui/spotTile/components/styled.tsx
ARTP244- hiding the date when not on hover
ARTP246- showing the actual amount in PnL on hover
> [ARTP-244] [ARTP-246] PnL bars hover, hide tile value until on hover

- src/client/src/routes/NotificationRoute.tsx
- src/client/src/shell/notification/styled.tsx
- src/client/src/shell/routes/ShellRoute.tsx
- Fixes font sizes, white space, and theme sync for notifications.
- Fixes horizontal rhythm of Forex layout
> Fix notification style

- deploy/docker/build/web/nginx/prod.nginx.conf
> Fix syntax error

- src/client/package-lock.json
- src/client/src/ui/blotter/components/blotterUtils.ts
This function was causing a bug when receiving bad data. We are planning on removing the currency icons anyways, so I removed the whole function.
> Remove numericCellRenderer

- src/client/.env.local
- src/client/package-lock.json
- src/client/src/routes/OrderTicketRoute/ChannelMerger.tsx
- src/client/src/routes/OrderTicketRoute/DrawerMenu.tsx
- src/client/src/routes/OrderTicketRoute/FormantBars.tsx
- src/client/src/routes/OrderTicketRoute/GreenKeyRecognition.ts
- src/client/src/routes/OrderTicketRoute/MediaPlayer.tsx
- src/client/src/routes/OrderTicketRoute/MediaRecorderComponent.tsx
- src/client/src/routes/OrderTicketRoute/Microphone.tsx
- src/client/src/routes/OrderTicketRoute/Notification.tsx
- src/client/src/routes/OrderTicketRoute/OrderForm.tsx
- src/client/src/routes/OrderTicketRoute/OrderStatus.tsx
- src/client/src/routes/OrderTicketRoute/OrderTicket.tsx
- src/client/src/routes/OrderTicketRoute/ScribeSession.tsx
- src/client/src/routes/OrderTicketRoute/SpeechRecognition.ts
- src/client/src/routes/OrderTicketRoute/TextField.tsx
- src/client/src/routes/OrderTicketRoute/Timer.tsx
- src/client/src/routes/OrderTicketRoute/TranscriptionSession.tsx
- src/client/src/routes/OrderTicketRoute/UserMedia.tsx
- src/client/src/routes/OrderTicketRoute/VoiceInput.tsx
- src/client/src/routes/OrderTicketRoute/WebSocketConnection.tsx
- src/client/src/routes/OrderTicketRoute/devtools/BlobDownload.tsx
- src/client/src/routes/OrderTicketRoute/requestIdleCallback.ts
In this PR:
- Improved types
- Memory leak fixed (remove event listeners)
- Minor changes
> Updates to order-ticket

- src/client/src/rt-components/loadable/Loadable.tsx
**Feature**
The Loading component should resemble Adaptive Logo
**Solution**
Removed the Spinner Component and used the AdaptiveLoader Component instead.
> ARTP-305-loading-icon

- src/client/.gitignore
- src/client/package-lock.json
- src/client/package.json
This fixes #911 by:
1. Bumping the version of `openfin-cli` - fixes runtime error.
2. Introducing a small delay before launching OpenFin - fixes connection error where local dev server wasn't running.
> Fixup running inside OpenFin

- src/client/src/rt-system/ServiceStub.ts
- src/client/src/ui/spotTile/epics/executionService.ts
https://weareadaptive.atlassian.net/browse/ARTP-342
> ARTP-342 Fixed execution service logging.

- src/client/src/ui/analytics/components/positions-chart/PositionsBubbleChart.tsx
- src/client/src/ui/analytics/components/positions-chart/chartUtil.ts
Features as per design
- circles now overlapping slightly
- shadow added to each circle
> style: bubble chart updated as per new designs

- src/client/src/shell/routes/AnalyticsRoute.tsx
- src/client/src/shell/routes/ShellRoute.tsx
**Feature**
- The Analytics window on popout should have a padding.
**Solution**
- Added a padding to the AnalyticsRoute component when Analytics Component is on popout.
> Artp 358/padding analytics

- src/client/Dockerfile
- src/client/Dockerfile.dev
- src/client/src/ui/analytics/components/styled.tsx
Removed horizontal scrolling in profit loss panel.
Also, in order to not break the UI when `distance` value is near `50`, I've made sure to add the CSS property to the `AnalyticsStyle` styled-component:
And not directly on the `BarChart` component:
> Removed horizontal scrolling in profit loss panel.

- src/client/src/shell/components/app-header/Header.tsx
Now able to vertically re-size between the shown boundaries on the top bar of the RT application window.
> Now able to vertically re-size

- src/client/src/rt-components/tear-off/ExternalWindow.tsx
This solution works for both browser and openfin and after much thought seems to be optimal
> ARTP-528/external-window-redirect-toggling

- src/client/public/config/openfin/launcher-dev.json
- src/client/src/routes/SimpleLauncher/applicationConfigurations.tsx
Launcher App Configs use the same protocol the launcher is running on, in order to share localStorage, thus make theme sync across windows
> Artp 471/link theme switching

- src/client/public/config/openfin/launcher-demo.json
- src/client/public/config/openfin/launcher-dev.json
Fixing the launcher demo width. The configs for size of the launcher that were in launcher-local.json were never reflected in launcher-demo.json.
> removed old settings

- src/client/package-lock.json
- src/client/package.json
- src/client/src/type-declarations/globals.d.ts
- src/client/src/ui/analytics/components/positions-chart/PositionsBubbleChart.tsx
- src/client/src/ui/analytics/components/positions-chart/chartUtil.ts
Added typings / very minor refactorings to
- PositionsBubbleChart
- chartUtils
> ARTP-591 - Bubble Chart typings

- src/client/package-lock.json
- src/client/src/ui/spotTile/components/PriceControls/PriceControls.tsx
- src/client/src/ui/spotTile/components/SpotTile.tsx
- src/client/src/ui/spotTile/components/Tile/Tile.tsx
- src/client/src/ui/spotTile/components/Tile/TileBusinessLogic.test.ts
- src/client/src/ui/spotTile/components/Tile/TileBusinessLogic.ts
- src/client/src/ui/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
- src/client/src/ui/spotTile/components/TileSwitch.tsx
- src/client/src/ui/spotTile/components/analyticsTile/AnalyticsTile.tsx
- src/client/src/ui/spotTile/model/spotTileUtils.ts
> Fixes for RFQ.

- src/client/src/rt-components/loadable/Loadable.tsx
- src/client/src/ui/spotTile/SpotTileContainer.tsx
Fixed Spot Tile size on connection load
**Before**
**After**
> ARTP-581 - Spot tile loading size

- src/client/src/ui/spotTile/epics/rfqTileEpics.ts
The takeUntil on rfqRequestEpic also needs to be filtered. Or else it cancels all, and other Tiles in `requested` state will never received the prices.
This PR fixes that.
> The takeUntil on rfqRequestEpic also needs to be filtered.

- src/client/src/routes/NotificationRoute.tsx
- src/client/src/routes/OrderTicketRoute/ChannelMerger.tsx
- src/client/src/routes/OrderTicketRoute/FormantBars.tsx
- src/client/src/routes/OrderTicketRoute/MediaPlayer.tsx
- src/client/src/routes/OrderTicketRoute/VoiceInput.tsx
- src/client/src/shell/notification/TradeNotification.tsx
Contains null check fixes in preparation for turning on --strictNullChecks setting
> ARTP-599 - null checks order flow

- src/client/src/ui/spotTile/components/PriceButton/PriceButton.tsx
- src/client/src/ui/spotTile/components/PriceControls/PriceControls.tsx
- src/client/src/ui/spotTile/components/SpotTile.tsx
- src/client/src/ui/spotTile/components/stories/PriceButton.stories.tsx
- src/client/src/ui/spotTile/components/stories/SpotTile.stories.tsx
**Issue**
- 0 is shown for prices/price movement when data is being loaded
- `Invalid Date` trying to parse undefined date
**Fix**
- Show `-` in place of `0`
- Hide date
**Data Loaded**
> ARTP-547 - Initial prices on load are 0

- src/client/src/shell/GlobalScrollbarStyle.tsx
- src/client/src/shell/routes/styled.tsx
- src/client/src/ui/analytics/components/styled.tsx
- src/client/src/ui/blotter/components/BlotterGrid.tsx
Added scrollbar styles for firefox
**Before**
**After**
> ARTP-619 - Firefox scrollbars

- src/client/src/routes/MainRoute/MainRoute.tsx
Increase application disconnect time from 15 minutes to 60
> Increase application disconnect time

- src/client/src/routes/MainRoute/MainRoute.tsx
- src/client/src/routes/MainRoute/index.tsx
- src/client/src/shell/components/reconnect-modal/ReconnectModal.tsx
Updated `ReconnectModal` message to use timeout value
> ARTP-623 - Up the timeout from 15 minutes to 60 minutes

- src/client/src/rt-components/icons/PopoutIcon.tsx
Remove `icon-popout` title/tooltip
> ARTP-627 - Remove icon-popout title

- src/client/src/ui/status-bar/assets/OpenFinLogo.tsx
> ARTP-634 - Remove the strange tooltip on the OpenFin logo, bottom right

- src/client/src/rt-util/hooks/index.ts
- src/client/src/rt-util/hooks/useForceUpdate.ts
- src/client/src/rt-util/hooks/useWindowSize.ts
- src/client/src/rt-util/index.ts
- src/client/src/ui/analytics/components/Analytics.tsx
- src/client/src/ui/analytics/components/analyticsLineChart/AnalyticsLineChart.tsx
- Converted `Analytics` and `AnalyticsLineChart` to use hooks
- Added custom hooks `useForceUpdate` and `useWindowSize`
> ARTP-602 - Use React hooks in Reactive Analytics client

- src/client/public/config/openfin/demo.json
Update openfin config to enable Layouts feature
> ARTP-621 Add layouts service for demo to enable Snap and dock, tabbing... features

- src/client/src/ui/analytics/components/analyticsBarChart/PNLBar.tsx
- src/client/src/ui/analytics/components/analyticsBarChart/styled.tsx
> ARTP-638 - On hover of the amount in PnL tab range indicators, you should be able to see the precise amount

- src/client/Dockerfile.dev
Realised that storybook was added to the dockerfile.dev which is not supposed to be there.
> Dockerfile.dev clean up

- src/client/src/shell/components/app-header/Header.tsx
- src/client/src/ui/blotter/components/BlotterHeader.tsx
- feat: Updated BlotterHeader to use react hooks.
- fix: removed `type={themeName || 'primary'}` from IconButton.
- type for button should be submit || button || reset, so it wouldn't compile
> Artp 598/feat added react hooks

- src/client/package-lock.json
- src/client/package.json
a simple package addition. works out of box
> add openfin-fdc3

- src/client/src/ui/blotter/epics/blotterHighlightEpic.ts
Make sure we don't error when clicking "highlight trade in blotter" and the trade is no longer present in the blotter.
https://weareadaptive.atlassian.net/browse/ARTP-667
> ARTP-667: Prevent errors when selecting "Highlight Trade in Blotter"

- src/client/public/config/openfin/demo.json
- src/client/public/config/openfin/dev.json
- src/client/public/config/openfin/launcher-demo.json
- src/client/public/config/openfin/launcher-dev.json
- src/client/public/config/openfin/launcher-local.json
- src/client/public/config/openfin/local.json
Disables tabbing in the layouts configs for all configurations.
https://weareadaptive.atlassian.net/browse/ARTP-668
> ARTP-668: Disables tabbing across all configs

- src/client/src/rt-components/tear-off/TearOff.tsx
- src/client/src/shell/routes/ShellRoute.tsx
- src/client/src/ui/workspace/Workspace.tsx
new boolean to set dragable functionality
> Only allow drag tear off on tiles

- src/client/public/config/openfin/local.json
- src/client/src/rt-components/platform/adapters/browser/browser.ts
- src/client/src/rt-components/platform/adapters/finsemble/finsemble.ts
- src/client/src/rt-components/platform/adapters/openfin/openFin.ts
- src/client/src/rt-components/platform/adapters/platformAdapter.ts
- src/client/src/ui/blotter/components/Blotter.tsx
This PR is the first step to using fdc3 context. Here we broadcast the currency pair when the user clicks on a row in the blotter. Separately in Adaptive Insights, there will be a PR for that app to receive the RT context.
> feat[fdc3]: broadcast currency pair from blotter

- src/client/src/ui/blotter/components/Blotter.tsx
Updating the shape of the context passed while clicking on the blotter row to be inline with fdc3 standards. Adds a market key for easier consumption in Reactive Analytics.
> update shape of context

- docs/setup/windows-setup.md
Installing Crossbar was the trickiest part of setting up the server locally for me. I've changed the instructions to be more helpful
> Improve instructions for installing crossbar on Windows

- src/client/src/rt-platforms/browser/window.ts
Give a position offset to the torn windows so that they don't completely overlap one another.
> add position offset to torn windows in browser

- src/client/__tests__/helpers/index.tsx
- src/client/package.json
- src/client/src/apps/MainRoute/MainRoute.tsx
- src/client/src/apps/MainRoute/layouts/reducer.ts
- src/client/src/apps/MainRoute/routes/ShellRoute.tsx
- src/client/src/apps/MainRoute/store/index.ts
- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
- src/client/src/apps/SimpleLauncher/Launcher.tsx
- src/client/src/apps/SimpleLauncher/tools.ts
- src/client/src/index.tsx
- src/client/src/rt-platforms/excelApp.ts
- src/client/src/rt-platforms/finsemble/index.ts
- src/client/src/rt-platforms/index.ts
- src/client/src/rt-platforms/limitChecker.ts
- src/client/src/rt-platforms/openFin/index.ts
- src/client/src/rt-platforms/openFin/limitChecker/openFin.ts
- src/client/src/rt-platforms/platform.ts
- src/client/src/rt-storybook/Story/Story.tsx
- Remove platform implementation exports from top level of rt-platforms
- Replaced with `async getXxxPlatform()` functions which load the modules async
- Removed all submodule imports `import x from 'rt-platforms/x'` to help ensure not loading any platform code sync
- Made `createStore`/`createLimitChecker`/`createExcelApp` async
> ARTP-753: dynamic import platform implementation

- src/client/src/apps/MainRoute/widgets/spotTile/epics/rfqEpics.test.ts
- src/client/src/apps/MainRoute/widgets/spotTile/epics/rfqEpics.ts
> Reset spot tile after expired RFQ stays idle for a while

- .gitignore
- src/node-server/shared/package-lock.json
- src/node-server/shared/package.json
- src/node-server/shared/src/logger.ts
- src/node-server/shared/src/transport/AutoBahnConnection.ts
- src/node-server/shared/src/transport/AutoBahnTypeExtensions.ts
- src/node-server/shared/src/transport/AutobahnConnectionProxy.ts
- src/node-server/shared/src/transport/AutobahnSessionProxy.ts
- src/node-server/shared/src/transport/DisconnectionReason.ts
- src/node-server/shared/src/transport/ServiceStub.ts
- src/node-server/shared/src/transport/connectionStatus.ts
- src/node-server/shared/src/transport/connectionStream.ts
- src/node-server/shared/src/transport/connectionType.ts
- src/node-server/shared/src/transport/index.ts
- src/node-server/shared/tsconfig.json
- src/node-server/tsconfig-base.json
Example of use 
```
// node-server/service/tsconfig.json
{
"extends": "../../node-server/tsconfig-base",
"compilerOptions": {
"outDir": "lib"
},
"references": [
{"path": "../shared"}
],
"include": ["./src/**/*"]
}
```
> create shared server side folder

- src/client/src/apps/SpotlightRoute/Spotlight.tsx
- src/client/src/apps/SpotlightRoute/ThemedSpotlight.tsx
- src/client/src/apps/SpotlightRoute/index.ts
- src/client/src/apps/SpotlightRoute/reducer.ts
- src/client/src/apps/index.ts
- src/client/src/index.tsx
Simple app at http://localhost:3000/spotlight which allows user input and shows a response
Added a history feature so you can cursorup/cursordown to edit/redo previous commands
> ARTP-776: Basic spotlight app

- .circleci/config.yml
- src/services/kubernetes/nlp-deployment.yaml
Reverts AdaptiveConsulting/ReactiveTraderCloud#1213
> Revert "deploy nlp (second try)"

- src/client/src/apps/SpotlightRoute/Spotlight.tsx
- src/client/src/apps/SpotlightRoute/handleIntent.ts
- src/client/src/apps/SpotlightRoute/intent-handlers/defaultWindowConfig.ts
- src/client/src/apps/SpotlightRoute/intent-handlers/index.ts
- src/client/src/apps/SpotlightRoute/intent-handlers/showBlotter.ts
- src/client/src/apps/SpotlightRoute/intent-handlers/showCurrencyPair.ts
just opening blotter for now, no filtering
> Intial nlp blotter handler

- src/client/src/apps/SpotlightRoute/handleIntent.ts
- src/client/src/apps/SpotlightRoute/intent-handlers/showBlotter.ts
- src/client/src/rt-platforms/types.ts
Note: this PR only handles the Spotlight side of things (and not the blotter itself, which would need to subscribe to the `FilterBlotter` topic)
> use interop to update blotter filters

- src/client/package-lock.json
- src/client/package.json
- src/client/public/config/openfin/demo.json
- src/client/public/config/openfin/dev.json
- src/client/public/config/openfin/launcher-demo.json
- src/client/public/config/openfin/launcher-dev.json
- src/client/public/config/openfin/launcher-local.json
- src/client/public/config/openfin/local.json
- Remove scaling factor, forceLatest etc. from OpenFin runtime config
- Pin OpenFin service versions to same versions as in package.json
- Fix shortcut naming for launcher manifest
> ARTP-812: Pin OpenFin service versions to fix Demo

- src/client/src/apps/MainRoute/routes/BlotterRoute.tsx
- src/client/src/apps/MainRoute/widgets/blotter/BlotterContainer.tsx
- src/client/src/apps/MainRoute/widgets/blotter/blotterTradesFilter.ts
- src/client/src/apps/MainRoute/widgets/blotter/index.ts
- src/client/src/apps/SpotlightRoute/InlineBlotter.tsx
- src/client/src/apps/SpotlightRoute/Spotlight.tsx
- src/client/src/apps/SpotlightRoute/handleIntent.ts
- src/client/src/apps/SpotlightRoute/intent-handlers/showBlotter.ts
- src/client/src/apps/SpotlightRoute/responseMapper.ts
- connects Bloter route to nlp intent handling
- makes sure that filtering in Inline blotter is the same as in blotter route
> Connect blotter route to nlp

- src/client/src/apps/MainRoute/routes/BlotterRoute.tsx
- src/client/src/apps/MainRoute/widgets/blotter/BlotterContainer.tsx
- src/client/src/apps/MainRoute/widgets/blotter/blotterTradesFilter.ts
- src/client/src/apps/SpotlightRoute/InlineBlotter.tsx
- src/client/src/apps/SpotlightRoute/Spotlight.tsx
- src/client/src/apps/SpotlightRoute/handleIntent.ts
- src/client/src/apps/SpotlightRoute/intentUtils.ts
respect count of trades in the blotter
> respect count of trades in the blotter

- src/client/__tests__/e2e/pages/tile.component.ts
- src/client/__tests__/e2e/tests/trade.spec.ts
Added test for notional higher than allowed for streaming and the reset button
> Added test for high notional and reset button

- commitlint.config.js
- package-lock.json
- package.json
This adds commit linting to our repo. This has a serious impact on how we write our commits. You will no longer be able to commit something like "did blah", it would have to be something meaningful that will help to automatically increment versions using semantic versioning and auto-generate changelogs.
Please read about conventional commits here:
https://www.conventionalcommits.org/en/v1.0.0/
And here's the info about repo that helps us to lint commit messages in the pre-commit hook:
https://commitlint.js.org/#/guides-local-setup
Your commits will have to be prefixed with `feat: `/`fix: `, etc
> feat: add commit linting

- .editorconfig
- src/server/Adaptive.ReactiveTrader.Server.IntegrationTests/ExecuteTradeIntegrationTests.cs
Also added *.cs indent of 4 spaces in .editorconfig as that's default spacing in C# world
> Improved ExecuteTrade integration tests

- .circleci/config.yml
- src/services/kubernetes/analytics-deployment.yaml
- src/services/kubernetes/blotter-deployment.yaml
- src/services/kubernetes/bot-deployment.yaml
- src/services/kubernetes/broker-deployment.yaml
- src/services/kubernetes/client-deployment.yaml
- src/services/kubernetes/eventstore-deployment.yaml
- src/services/kubernetes/nlp-deployment.yaml
- src/services/kubernetes/pricehistory-deployment.yaml
- src/services/kubernetes/pricing-deployment.yaml
- src/services/kubernetes/referencedataread-deployment.yaml
- src/services/kubernetes/tradeexecution-deployment.yaml
- src/services/kubernetes/web-deployment.yml
Currently, adding a new deployment is a manual step.
This changes the process slightly. This build step:
- finds all matching `*-deployment.yaml` 
- does a variable substitution. The BUILD_NUMBER is the environment variable that will be replaced in the deploys.
- the `kubectl apply` command will create the deployment if it doesn't exist yet.
> build: create/update kubernetes deployment configuration

- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/TileBusinessLogic.ts
- src/e2e/src/tests/trade.spec.ts
disables trading if notional is zero
> fix: disable trading if notional is zero (ARTP-823)

- .circleci/config.yml
Use custom checkout only in main pipeline
> fix: using custom checkout only in main pipeline

- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/TileBusinessLogic.ts
- src/client/src/apps/MainRoute/widgets/spotTile/components/TileSwitch.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/selectors.test.ts
- src/client/src/apps/MainRoute/widgets/spotTile/selectors.ts
- src/node-server/nlp/package.json
Fixes exception when tile is torn off
> fix: fixing exception in torn off spot tile

- src/client/src/apps/MainRoute/routes/ShellRoute.tsx
- src/client/src/apps/MainRoute/widgets/blotter/components/Blotter.tsx
- src/client/src/apps/MainRoute/widgets/blotter/components/BlotterHeader.tsx
- src/client/src/apps/MainRoute/widgets/workspace/utils.ts
- src/client/src/rt-components/tear-off/TearOff.tsx
- src/client/src/rt-platforms/openFin/adapter/window.ts
- Tiles which were torn off by dragging will now appear at the position where user dragged them
- Tiles which were torn off by clicking on "pop out" button will appear at the position of the click
> fix: fixing tear-off positions (ARTP-628)

- src/node-server/nlp/package-lock.json
- src/node-server/nlp/package.json
Upgraded packages to versions without vulnerabilities
> fix(server): node nlp service security vulnerabilities (ARTP-881)

- .circleci/config.yml
- src/client/public/config/openfin/uat.json
- Set up circle to deploy merges to release/1.1 to UAT env
- Add UAT OpenFin manifest
> feat: release 1.1 UAT deployment (ARTP-875)

- src/client/lib/downloadInstaller.js
- src/client/package-lock.json
- src/client/package.json
Also regenerate Mac installers
> fix(client): update installer generator script for macOS

- src/client/src/apps/MainRoute/widgets/blotter/epics/blotterServiceEpic.ts
- src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/NotificationContainer.tsx
Change the date to the valueDate in the confirmation page and in the blotterService
> fix(client): incorrect confirmation date(ARTP-907)

- src/client/src/apps/MainRoute/widgets/spotTile/components/PriceControls/PriceControls.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/PriceControls/TileBookingSwitch.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/PriceControls/styled.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/PriceMovement.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/SpotTile.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/Tile.test.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/Tile.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
- src/client/src/apps/MainRoute/widgets/spotTile/components/TileSwitch.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/analyticsTile/AnalyticsTile.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/TileBooking.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/TileNotification.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/stories/PriceControls.stories.tsx
- src/e2e/src/pages/tile.component.ts
- src/e2e/src/tests/trade.spec.ts
- move the RFQ button into the correct div
- RFQ button now follow the zeplin design in non-analytic style (no zeplin in analytic style)
> fix(client): align RFQ functionality with Zeplin designs (ARTP-899)

- src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/TileBooking.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/epics/rfqEpics.test.ts
- src/client/src/apps/MainRoute/widgets/spotTile/epics/rfqEpics.ts
now RFQ not expiring before timer hits zero
> fix(client): rfq expiring before timer hits zero(ARTP-903)

- src/client/package.json
- src/client/src/apps/MainRoute/widgets/blotter/epics/blotterServiceEpic.ts
- src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/NotificationContainer.tsx
- src/client/src/apps/MainRoute/widgets/workspace/Workspace.tsx
- src/client/src/apps/MainRoute/widgets/workspace/workspaceHeader/WorkspaceHeader.tsx
- src/client/src/apps/SimpleLauncher/applicationConfigurations.tsx
- src/client/src/apps/SimpleLauncher/tools.ts
- src/client/src/apps/utils/openfin-utils.ts
- src/client/src/index.tsx
- src/e2e/src/tests/trade.spec.ts
- src/server/Adaptive.ReactiveTrader.Server.Pricing/MeanReversionRandomWalkPriceGenerator.cs
Merge changes back into master branch after the release of [Reactive Trader Cloud 1.2.1](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/releases/tag/v1.2.1).
> Release 1.2 -> Master

- src/client/public/config/openfin/launcher-demo.json
- src/client/public/config/openfin/launcher-dev.json
- src/client/public/config/openfin/launcher-local.json
- src/client/public/config/openfin/launcher-uat.json
- src/client/public/config/openfin/local.json
Chore prior to working on ARTP-877
> Chore: Tidy up openfin configs

- src/client/src/index.tsx
- src/client/tsconfig.json
- src/e2e/src/tests/trade.spec.ts
Re-submission of lost code due to merging error.
- browser header now displays correct deployment env alongside title
> feat(client): browser header displays env (ARTP-891)

- src/client/public/config/openfin/demo.app.json
- src/client/public/config/openfin/demo.json
- src/client/public/config/openfin/dev.json
- src/client/public/config/openfin/launcher-demo.json
- src/client/public/config/openfin/launcher-dev.json
- src/client/public/config/openfin/launcher-uat.json
- src/client/public/config/openfin/uat.json
This reverts commit 8651e5f0ba773c45db1f1f1b7cea82b6a399d835 and restore the openfin configs
> Revert "feat(client): remove redundant openfin configs [ARTP-877]"

- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
- src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/TileBooking.tsx
> fix(client): add more padding to executing status

- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
- src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/TileBooking.tsx
Before: 
After: 
viewport width smaller than 320px: 
viewport width between 320px and 400px:
viewport width 400px and up:
> fix(client): cancel RFQ button in non-graph view fixed (ARTP-961)

- src/client/src/apps/MainRoute/widgets/spotTile/components/analyticsTile/AnalyticsTile.tsx
It now stop ticking in RFQ mode for analytics tile
> fix(client): add rfq price in analytics view(ARTP-965)

- src/client/src/apps/MainRoute/widgets/spotTile/components/PriceControls/PriceControls.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/PriceControls/styled.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/analyticsTile/styled.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/TileBooking.tsx
- Centered executing booking pill in analytics
> fix(client): center executing booking pill

- src/client/src/apps/MainRoute/widgets/spotTile/components/PriceControls/PriceControls.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/PriceMovement.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/SpotTile.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
- src/client/src/apps/MainRoute/widgets/spotTile/components/analyticsTile/AnalyticsTile.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/TileBooking.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/stories/PriceControls.stories.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/stories/PriveMovement.stories.tsx
- add arrow sign to initiate rfq state (ARTP-967):
- align initiate rfq button in analytic view (ARTP-927):
- in horizontal view (ARTP-899):
- executing status:
> Fix/spot-tile (ARTP-927, 967, 899)

- src/client/src/apps/MainRoute/widgets/spotTile/components/PriceMovement.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/RfqTimer.tsx
- now it has equal space on either side
> fix(client): the space on either side of the Reject button are equal (ARTP-958)

- src/client/src/apps/MainRoute/widgets/spotTile/SpotTileContainer.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/SpotTile.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/analyticsTile/AnalyticsTile.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/analyticsTile/AnalyticsTileChart.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/model/dateUtils.test.ts
- src/client/src/apps/MainRoute/widgets/spotTile/model/dateUtils.ts
* memoize date formatter
* remove inline function creation
* memoize tile container redux mapping
> Improve tiles perf

- src/client/src/apps/SimpleLauncher/Launcher.tsx
See [this line](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/1429/files#diff-19068037819488e38ed57cebf6ff7b9bR60)
Also, a load of prettier changes 👀
> Catch exception from Launcher when run in the browser

- src/client/src/rt-platforms/openFin/components/OpenFinChrome.tsx
This PR is for having the functionality of being able to undock a popped out windows
> feat(client): undock button for pop-out (ARTP-944)

- src/client/src/apps/MainRoute/widgets/analytics/components/Analytics.tsx
- src/client/src/apps/MainRoute/widgets/analytics/components/AnalyticsWindowControls.tsx
- src/client/src/apps/MainRoute/widgets/analytics/components/ProfitAndLoss.tsx
- src/client/src/apps/MainRoute/widgets/analytics/components/styled.tsx
Still using the old icon, @zhouyuhe will do the replace
Attached:
Popped:
> feat(client): reworked analytics header to match others (ARTP-999)

- package-lock.json
- package.json
- src/client/package-lock.json
- src/client/package.json
- src/client/src/apps/MainRoute/data/compositeStatus/index.ts
- src/client/src/apps/MainRoute/data/connectionStatus/connectionStatusService.ts
- src/client/src/apps/MainRoute/data/connectionStatus/index.ts
- src/client/src/apps/MainRoute/data/referenceData/index.ts
- src/client/src/apps/MainRoute/widgets/analytics/model/currencyPairPosition.ts
- src/client/src/apps/MainRoute/widgets/analytics/model/index.ts
- src/client/src/apps/MainRoute/widgets/blotter/index.ts
- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
- src/client/src/apps/MainRoute/widgets/spotTile/model/index.ts
- src/client/src/apps/MainRoute/widgets/status-bar/StatusBar.stories.tsx
- src/client/src/apps/MainRoute/widgets/workspace/Workspace.tsx
- src/client/src/apps/StyleguideRoute/components/ColorBlocks.tsx
- src/client/src/apps/StyleguideRoute/components/FormGrid.tsx
- src/client/src/apps/StyleguideRoute/sections/Atoms.tsx
- src/client/src/apps/StyleguideRoute/sections/CoreBranding.tsx
- src/client/src/apps/StyleguideRoute/styled/index.tsx
- src/client/src/rt-platforms/index.ts
- src/client/src/rt-platforms/symphony/index.ts
- src/client/src/rt-styleguide/components/Input.tsx
- src/client/src/rt-styleguide/index.ts
- src/client/src/rt-system/index.ts
- src/client/src/rt-theme/index.ts
- src/client/src/rt-types/index.ts
- src/client/src/rt-util/index.ts
- src/client/tsconfig.json
Screenshots from Input elements from the styleguide:
light theme:
dark theme:
> feat(styleguide): input added to atoms section(ARTP-956)

- src/client/src/apps/MainRoute/widgets/spotTile/components/PriceButton/PriceButton.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/PriceButton/styled.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
- src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/TileBooking.tsx
> fix(client): rfq-button now in the right position(ARTP-1021)

- src/client/src/apps/MainRoute/Router.tsx
> fix(launcher): missing control buttons in launcher apps

- src/client/src/apps/SimpleLauncher/icons/maximiseScreenIcon.tsx
- src/client/src/apps/SimpleLauncher/icons/popInIcon.tsx
- src/client/src/rt-components/icons/ChartIcon.tsx
- src/client/src/rt-components/icons/ChevronIcon.tsx
- src/client/src/rt-components/icons/CrossIcon.tsx
- src/client/src/rt-components/icons/DownloadIcon.tsx
- src/client/src/rt-components/icons/FilterIcon.tsx
- src/client/src/rt-components/icons/MaximizeIcon.tsx
- src/client/src/rt-components/icons/MinimizeIcon.tsx
- src/client/src/rt-components/icons/PopInIcon.tsx
- src/client/src/rt-components/icons/PopoutIcon.tsx
- src/client/src/rt-platforms/openFin/components/OpenFinChrome.tsx
This PR fixes the warning from the console
> fix(client): fix console warning

- src/client/public/config/openfin/launcher-dev.json
- src/client/public/config/openfin/launcher-uat.json
This PR is to update the old launcher config to match the new config
> fix(config): update old launcher config to match the new one

- src/client/src/apps/SimpleLauncher/windowUtils.ts
This PR fixes the problem with launcher resize issue
> Fix launcher resize ARTP1028

- src/client/src/apps/MainRoute/Router.tsx
- src/client/src/rt-interop/intents/showMarket.ts
This PR fixes the bug where the market launched from launcher is not showing properly.
> fix(launcher): fix market in launcher by updating the url (ARTP-1041)

- src/client/src/rt-interop/intents/showMarket.ts
This PR fixes a merging conflicts early on ARTP1046
> fix(launcher): fix a merging conflicts (ARTP-0146)

- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
- src/client/src/apps/SimpleLauncher/windowUtils.ts
- src/client/src/rt-components/route-wrapper/RouteWrapper.tsx
- src/client/src/rt-platforms/index.ts
- src/client/src/rt-platforms/openFin/adapter/index.ts
- src/client/src/rt-platforms/openFin/adapter/window.ts
- src/client/src/rt-platforms/openFin/components/OpenFinChrome.tsx
- src/client/src/rt-platforms/openFin/index.ts
This PR replace the popin button with close button when windows are launched from the launch bar
> feat(launcher): close button for popout from launcher (ARTP-1057)

- src/client/src/apps/SimpleLauncher/LaunchButton.tsx
- src/client/src/apps/SimpleLauncher/LauncherApps.tsx
- src/client/src/apps/SimpleLauncher/applicationConfigurations.tsx
- Update hover style according to zeplin
- Highlight opened apps
> feat(launcher): highlight opened apps - hover style (ARTP-1071)

- package-lock.json
- src/client/package-lock.json
- src/client/package.json
- src/client/src/apps/MainRoute/MainRoute.tsx
- src/client/src/rt-util/hooks/useWindowSize.ts
- src/client/src/rt-util/utilityTypes.ts
- src/server/node/bot/package-lock.json
- src/server/node/nlp/package-lock.json
- src/server/node/openfin-config/package-lock.json
- Recreate package-lock files with fresh installs to create new vulnerabilities
- Had to add a new utility function to use correct types with useState function
- Still 2 security vulnerabilities at root level that can't be fixed - needs a new version of lerna/handlebars
> fix(security): remove vulnerabilities (ARTP-1077)

- src/client/src/apps/SimpleLauncher/spotlight/components/InlineQuote.tsx
- src/client/src/apps/SimpleLauncher/spotlight/components/resultsTable.tsx
> Updates Pips in Launcher Quote Response

- src/client/src/apps/MainRoute/widgets/workspace/workspaceHeader/styled.tsx
> ARTP-1118: Fix currency nav item style when active

- src/client/src/apps/MainRoute/widgets/spotTile/components/PriceButton/styled.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
- src/client/src/apps/MainRoute/widgets/spotTile/components/analyticsTile/styled.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/notional/__snapshots__/NotionalInput.test.tsx.snap
- src/client/src/rt-theme/colors.ts
Updated spot tile state on hover in both light and dark theme
> ARTP-1115: fix buy/sell buttons color on tile hover

- src/client/src/apps/SimpleLauncher/LaunchButton.tsx
Fix moving search icon on hover
> fix(launcher): fix moving search icon on hover in launcher

- src/client/src/apps/SimpleLauncher/spotlight/components/InlineQuote.tsx
- src/client/src/apps/SimpleLauncher/spotlight/components/resultsTable.tsx
- src/client/src/apps/SimpleLauncher/spotlight/components/styles.ts
> ARTP-1117: Fix launcher results to have fixed width

- src/client/src/apps/MainRoute/components/app-header/Header.tsx
> ARTP-1125: Fix top navigation click area

- src/client/src/apps/MainRoute/data/referenceData/epics.ts
- src/client/src/apps/MainRoute/widgets/blotter/blotterService.ts
- src/client/src/apps/SimpleLauncher/SimpleLauncher.tsx
- src/client/src/apps/SimpleLauncher/spotlight/components/InlineBlotter.tsx
- src/client/src/apps/SimpleLauncher/spotlight/components/InlineMarketResults.tsx
- src/client/src/apps/SimpleLauncher/spotlight/components/InlineQuote.tsx
- src/client/src/apps/SimpleLauncher/spotlight/components/getInlineSuggestionsComponent.tsx
- src/client/src/apps/SimpleLauncher/spotlight/components/resultsTable.tsx
- src/client/src/apps/SimpleLauncher/spotlight/components/useMarketService.ts
- src/client/src/apps/SimpleLauncher/spotlight/components/utils.tsx
- src/client/src/apps/SimpleLauncher/spotlight/context.ts
- src/client/src/rt-interop/intents/responseMapper.ts
> Adds Market View NLP Response 

- src/client/src/apps/MainRoute/routes/ShellRoute.tsx
- src/client/src/apps/MainRoute/widgets/contact-us/ContactUs.tsx
- src/client/src/apps/MainRoute/widgets/contact-us/ContactUsButton.tsx
- src/client/src/apps/MainRoute/widgets/contact-us/FollowUs.tsx
- src/client/src/apps/MainRoute/widgets/contact-us/MailLogo.tsx
- src/client/src/apps/MainRoute/widgets/contact-us/index.ts
- src/client/src/apps/MainRoute/widgets/contact-us/styled.tsx
- src/client/src/apps/MainRoute/widgets/status-connection/styled.tsx
- src/client/src/rt-components/popup/Popup.tsx
- src/client/src/rt-components/popup/styled.tsx
> feat(CTA): Build CTA UI for 'Getting in Touch'

- src/client/src/apps/MainRoute/components/app-header/Header.stories.tsx
> fix(storybook): Fix header in storybook

- src/client/src/apps/MainRoute/components/app-header/LoginControls/styled.ts
> fix(header): Fix theme switcher divider on light theme

- src/client/src/apps/MainRoute/widgets/contact-us/ContactUs.stories.tsx
> chore(storybook): Add CTA button to storybook

- src/client/src/apps/MainRoute/widgets/contact-us/ContactUsButton.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
- src/client/src/apps/StyleguideRoute/sections/Iconography.tsx
- src/client/src/rt-components/icons/MailIcon.tsx
- src/client/src/rt-components/icons/index.ts
> chore(styleguide): Add mail icon from CTA to iconography

- src/client/src/apps/MainRoute/components/app-header/Header.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
- src/client/src/rt-platforms/getPlatformAsync.ts
- src/client/src/rt-platforms/openFin/components/OpenFinChrome.tsx
> ARTP-1130: Remove reactive trader in browser header

- src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/NotificationContainer.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/epics/spotTileEpics.ts
> ARTP-1134: Fix limit checker error not timing out on spot tile

- src/client/src/apps/MainRoute/components/notification/TradeNotification.stories.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/NotificationContainer.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/epics/executionService.ts
- src/client/src/apps/MainRoute/widgets/spotTile/epics/spotTileEpics.ts
- src/client/src/apps/MainRoute/widgets/spotTile/model/executeTradeRequest.ts
- src/client/src/apps/MainRoute/widgets/spotTile/model/spotTileData.ts
- src/e2e/src/utils/assert.utils.ts
> ARTP-1142/notification message

- src/client/src/apps/SimpleLauncher/Launcher.tsx
- src/client/src/apps/SimpleLauncher/spotlight/components/SearchControl.tsx
- src/client/src/apps/SimpleLauncher/spotlight/components/useNlpService.ts
> ARTP-1148: Fix launcher search results not resetting 

- src/client/src/rt-interop/intents/responseMapper.ts
> fix(launcher): Fix launcher button labels to spec

- src/client/src/apps/SimpleLauncher/spotlight/components/InlineQuote.tsx
- Fixes date formatting to DD MMM YYYY
> Launcher Inline Quote Date Formatting

- src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap
- src/client/src/apps/MainRoute/widgets/spotTile/components/styled.tsx
> fix(spot-tile): Fix spot tile highlight on light mode

- src/client/src/apps/MainRoute/routes/ShellRoute.tsx
> fix(live-rates): Fix spot tile dragging the whole live rates section

- src/client/src/apps/MainRoute/widgets/contact-us/ContactUs.tsx
- src/client/src/apps/MainRoute/widgets/contact-us/ContactUsButton.tsx
- src/client/src/apps/MainRoute/widgets/contact-us/FollowUs.tsx
- src/client/src/apps/MainRoute/widgets/contact-us/styled.tsx
- src/client/src/apps/MainRoute/widgets/contact-us/utils.ts
- Clicking the Contact Us pane no longer close it
- Email `mailto` link replaced by selectable/highlightable input field
- If in OpenFin uses `openUrlWithBrowser()` for links
> Contact Us Improvements

- src/client/src/apps/MainRoute/widgets/blotter/blotterTradesFilter.ts
- src/client/src/apps/SimpleLauncher/spotlight/components/useBlotterTrades.ts
> ARTP-1152/Fix launcher results not filtering correctly

- src/client/src/apps/SimpleLauncher/spotlight/components/InlineQuote.tsx
- src/client/src/apps/SimpleLauncher/spotlight/components/styles.ts
Brings date and table cell formatting in line with RTC.
> Date and Tablecell Formatting

- src/client/src/apps/StyleguideRoute/components/OnePageNavBar.tsx
Adjusts the offset used to measure the currently active section for better highlighting of active section nav link.
> Styleguide Header Section Highlighting

- src/client/src/apps/MainRoute/Router.tsx
- src/client/src/rt-components/route-wrapper/RouteWrapper.tsx
> fix(client): remove dash from live rates in headers

- src/client/src/apps/SimpleLauncher/spotlight/components/useBlotterTrades.ts
> fix(launcher): Fix inline blotter results

- src/client/src/apps/SimpleLauncher/spotlight/components/InlineBlotter.tsx
Updates trade results date formatting to match the rest of the application.
> Launcher Trade Results Date Formatting

- src/client/package-lock.json
- src/client/public/index.html
- src/client/src/apps/MainRoute/components/app-header/theme-switcher/ThemeSwitcher.tsx
- src/client/src/apps/StyleguideRoute/styled/index.tsx
- src/client/src/rt-platforms/index.ts
- src/client/src/rt-theme/index.ts
> ARTP-1175: Fix PWA header to switch themes correctly

- src/client/src/rt-platforms/browser/browser.ts
> ARTP-1180 (PWA): Enable popout

- src/client/src/index.tsx
- src/client/src/rt-util/getAppName.ts
- src/client/src/rt-util/index.ts
> ARTP-1174: add area specific title to popped out windows

- src/client/src/apps/MainRoute/widgets/workspace/workspaceHeader/CurrencyOptions.tsx
- src/client/src/apps/MainRoute/widgets/workspace/workspaceHeader/WorkspaceHeader.tsx
- src/client/src/apps/MainRoute/widgets/workspace/workspaceHeader/styled.tsx
- src/e2e/src/protractor.config.js
> fix(workspace): change currency filters to dropdown on smaller screens

- src/e2e/package-lock.json
- src/e2e/package.json
Update protractor to version 7.0.0
> Testautomation

- src/client/src/apps/MainRoute/widgets/workspace/workspaceHeader/CurrencyOptions.tsx
- src/client/src/apps/MainRoute/widgets/workspace/workspaceHeader/styled.tsx
- src/client/src/rt-theme/colors.ts
> fix(workspace): reimplement and restyle ccy filters dropdown

- src/client/src/apps/StyleguideRoute/components/DropdowGrid.tsx
- src/client/src/apps/StyleguideRoute/components/DropdownMenuGrid.tsx
- src/client/src/apps/StyleguideRoute/components/FormGrid.tsx
- src/client/src/apps/StyleguideRoute/components/ListItemGrid.tsx
- src/client/src/apps/StyleguideRoute/sections/Atoms.tsx
- src/client/src/rt-styleguide/components/Dropdown.tsx
- src/client/src/rt-styleguide/components/DropdownMenu.tsx
- src/client/src/rt-styleguide/components/ListItem.tsx
- src/client/src/rt-styleguide/index.ts
> chore(styleguide): add dropdown atoms to styleguide

- src/client/public/openfin/launcher.json
Disables the snap and dock feature from the launcher only. Main application and its children still have snap and dock capabilities.
> ARTP-1190: disable snap and dock from launcher config

- src/client/src/apps/MainRoute/components/app-header/PWAInstallBanner/usePWABannerPrompt.tsx
A test to see if the Android native PWA installation can be utilized
> fix(workspace): native android pwa (ARTP-1211)

- docs/deployment/kubernetes-locally.md
- src/services/kubernetes/analytics-deployment.yaml
- src/services/kubernetes/blotter-deployment.yaml
- src/services/kubernetes/bot-deployment.yaml
- src/services/kubernetes/broker-deployment.yaml
- src/services/kubernetes/client-deployment.yaml
- src/services/kubernetes/deploy_locally.sh
- src/services/kubernetes/eventstore-deployment.yaml
- src/services/kubernetes/initialise/initialise-job.yaml
- src/services/kubernetes/nlp-deployment.yaml
- src/services/kubernetes/pricehistory-deployment.yaml
- src/services/kubernetes/pricing-deployment.yaml
- src/services/kubernetes/referencedataread-deployment.yaml
- src/services/kubernetes/tradeexecution-deployment.yaml
- src/services/kubernetes/web-deployment.yaml
As in the title, I added the ability to deploy the application on a Kubernetes cluster running with [microk8s](https://microk8s.io/).
I also wrote a documentation file explaining how to set it up and a bash script that will build, push and deploy everything for you.
> Added ability to run with local kubernetes cluster

- src/client/src/apps/utils/openfin-utils.ts
**Changes:**
- Add FDC3 API to application config
**Notes:**
Tested on Linux Ubuntu and Windows 10
> fix(client): add fdc3 api to app config (ARTP-1269)

- src/client/package.json
- src/client/public/config/openfin/demo.json
- src/client/public/index.html
- src/client/public/manifest.json
- src/client/public/openfin/app.json
- src/client/public/symphony/bundle.json
- src/client/src/apps/MainRoute/components/app-header/PWAInstallPrompt/PWAInstallPrompt.tsx
- src/client/src/apps/MainRoute/routes/BlotterRoute.tsx
- src/client/src/apps/SimpleLauncher/applicationConfigurations.tsx
- src/client/src/rt-platforms/glue/Reactive Trader Workspace.json
- src/client/src/rt-platforms/glue/reactive-trader.json
- src/client/src/rt-util/getAppName.ts
I am unable to access the Launcher so I'm not sure if the last two screenshots on the Kanban card have the TM logo added but if they draw from the same place as the others (getAppName()) then they should work as well. I also added TM to every instance of the word "Reactive Trader" in the codebase. I'm not sure if this is completely necessary and I can revert it back if need be. I believe the only relevant area that needed to be changed was in getAppName() and maybe one other place. 
Here are the screenshots from my browser. You can see the TM reflected in the pop-out browser header at the very top:
> Add trademark

- src/client/src/apps/MainRoute/routes/BlotterRoute.tsx
> removed margin and padding on bottom of blotter

- src/client/src/apps/MainRoute/MainRoute.tsx
- src/client/src/apps/SimpleLauncher/SimpleLauncher.tsx
- src/client/src/apps/SimpleLauncher/spotlight/components/getInlineSuggestionsComponent.tsx
- src/client/src/apps/StyleguideRoute/StyleguideRoute.tsx
- src/client/src/rt-platforms/symphony/symphonyController.ts
I fixed the issue with the TM not appearing in the browser tab. I believe MainRoute.tsx was the culprit but I added TM to a few more areas in the code just in case there are other cases were TM does not appear.
> fix(client): trademark-to-appear-on-tab (ARTP-1316)

- src/client/src/apps/SimpleLauncher/applicationConfigurations.tsx
Now that manifest mode is available, launch RA that way too
> feat(launcher): launch reactive analytics from openfin manifest

- src/client/src/rt-platforms/openfin-platform/components/OpenFinSubWindowFrame.tsx
- src/client/src/rt-platforms/openfin-platform/components/OpenFinWindowFrame.tsx
> fix: style drag handles (ARTP-1318)

- src/client/src/apps/MainRoute/widgets/spotTile/components/SpotTile.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/analyticsTile/AnalyticsTile.tsx
- src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/TileBooking.tsx
Disabling RFQ booking when the user has entered a notional value that exceeds our hardcoded limit.
> ARTP-1326 disable RFQ when max exceeded

- src/server/node/bot/.env
- src/server/node/bot/.env.example
- src/server/node/bot/.gitignore
- src/server/node/bot/README.MD
* Use `.env.example` to seed local `.env` file
* Update .env keys for Symphony Bot Authentication
* Include instructions for Google Dialog Flow authentication
With this, I am able to converse with a Symphony Bot running locally. All features are currently working on V1 & V2 of the Symphony Client
> Artp 1331 symphony bot

- README.md
- src/client/install/README.md
- src/client/package.json
- src/client/public/config/openfin/demo.json
- src/client/public/index.html
- src/client/public/manifest.json
- src/client/public/openfin/app.json
- src/client/public/symphony/bundle.json
- src/client/src/apps/MainRoute/MainRoute.tsx
- src/client/src/apps/MainRoute/components/app-header/PWAInstallPrompt/PWAInstallPrompt.tsx
- src/client/src/apps/SimpleLauncher/applicationConfigurations.tsx
- src/client/src/apps/SimpleLauncher/spotlight/components/getInlineSuggestionsComponent.tsx
- src/client/src/apps/StyleguideRoute/StyleguideRoute.tsx
- src/client/src/rt-platforms/glue/Reactive Trader Workspace.json
- src/client/src/rt-platforms/glue/reactive-trader.json
- src/client/src/rt-util/getAppName.ts
- src/e2e/src/tests/trade.spec.ts
chore: change TM to R(ARTP1356)
-change the ™ to ® in all the places required.
> chore: Change Mark from TM to R(ARTP1356)

- src/client/src/rt-platforms/openfin/components/LayoutLockToggleSwitch.tsx
> fix(client): style openfin layout lock (ARTP-1369)

- src/new-client/src/App/LiveRates/LiveRates.tsx
- src/new-client/src/App/LiveRates/MainHeader.tsx
- src/new-client/src/App/LiveRates/MainPanel.tsx
- src/new-client/src/App/LiveRates/TileSwitch.tsx
- src/new-client/src/App/LiveRates/Tiles/AnalyticsTile/AnalyticsTile.tsx
- src/new-client/src/App/LiveRates/Tiles/AnalyticsTile/AnalyticsTileChart.tsx
- src/new-client/src/App/LiveRates/Tiles/AnalyticsTile/styled.tsx
- src/new-client/src/App/LiveRates/Tiles/Notional.tsx
- src/new-client/src/App/LiveRates/Tiles/PriceControls/PriceButton.tsx
- src/new-client/src/App/LiveRates/Tiles/PriceControls/PriceControls.tsx
- src/new-client/src/App/LiveRates/Tiles/PriceControls/PriceMovement.tsx
- src/new-client/src/App/LiveRates/Tiles/PriceControls/styled.tsx
- src/new-client/src/App/LiveRates/Tiles/SpotTile/SpotTile.tsx
- src/new-client/src/App/LiveRates/Tiles/SpotTile/styled.tsx
- src/new-client/src/App/LiveRates/Tiles/TileHeader.tsx
- src/new-client/src/App/LiveRates/Tiles/styled.tsx
- src/new-client/src/App/LiveRates/styled.tsx
- src/new-client/src/App/LiveRates/types.ts
- src/new-client/src/App/LiveRates/util.ts
- src/new-client/src/App/Trades/BlotterGrid/SetFilter/SetFilter.tsx
- src/new-client/src/services/currencyPairs.ts
- src/new-client/src/services/tiles.ts
> refactor: tiles for new architecture(657)

- src/new-client/src/App/Analytics/Positions/Positions.tsx
- src/new-client/src/App/Analytics/ProfitAndLoss/LineChart/LineChart.tsx
- src/new-client/src/App/LiveRates/MainPanel.tsx
- src/new-client/src/App/LiveRates/TileSwitch.tsx
- src/new-client/src/App/LiveRates/Tiles/AnalyticsTile/AnalyticsTileChart.tsx
- src/new-client/src/App/LiveRates/Tiles/Notional.tsx
After we put together all the different pieces of work that @iprado78 , @slcfv3  and myself have been working on under the `new-client` folder things are starting to look really good in the screen 🎉 . However, the console became an endless stream of warnings and noise. These commits get rid of most of that noise.
(I will squash when I merge)
> New client chores

- src/new-client/src/App/LiveRates/Tiles/AnalyticsTile/AnalyticsTile.tsx
- src/new-client/src/App/LiveRates/Tiles/Notional.tsx
- src/new-client/src/App/LiveRates/Tiles/PriceControls/PriceControls.tsx
- src/new-client/src/App/LiveRates/Tiles/PriceControls/PriceMovement.tsx
- src/new-client/src/App/LiveRates/Tiles/styled.tsx
-add colors to priceMovement components
-add colors to notional components
-small changes to tile charts
> feat(colors): tiles add colors

- src/new-client/package.json
- src/new-client/src/App/Analytics/Positions/Positions.tsx
- src/new-client/src/App/Analytics/Positions/data.ts
- src/new-client/src/App/Analytics/styled.tsx
- src/new-client/yarn.lock
This PR generally improves the position bubble chart code as a part of moving it over to the new client. The first step of this process was to upgrade our version of D3, the library powering the bubble physics simulation, to v6 (we were previously on v3). From there, I simplified a lot of the code by removing calculations that we were doing manually and using D3 to achieve the same. The types still aren't great in a few places, but I tried to fix the low hanging fruit in this regard.
> Refactor: upgrade and improve position bubble chart

- src/server/node/bot/README.MD
- src/server/node/bot/package-lock.json
- src/server/node/bot/package.json
- src/server/node/bot/src/connection/ServiceStub.ts
- src/server/node/bot/src/connection/WsConnection.ts
- src/server/node/bot/src/handlers/defaultIntentHandler.ts
- src/server/node/bot/src/handlers/handlers.ts
- src/server/node/bot/src/handlers/index.ts
- src/server/node/bot/src/handlers/marketIntentHandler.ts
- src/server/node/bot/src/handlers/priceQuoteIntentHandler.ts
- src/server/node/bot/src/handlers/tradeIntentHandler.ts
- src/server/node/bot/src/handlers/tradeNotificationHandler.ts
- src/server/node/bot/src/index.ts
- src/server/node/bot/src/rt-services.ts
- src/server/node/bot/src/symphony/SymphonyClient.ts
* file names matching default exports of handlers
* upgrades to latest version of StompRX to consume error observables. This should give us a better idea of what could be causing the initial price feed handshake to not always resolve
* restart instructions for node bot - in the event of a failed connection, this should do it
> chore(server): bot reconnect instruction; update bot imports

- src/new-client/src/App/Analytics/Positions/Positions.tsx
- src/new-client/src/services/prices.ts
-temporary fix the tile chart jump point issue
> refactor(new-client): fix tile chart jump point

- src/new-client/src/App/Trades/TradesGrid/TradesGrid.tsx
- src/new-client/src/App/Trades/TradesHeader/ExcelButton.tsx
-Export the trades new table to csv file
> feat(new-client): export excel button(713)

- src/new-client/src/App/Footer/StatusButton/StatusButton.tsx
- src/new-client/src/App/Header/theme-switcher/DarkThemeIcon.tsx
- src/new-client/src/App/LiveRates/Tiles/PriceButton/PriceButtonStyles.tsx
This PR fixes the Buy/Sell buttons by adjusting the min-width.
This PR also:
- Wraps Github API call in try/catch 
- Adjusts dark theme icon to fit better
> Buy/Sell CSS Fixes

- src/new-client/src/App/LiveRates/Tiles/AnalyticsTile.tsx
- src/new-client/src/App/LiveRates/Tiles/ExecutionStatusAlertSwitch/ExecutionStatusAlertSwitch.tsx
- src/new-client/src/App/LiveRates/Tiles/ExecutionStatusAlertSwitch/Pending.tsx
- src/new-client/src/App/LiveRates/Tiles/ExecutionStatusAlertSwitch/Response.tsx
- src/new-client/src/App/LiveRates/Tiles/ExecutionStatusAlertSwitch/index.tsx
- src/new-client/src/App/LiveRates/Tiles/ExecutionStatusAlertSwitch/styled.tsx
- src/new-client/src/App/LiveRates/Tiles/Notional.tsx
- src/new-client/src/App/LiveRates/Tiles/PriceButton/PriceButton.tsx
- src/new-client/src/App/LiveRates/Tiles/PriceMovement.tsx
- src/new-client/src/App/LiveRates/Tiles/Tile.tsx
- src/new-client/src/App/LiveRates/Tiles/TileHeader.tsx
- src/new-client/src/services/executions.ts
* Add execution service
* UI for trade accepted/rejected
> feat(client): add execution service

- src/new-client/public/index.html
- src/new-client/src/App/Analytics/styled.tsx
- src/new-client/src/App/Footer/ContactUsButton/styled.tsx
- src/new-client/src/App/LiveRates/MainHeader/CurrencyOptions.tsx
- src/new-client/src/App/LiveRates/MainHeader/MainHeader.tsx
- src/new-client/src/App/LiveRates/Tiles/ExecutionStatusAlertSwitch/Pending.tsx
- src/new-client/src/App/LiveRates/Tiles/ExecutionStatusAlertSwitch/Response.tsx
- src/new-client/src/App/LiveRates/Tiles/ExecutionStatusAlertSwitch/styled.tsx
- src/new-client/src/App/LiveRates/Tiles/Notional.tsx
- src/new-client/src/App/LiveRates/Tiles/PriceButton/PriceButton.tsx
- src/new-client/src/App/LiveRates/Tiles/PriceButton/PriceButtonStyles.tsx
- src/new-client/src/App/LiveRates/Tiles/PriceMovement.tsx
- src/new-client/src/App/LiveRates/Tiles/Tile.tsx
- src/new-client/src/App/LiveRates/Tiles/TileHeader.tsx
- src/new-client/src/App/LiveRates/Tiles/responsiveWrappers.tsx
- src/new-client/src/App/LiveRates/Tiles/styled.tsx
-refined the stylings of new-client to match old client's stylings
> feat(new-client): refine the stylings(722)

- src/new-client/package.json
- src/new-client/src/services/trades/index.ts
- src/new-client/src/services/trades/trades.test.tsx
- src/new-client/src/services/trades/trades.ts
- src/new-client/src/services/trades/types.ts
- src/new-client/yarn.lock
Yesterday I mistakenly pushed these changes into the wrong branch and then it didn't get merged with my previous PR. These are the tests that we migrated yesterday from @iprado78 's PR #1764 , I've added him as a co-author of this commit, of course.
> test(new-client): trades service

- src/new-client/.env.development
- src/new-client/src/App/Trades/TradesGrid/NumFilter.tsx
- src/new-client/src/App/Trades/TradesGrid/SetFilter.tsx
- src/new-client/src/App/Trades/TradesGrid/TableHeadCell.tsx
- src/new-client/src/App/Trades/TradesGrid/TradesGrid.tsx
- src/new-client/src/App/Trades/TradesHeader/AppliedFilters.tsx
- src/new-client/src/App/Trades/TradesState/colConfig.ts
- src/new-client/src/App/Trades/TradesState/filterState.ts
- src/new-client/src/App/Trades/TradesState/index.ts
- src/new-client/src/App/Trades/TradesState/tableTrades.ts
- src/new-client/src/services/executions/types.ts
- src/new-client/src/services/trades/trades.ts
- src/new-client/src/services/trades/types.ts
-align the number columns to right, as old client
-add filters to number column like notional
-fix a small issue of set filter
> feat(new-client): add number filter to trades(736)

- src/new-client/src/App/LiveRates/Tile/Tile.test.tsx
This test works well so far but will take over 5s to finish since I added timeout option in waitFor(), should I use sinon instead for this case?
> test(new-client): test tile component too long execution(753)

- src/new-client/src/App/LiveRates/Tile/Notional/Notional.tsx
- src/new-client/src/App/LiveRates/Tile/Notional/NotionalReset.tsx
- src/new-client/src/App/LiveRates/Tile/PriceButton/PriceButton.tsx
- src/new-client/src/App/LiveRates/Tile/PriceMovement/PriceMovement.tsx
- src/new-client/src/App/LiveRates/Tile/Rfq/Rfq.state.ts
- src/new-client/src/App/LiveRates/Tile/Rfq/RfqButton.tsx
- src/new-client/src/App/LiveRates/Tile/Rfq/RfqTimer.tsx
- src/new-client/src/App/LiveRates/Tile/Tile.state.ts
- src/new-client/src/App/LiveRates/Tile/Tile.tsx
Hi @iprado78 , let's pair program on this stuff together whenever you have a chance. Thanks!
> chore(new-client): refactor RFQ

- src/services/kubernetes/per-cluster/gateway.yaml
This enables gzip compression and content caching on the ingress gateway.
Lighthouse report: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fpr1824.beta.lb.adaptivecluster.com%2F
> feat: update caching and compression on gateway proxy

- .github/workflows/pull-origin-up.yml
Add more detail to the auto-deploy comment:
1. a link to the dev (master branch) build of the new client
2. a link to the Lighthouse score
3. some description about how these links should be used in the course of code review
See link below.
> Enrich auto-deploy comment on pull requests

- src/new-client/src/App/Analytics/Positions/Positions.tsx
- src/new-client/src/App/Analytics/Positions/data.ts
I just enjoy deleting code... :sweat_smile:
> fix(new-client): add/remove position bubbles (807)

- src/new-client/src/App/Analytics/Analytics.tsx
- src/new-client/src/App/App.tsx
- src/new-client/src/components/Resizer.tsx
As I was addressing this issue, I noticed that the `Resizer` component needed some love, which is something that @bhavesh-desai-scratch had already pointed out to me in the past, so I decided to fix that too in a separate commit.
> Fix Analytics panel responsive issue with FF

- src/new-client/src/App/LiveRates/Tile/Rfq/Rfq.state.ts
It doesn't happen everyday that [we get the luxury of having Ben Lesh review our code](https://twitter.com/BenLesh/status/1375483046598742017).
Also, since one of the purposes of this code-base is to help new comers understand the benefits of using react-rxjs, I think that I will start refactoring many other parts to look a lot more like this.
> chore(new-client): improve RFQ workflow

- src/new-client/package-lock.json
- src/new-client/package.json
- src/new-client/src/App/LiveRates/Tile/Tile.test.tsx
- src/new-client/src/services/status/status.test.tsx
It turns out that we can just use `jest.useFakeTimers()`! :tada:
> test(new-client): fix timers issue

- src/services/kubernetes/per-cluster/inbound-tls.yaml
- src/services/kubernetes/per-cluster/rt-ingress-demo.yaml
- src/services/kubernetes/per-cluster/rt-ingress-dev.yaml
- src/services/kubernetes/per-cluster/rt-ingress-uat.yaml
- src/services/kubernetes/per-deployment/ingress.yaml
DNS propagation time of TXT records is too slow for PR builds.
> HTTP01 ACME challenge for (ns).lb.adaptivecluster.com certs

- src/new-client/src/theme/ThemeContext.tsx
> feat(PWA): set title bar theme color dynamically

- src/new-client/src/OpenFin/Window/WindowFooter.tsx
> feat: add connection status to OpenFin footer

- src/new-client/src/OpenFin/DetachableTile/DetachableTile.tsx
- src/new-client/src/OpenFin/Window/WindowViewport.tsx
- src/new-client/src/OpenFin/components/OpenFinBrowserLink.tsx
> 909 show tear out hover

- src/new-client/src/App/Footer/common-styles.ts
- src/new-client/src/OpenFin/Footer/ContactUsButton.tsx
- src/new-client/src/OpenFin/OpenFinApp.tsx
- src/new-client/src/OpenFin/Window/WindowFooter.styles.ts
- src/new-client/src/OpenFin/Window/WindowFooter.tsx
> 904 contact button

- src/new-client/src/App/Analytics/Analytics.tsx
- src/new-client/src/App/Trades/Trades.tsx
simple addition of background aligning wrappers for Analytics / Trades with LiveRates
> 1167 fix Analytics/Trades wrapper background, add theme darkBackground

- src/new-client/src/App/Analytics/styled.tsx
- src/new-client/src/App/Trades/TradesGrid/TradesGrid.tsx
- src/new-client/src/App/Trades/TradesHeader/QuickFilter.tsx
- src/new-client/src/OpenFin/DetachableTile/DetachableTile.tsx
| Before | After |
| ---------|---------|
| ![image](https://user-images.githubusercontent.com/54838842/129002277-fb85f715-627e-45cd-8af1-bdf9a3ff6ffb.png) | ![Screenshot from 2021-08-11 10-23-36](https://user-images.githubusercontent.com/54838842/129004544-aa34f716-ca1a-42d9-97dd-92f58b070748.png) |
| ![image](https://user-images.githubusercontent.com/54838842/129002355-2b4170d0-26c7-465a-82cf-01affec929f8.png) | ![Screenshot from 2021-08-11 10-10-41](https://user-images.githubusercontent.com/54838842/129002553-5833f0e6-74be-4d72-931c-ec5e85d3c232.png) |
| ![image](https://user-images.githubusercontent.com/54838842/129002980-2d405c86-9f76-4b46-b4ac-170dd3837521.png) | ![Screenshot from 2021-08-11 10-13-06](https://user-images.githubusercontent.com/54838842/129002988-ab5db398-2134-4d83-a83 …
> fix: minor ui issues (BUG-1186)

- src/new-client/src/Finsemble/index.tsx
- src/new-client/src/OpenFin/index.tsx
- src/new-client/src/Web/index.tsx
- src/new-client/vite.config.ts
See corresponding deployments PR: https://github.com/AdaptiveConsulting/reactive-deployments/pull/3/files
> Hydra url as /ws (proxied in nginx)

- src/new-client/package-lock.json
- src/new-client/package.json
This fixes the UI on Safari/iOS.
Doesn't require a backend update.
> Bump Hydra to 3.24.0.

- src/new-client/src/App/Trades/TradesGrid/TradesGrid.tsx
> fix(client): Removed table height to fix expanding row

- .github/workflows/branch.yml
- .github/workflows/pull.yml
- .github/workflows/tag.yml
- src/new-client/src/App/Footer/Footer.tsx
- src/new-client/src/App/Footer/Version/Version.tsx
- src/new-client/src/App/Footer/Version/index.tsx
- src/new-client/src/App/Footer/Version/styled.tsx
- src/new-client/vite.config.ts
Added current build version to footer. 
Ported over from `./client` with some changes to make compatible with vite.
> feat(client): Added Version to Footer

- src/new-client/src/App/Footer/Version/Version.tsx
- src/new-client/src/Web/index.tsx
- src/new-client/src/index.tsx
Quick PR with small chanes to test the caching in dev environment.
> chore(client): Moved google analytics from index to web main

- src/new-client/src/App/Footer/ContactUsButton/ContactUs.tsx
- src/new-client/src/App/Footer/ContactUsButton/styled.tsx
A simple redirect when we click the sales email in the contact.
> feat(new-client): mail to redirect

- src/new-client/package-lock.json
- src/new-client/package.json
- src/new-client/src/App/DisconnectionOverlay.tsx
- src/new-client/src/App/Footer/StatusButton/StatusButton.tsx
- src/new-client/src/App/Trades/TradesState/tableTrades.ts
- src/new-client/src/Web/cacheUpdateModal.tsx
- src/new-client/src/components/Modal/Modal.styles.ts
- src/new-client/src/index.tsx
- src/new-client/src/services/connection.ts
Disconnects user after being idle for 15 minutes and shows a modal with button to reconnect.
> feat(new-client): Idle disconnect

- src/new-client/.storybook/main.js
- src/new-client/.storybook/manager-head.html
- src/new-client/src/constants.ts
Fixed public path for storybook
> fix: storybook public path

- src/new-client/src/App/LiveRates/Tile/TearOut/TornOutTile.finsemble.tsx
- src/new-client/src/App/LiveRates/Tile/TearOut/TornOutTile.tsx
- src/new-client/src/Web/index.tsx
- src/new-client/vite.config.ts
Added finsemble `TornOutTile` to fix analytics tile view
Updated vite `targetBuildPlugin` to support….tsx files
> fix: Finsemble Analytics Tiles

- src/new-client/index.html
- src/new-client/package-lock.json
- src/new-client/package.json
- src/new-client/src/App.tsx
- src/new-client/src/BrowserUnsupported.tsx
- src/new-client/src/dom.d.ts
- src/new-client/src/index.tsx
- src/new-client/vite.config.ts
Added browser unsupported message for browsers without `BigInt`
> fix(new-client): added browser unsupported message 

- src/new-client/README.md
First round of readme updates for new-client. More updates to follow
> chore(new-client): updated readme

- src/client/src/App/Credit/CreditRfqs/CreditRfqCards/CardFooter.tsx
- src/client/src/App/Credit/CreditRfqs/CreditRfqCards/CreditRfqCards.tsx
- src/client/src/App/Credit/CreditRfqs/CreditRfqCards/styled.tsx
- src/client/src/App/Credit/CreditSellSideTicket/CreditSellSideFooter.tsx
- src/client/src/App/Credit/CreditSellSideTicket/CreditSellSideHeader.tsx
- src/client/src/App/Credit/CreditSellSideTicket/CreditSellSideParameters.tsx
- src/client/src/App/Credit/CreditSellSideTicket/CreditSellSideTicket.tsx
- src/client/src/App/Credit/CreditSellSideTicket/CreditSellSideTicketCore.tsx
- src/client/src/App/Credit/CreditSellSideTicket/CreditSellSideTimer.tsx
- src/client/src/App/Credit/CreditSellSideTicket/index.ts
- src/client/src/App/Credit/CreditTimer.tsx
- src/client/src/App/Credit/index.ts
- src/client/src/Web/index.tsx
- src/client/src/constants.ts
- src/client/src/services/credit/creditRfqRequests/creditRfqRequests.ts
- src/client/src/services/credit/creditRfqs/creditRfqs.ts
- src/client/src/services/credit/creditRfqs/types.ts
- src/client/src/utils/window/openWindow.web.ts
TODO: Need server timestamp change
> feat(client): Sell side ticket to enter quotes

- src/client/src/App/Trades/TradesHeader/QuickFilter.tsx
Before: No action on keyboard input
https://user-images.githubusercontent.com/25262082/181528239-b9634207-7240-45d5-a351-218e51ebd074.mp4
After:
https://user-images.githubusercontent.com/25262082/181528648-21cf645e-c457-41cb-90e8-062a5c7f2df3.mp4
> fix(client): filter on blotter - ios (2547)

- .github/workflows/branch.yml
- .github/workflows/pull.yml
- .github/workflows/tag.yml
- src/client/package-lock.json
- src/client/src/App/LiveRates/MainHeader/MainHeader.test.tsx
- src/client/src/App/LiveRates/Tile/Tile.test.tsx
this restores master to working test suite
run tests on CI !
> chore(client): fix some tests that have been broken a while

- src/client/src/App/Header/InstrumentTypeSelector.tsx
- src/client/src/App/LiveRates/MainHeader/MainHeader.test.tsx
- src/client/src/App/Trades/__tests__/FxTrades.core.test.tsx
- src/client/src/App/Trades/__tests__/FxTrades.filter.test.tsx
- src/client/src/App/Trades/__tests__/FxTrades.quickFilter.test.tsx
- src/client/src/Web/index.tsx
per @ivanfalanga-adaptive's mods over on master #2118 
+ updated routing, adding fallback Redirect (e.g. if /credit attempted, will just show default)
+ fixed some failing credit-feature tests - Tile failures are as per master, so aim to fix there
> 2849: disable credit mobile

- src/client/src/services/credit/__mocks__/index.ts
- src/client/src/services/trades/__tests__/trades.test.ts
- src/client/src/services/trades/trades.ts
pick accepted quote from rfq for creditTrades$
> fix(credit): pick accepted quote for grid

- src/client/package-lock.json
- src/server/cloud/nlp/package-lock.json
- src/workspace/package-lock.json
simple one .. just using
```
npm upgrade minimist
npm upgrade minimatch
```
in all 3 active "workspaces"
> chore(deps): upgrade minimist/minimatch to fix vulnerabilities

- src/client/src/services/credit/creditRfqs/creditRfqs.ts
> Bugfix Rfq on load

- .github/workflows/schedule.yml
- src/client/.env
- src/client/.env.development
- src/client/e2e/blotter.spec.ts
- src/client/e2e/credit.spec.ts
- src/client/e2e/fixtures.ts
- src/client/e2e/spot-tile.spec.ts
- src/client/e2e/utils.ts
- src/client/public-openfin/rt-credit.json
- src/client/public-openfin/rt-fx.json
- src/client/src/App/Trades/TradesHeader/AppliedFilters.tsx
Added annotations to 2 tests for a minimal smoke test set.
Fixed some issues with the OpenFin tests.
Tidied up some tests and env files.
> Smoke test annotations, OpenFin test fixes

- .github/workflows/schedule.yml
- src/client/package.json
change scheduled e2e tests to only run smoke subset
> chore: schedule smoke tests

- src/workspace/src/home/index.ts
- src/workspace/src/home/nlpProvider.ts
- src/workspace/src/home/utils.ts
- src/workspace/src/utils.ts
> fix: adaptive logo shows on more search results

- src/workspace/vite.config.ts
.. further niggly issues in RA address substitution - the logic of choosing the correct RA address is needed in the code as well as the vite config ws json transformation .. hence a bit of juggling around process.env so the logic feeds the env (for the code) and the plugin (for the workspace JSON)
phew ...
> fix(workspace): correct RA address substitution in Home search

- src/workspace/src/home/index.ts
- src/workspace/src/home/nlpProvider.ts
- src/workspace/src/home/notifications.ts
- src/workspace/src/home/utils.ts
- src/workspace/src/services/currencyPairs.ts
- src/workspace/src/services/executions.ts
- src/workspace/src/services/prices.ts
- src/workspace/src/services/trades.ts
- src/workspace/tsconfig.json
- src/workspace/vite.config.ts
Added @ alias for src/ in the workspace directory.
> Workspace alias

- src/client/public-openfin/limit-checker.json
- src/client/src/App/Trades/TradesGrid/styled.ts
- src/client/src/OpenFin/apps/LimitChecker/LimitChecker.tsx
- src/client/src/OpenFin/apps/LimitChecker/LimitInput.tsx
- src/client/src/OpenFin/apps/LimitChecker/LimitInputList.tsx
- src/client/src/OpenFin/apps/LimitChecker/styled.ts
Updated limit checker
Horizontal blotter scrolling. (also applied to limit checker result table)
> improvement: new limit checker layout, blotter horizontal scroll

- src/client/src/App/Credit/CreditRfqs/CreditRfqCards/styled.tsx
- src/workspace/config/credit-rfqs.json
- src/workspace/package-lock.json
- src/workspace/package.json
- src/workspace/src/home/index.ts
- src/workspace/src/home/nlpProvider.ts
- src/workspace/src/provider.ts
- src/workspace/src/services/connection.ts
- src/workspace/src/services/creditDealers.ts
- src/workspace/src/services/creditInstruments.ts
- src/workspace/src/services/creditRfqRequests.ts
- src/workspace/src/services/creditRfqs.ts
- src/workspace/src/services/currencyPairs.ts
- src/workspace/src/services/nlpService.ts
- src/workspace/src/services/prices.ts
- src/workspace/src/services/trades.ts
- src/workspace/src/services/withConnection.ts
Feature for raising an RFQ from the Workspace home input bar.
After raising the rfq the user can open the credit rfqs view
> feat: workspace nlp rfq

- .github/workflows/branch-fork.yml
- .github/workflows/e2e-full.yml
- .github/workflows/e2e-smoke.yml
- .github/workflows/pull-fork.yml
- .github/workflows/tag.yml
Updated github workflows based on latest folder structure changes
> chore(maintenance): updated github workflows

- packages/client/src/client/App/Trades/TradesGrid/TableHeadCell.tsx
- packages/client/src/client/App/Trades/TradesGrid/TradesGridInner.tsx
- packages/client/src/client/App/Trades/TradesGrid/components/FilterPopup.tsx
Fixed an issue where the last filter popup would go outside the grid
Better aligned the left and right aligned popups
> fix: realigned popups to fit better into grid

- packages/client/e2e/limit-checker.spec.ts
- packages/client/e2e/utils.ts
- packages/client/src/client/App/Trades/TradesState/colConfig.ts
- packages/client/src/client/OpenFin/apps/LimitChecker/LimitCheckResults.tsx
- packages/client/src/client/OpenFin/apps/LimitChecker/state.ts
> fix: added limit column, notional column showing trade notional

- README.md
- packages/client/package-lock.json
- packages/client/package.json
we do not use husky, and it is something that is awkward to get rid of / upgrade
you will need to clean up (or just remove) your `.git/hooks` folder (_I just deleted everything apart from the default new repo .sample files_)
> chore: remove husky

- packages/client/src/client/App/Trades/CoreFxTrades.tsx
.. to simplify Finsemble interop
> chore: remove proto blotter intent handler

- packages/client/playwright/components/spotTile.component.ts
- packages/client/playwright/tests/spot-tile.spec.ts
This is final version for the Spot Tile Tests written on the revamped Playwright framework.
> Final Version for Spot Tile Tests 

- packages/client/src/client/Web/serviceWorkerRegistration.ts
tweak the SW reg so on first load it doesn't throw up the update dialog 🤦🏻
> fix:  prevent PWA prompt on first app load/install

- packages/client/package-lock.json
- packages/client/package.json
- packages/client/src/generated/TradingGateway.ts
- latest Hydra has recently updated dependencies, just keeping up to date and testing Hydra platform lib and codegen
- minor updates to codegen output (additional field `maxCount`)
.. plus the usual small crop of vulnerability updates - express/cookie and @sentry/browser
> update hydra to 4.70.0

- packages/client/.storybook/preview.tsx
Fix and use new brand colours in storybook
> chore: storybook fixes

- .github/workflows/branch-fork.yml
- .github/workflows/branch.yml
- .github/workflows/e2e-full.yml
- .github/workflows/e2e-smoke.yml
- .github/workflows/pull.yml
- .github/workflows/tag.yml
- packages/client/e2e/credit.spec.ts
- packages/client/e2e/fx-analytics.spec.ts
- packages/client/e2e/fx-blotter.spec.ts
- packages/client/e2e/fx-spot-tile.spec.ts
- packages/client/e2e/utils.ts
- packages/client/eslint.config.js
- packages/client/playwright.config.ts
- packages/client/src/client/App/Credit/CreditRfqs/CreditRfqCards/CreditRfqCard.tsx
- packages/client/src/client/setupTests.ts
- packages/client/src/client/utils/formatNumber.ts
- packages/client/src/client/utils/showRfqInSellSide.ts
- packages/client/src/client/utils/window/__tests__/openWindow.web.test.ts
- packages/client/src/client/utils/window/openWindow.openfin.ts
- packages/client/src/client/utils/window/openWindow.ts
- packages/client/src/client/utils/window/openWindow.web.ts
Web Credit has been failing (see Jira) intermittently on Dev - this is no slur on the Dev code, as it is only Dev that we the run _full_ Web E2E against, every weekday morning.
Note that it is only the PR build (normally) that runs OpenFin E2E at all .. it is suppressed here to give CI a break .. we do not see the issue on that platform (different Chromium? different timing?)
> chore: credit E2E crackdown

- .github/workflows/pull.yml
- packages/client/e2e/credit.spec.ts
- packages/client/e2e/fixtures.ts
- packages/client/e2e/pages/CreditBlotterPageObject.ts
- packages/client/e2e/pages/CreditNewRfqPageObject.ts
- packages/client/e2e/pages/CreditRfqTilesPageObject.ts
- packages/client/e2e/pages/CreditSellSidePageObject.ts
- packages/client/e2e/pages/index.ts
Add Page Object Models for Credit
Adjust and enhance E2E config, fixtures and credit specs accordingly
> Credit E2E - introduce page objects

- packages/client/src/client/OpenFin/apps/LimitChecker/LimitCheckResults.tsx
- packages/client/src/client/OpenFin/apps/LimitChecker/LimitChecker.tsx
- packages/client/src/client/OpenFin/apps/LimitChecker/LimitInputList.tsx
- packages/client/src/client/components/Stack.tsx
- packages/client/src/client/components/layout/Region/Region.tsx
- packages/client/src/client/components/layout/Region/RegionLayout.tsx
- packages/client/src/client/components/layout/types.ts
> Restyle limit checker
