AdaptiveConsulting/ReactiveTraderCloud

src/client/src/bootstrapper.js, src/client/src/ui/regions/views/popout/popoutRegionView.jsx
The JS client needs a way to differentiate a popout page from the full app page. In a popout the full JS bootstrapper doesn't run, hence the need to differentiate. 
Previously popouts were pointing to url `/popout` and the JS didn't load the bootstrapper at this URL, however nginx failed with a 404 as it tried to serve a non existent resource. 
The fix is to point popouts to `/#/popout` which is still a root url (keeping nginx happy) yet distinct enough for the JS to differentiate.
=> Popout nginx issue fix

src/client/src/index.html, src/client/src/ui/spotTile/views/priceButton.scss, src/client/src/ui/spotTile/views/spotTile.scss
Part of #106 
This font is the closest matching one to the visual designs we have out of the available Google web fonts. It's very subtly different - only the '0's are a bit thinner and the end of '3's are a tiny bit longer.
The proprietary design font probably doesn't conform to the FOSS style of this project anyway.
Rubik (Google web font):
=> use web font matching designs

src/client/src/ui/regions/views/workspace/workspaceItemContainer.scss, src/client/src/ui/regions/views/workspace/workspaceRegionView.jsx, src/client/src/ui/shell/views/shell.scss, src/client/src/ui/shell/views/shellView.js, src/client/src/ui/spotTile/views/tradeNotification.jsx, src/client/src/ui/spotTile/views/tradeNotification.scss
Make layout responsive. Tiles are now stretching and take all the available space in the workspace area. This also means we don't have a gap between the workspace and the analytics component anymore.
#106
=> Layout improvement

src/server/Adaptive.ReactiveTrader.Server.Pricing/MeanReversionRandomWalkPriceGenerator.cs, src/server/Adaptive.ReactiveTrader.Server.Pricing/PriceSource.cs, src/server/Adaptive.ReactiveTrader.Server.Pricing/RandomExtensions.cs, src/server/Adaptive.ReactiveTrader.Server.Pricing/RandomWalkPriceGenerator.cs
closes #229
- Bug: Random.Next(-5, 5) is not symmetric (min value is inclusive, max value is exclusive)
- Use mean reversion to stop prices diverging from initial value
- Use normal distribution to approximate prices moves
closes #230 
- Use % spread so that spreads can move (albeit not very often)
=> Improve price generation

src/client/config/openfin/demo.app.json, src/client/config/openfin/dev.app.json, src/client/config/openfin/local.app.json
Align config with reactive trader js config.
0 is also the default value for corner rounding...
Fixes #339
=> remove unnecessary openfin config

deploy/docker/prepare, deploy/docker/runAll
When the container are started without sleep between each, the .NET services throw exception. This should limit the problem until a fixe is applied to these services.
This PR is linked to https://github.com/AdaptiveConsulting/ReactiveTraderCloud/issues/504
=> temp fix to issue 504

src/client/src/configureStore.ts, src/client/src/pricingOperations.ts, src/client/src/system/openFin/openFin.ts, src/client/src/ui/analytics/analyticsOperations.ts, src/client/src/ui/blotter/blotterOperations.ts, src/client/src/ui/spotTile/spotTileOperations.ts
Looks like openfin CSV interop was not factored into recent refactors.
Functionality includes.
Ticking pricing in CSV, Show blotter in CSV, show positions in CSV and close positions
=> Get CSV functionality working

src/client/src/ui/analytics/Analytics.tsx
To recreate - pop-out the analytics window, then resize the main window. A console error is thrown:
```forceUpdate(...): Can only update a mounted or mounting component. This usually means you called forceUpdate() on an unmounted component. This is a no-op. Please check the code for the Analytics component.```
=> fix for error resizing main window when analytics is popped out

docs/setup/macos-setup.md
The existing link does not resolve, I've updated it with Event Store's current downloads page.
Additionally it seems the docker image would be preferable as Event Store v4 is not currently available for macOS.
=> Update Event Store link for macOS setup

src/client/src/ui/spotTile/spotTileOperations.ts
Fixes #620 
Because the redux state was mutated in the reducer, the UI didn't update properly creating a minor lag sometimes. Now the reducer returns a new state.
=> #620 "Executing" message on the spot tile has some delay sometimes

src/client/src/services/pricingService.ts
Fixes #610
To avoid duplicating the observable for the same pair we create a subject so it can multicast and is also cached.
We can see the difference of number of duplicate frames in the websockets. Before we have plenty of duplicate frames for the prices, after the change, there are no duplicates.
Before:
After:
=> #610 Client subscribes twice to every currency pair

docs/deployment/rtc-deployment-cli.md, docs/deployment/rtc-deployment.md
- Fixed link to build-id.md page which was pointing to the non-existent build_id.md
- Removed (Optional) in "authenticate with gcloud" as authentication with gcloud is needed to be able to use the cluster and list the environments.
=> [Documentation] Fixed documentation link and details.

deploy/config, deploy/docker/build/web/npminstall/Dockerfile, deploy/docker/prepare, src/client/.dockerignore
- Upgraded node version to LTS 8.11.3.
- Separated the npm install layer to quickly build the client.
- Added docker ignore file.
**Note:** To use node LTS alpine it will be needed to install python in the container. Alpine has been avoided in this task.
=> [ARTP-169] - Up Node version to LTS

src/client/src/rt-theme/globals.ts
Bug: Scrollbar styling is missing resulting in default styled scrollbars.
Cause: Scrollbar styling was removed.
Fix: Add in styling through `injectGlobal` provided by Emotion.js. While this works, it would be nice to come up with a more dynamic solution.
=> [ARTP-215] Style scrollbars

src/client/src/ui/spotTile/components/notifications/NotificationContainer.tsx
Bug: After a notification, a user would not be able to click a price button for about a second.
Cause: Due to animation, a notification component while unmounting is present until it is fully unmounted. This makes the tile look like it is ready to be clicked while the notification is actually still up, just not visible.
Fix: Added `pointer-events: none` on the leave property of the animation. This puts the CSS property on the notification component when unmounting, allowing the user to click-through the fading notification.
=> [ARTP-209] Unresponsive tile after notification

src/client/package-lock.json, src/client/src/ui/blotter/components/Blotter.tsx
Bug: In a tear off, clicking on a blotter header filter will cause the popup to become stuck
Cause: Removed reference to ag-grid's owner document
Fix: Letting ag-grid hold a reference to the document
=> [ARTP-192] Blotter filter popups stuck when torn off

src/client/package-lock.json, src/client/src/ui/spotTile/components/PriceMovement.tsx, src/client/src/ui/spotTile/components/SpotTile.stories.tsx, src/client/src/ui/spotTile/components/notifications/NotificationContainer.tsx
Bug: Price button, price movement, and notional input broken in storybook.
Cause: In the migration to the new theming method, spot tile styling was not selected for.
Fix: Create a `Story` component with a `ThemeProvider` that selects for spot tile styles from the parent theme.
=> [ARTP 216] Fix for broken storybook views

src/client/src/rt-components/tear-off/Portal.tsx
Bug: When popping out the blotter, the blotter grid's header titles were visible before the styles were fully loaded.
Cause: Styles not fully loaded before content is visible.
Fix: Delay adding the content to the pop out DOM to allow styles to load.
=> [ARTP-218] Blotter pop out flashing content before styles loaded

src/client/package.json
Removes a specified environment from default build script.
Compare with `build:local` or `build:cloud` which specify an environment — and therefore a particular host for the backend.
=> Fix default client build script

src/client/package-lock.json, src/client/public/config/openfin/demo.app.json, src/client/public/config/openfin/dev.app.json, src/client/public/config/openfin/local.app.json, src/client/src/NotificationRoute.tsx, src/client/src/shell/notification/styled.tsx, src/client/src/shell/openFin/openFin.ts
In this patch:
- Removed layouts service to fix the windows becoming tabs issue.
- Notification styling now fills container.
- Updated OpenFin version to 9.61.34.22.
- Changed main window close handler to call `fin.desktop.Application.getCurrent().close()` which will close the main process and all child processes. This fixes the issue where certain child processes would be leftover after closing windows.
=> [ARTP-242] OpenFin fixes

src/client/src/shell/layouts/AppLayout.tsx
The previous approach to styling scroll bars under `MainRoute` did not work. This is a simple fix, but the PR is open to suggestions.
It's important to keep in mind this style is not applicable to the `StyleguideRoute`. Therefore, we must find an appropriate place to add a global style — and do so without introducing side-effects outside of a component lifecycle. 
Specifically, we should not inject a global style on `import`, or even on component mount. We must mount and unmount globals when our component mounts and unmounts.
=> ARTP-277 Add scroll bar style via react-helmet style tag

src/client/src/index.tsx, src/client/src/routes/MainRoute.tsx, src/client/src/routes/OrderTicketRoute/OrderTicketRoute.tsx, src/client/src/routes/OrderTicketRoute/index.ts, src/client/src/routes/OrderTicketRoute/index.tsx, src/client/src/routes/index.ts, src/client/src/rt-components/Environment/EnvironmentContext.tsx, src/client/src/rt-components/Environment/index.tsx, src/client/src/rt-components/index.ts, src/client/src/rt-components/route-wrapper/RouteWrapper.tsx, src/client/src/rt-components/tear-off/Portal.tsx, src/client/src/shell/openFin/index.ts, src/client/src/shell/openFin/openFin.ts, src/client/src/ui/spotTile/components/TileControls.tsx
This is a proposal to generalize the environment we share across applications within Reactive Trader. As Reactive Trader grows to include application environments beyond OpenFin or the browser we'll want consistency in how we think and communicate with that underlying environment.
This change consolidates the definition of the environment and window provider. It alters the interface to be invariant to changes in platform specifics.
The underlying gist of a window provider is that we adopt browser conventions where ever possible. This happily minimizes the room for debate and possible surface area as we grow the feature set for each applications requirements.
=> Generalize environment handling

src/client/src/shell/openFin/openFin.ts
ChartIQ icon link was broken. This PR updates the url for the icon.
=> Update chartiq icon

src/client/package.json, src/client/src/rt-theme/ExtendedThemeProvider.tsx
- Updates `typescript` to `3.1.1`
- Fixes error from `ExtendedThemeProvider` by adding a `ThemeFunctor` type
=> Update dependency: typescript@3.1.1

src/client/src/shell/GlobalScrollbarStyle.tsx
**Issue :**
- The scrollbar was too thick and did not match the zeplin design
**Solution :**
- Make some changes in the GlobalScrollbarStyle.tsx file so as to make it look like the zeplin design
=> [ARTP-296] Reduce scrollbar width to match zeplin design

src/client/public/config/openfin/demo.json, src/client/public/config/openfin/dev.json, src/client/public/config/openfin/local.json, src/client/public/config/openfin/orderticket.json
**Issue**
RT closing when other connected external windows exited (e.g Excel, ChartIQ, Limit Checker)
**Solution**
Remove the nonPersistant:true property from the OpenFin config
=> fix: removed nonPersistent from openfin configs

src/client/Dockerfile, src/client/Dockerfile.dev, src/client/src/ui/analytics/components/analyticsBarChart/styled.tsx
Proposal to use `attrs` for the dynamic `transform` property on `FlexDiv` for performance.
Currently, every single `FlexDiv` in `PriceContainer` (in PnL) will generate its own new CSS class everytime the value of `distance` is updated. That's why we end up getting that warning (screenshot above).
If you hover the css class only that particular `FlexDiv` is highlighted in blue (on `develop`). So most likely each css class of each of these `FlexDiv` is only used for a few seconds.
With this update if you hover the css class you will see that all the `PriceContainer` are now highlighted in blue because they can now all use the same css class and styled-component doesn't need to generate a new unique css class every few seconds for every `PriceContainer`.
=> Proposal to prevent the FlexDiv styled-component to generate over 200 classes

src/client/package-lock.json, src/client/src/ui/spotTile/components/styled.tsx
=> SpotTileWrapper now supports 3 lines of content.

src/client/src/ui/spotTile/components/PriceButton.tsx, src/client/src/ui/spotTile/components/SpotTile.tsx, src/client/src/ui/spotTile/components/Tile.tsx, src/client/src/ui/spotTile/components/analyticsTile/AnalyticsTile.tsx, src/client/src/ui/spotTile/components/notional/NotionalInput.tsx, src/client/src/ui/spotTile/components/notional/utils.ts, src/client/src/ui/spotTile/components/stories/AnalyticsTitle.stories.tsx, src/client/src/ui/spotTile/components/stories/NotionalInput.stories.tsx, src/client/src/ui/spotTile/components/stories/SpotTile.stories.tsx, src/client/src/ui/spotTile/components/types.ts
:warning: We still need to validate a few things.
We now show commas in field when inputing number. Resets to DEFAULT_NOTIONAL_VALUE when input value exceeds MAX_NOTIONAL_VALUE.
When finished:
When inputting (Before):
When inputting (After):
When the value exceeds `MAX_NOTIONAL_VALUE`, it is set back to `DEFAULT_NOTIONAL_VALUE` and a red line appear to indicate that the entry was invalid. It disappears after 2 seconds.
We need to validate these points: 
⚠️ I did not leave the entered value in the field when exceeding `MAX_NOTIONAL_VALUE` because you don't want the end user to Buy or Sell with an invalid value entered.
=> Handling commas and exceeding values in `NotionalInput`

src/client/__tests__/helpers/index.tsx, src/client/src/ui/spotTile/components/Tile/Tile.test.tsx, src/client/src/ui/spotTile/components/Tile/Tile.tsx, src/client/src/ui/spotTile/components/Tile/TileBusinessLogic.test.ts, src/client/src/ui/spotTile/components/Tile/TileBusinessLogic.ts, src/client/src/ui/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap, src/client/src/ui/spotTile/components/Tile/index.tsx, src/client/src/ui/spotTile/components/TileSwitch.tsx, src/client/src/ui/spotTile/components/notional/NotionalInput.test.tsx, src/client/src/ui/spotTile/components/notional/NotionalInput.tsx, src/client/src/ui/spotTile/components/notional/__snapshots__/NotionalInput.test.tsx.snap
=> ARTP-573 / Tests and snapshots for Tile components

src/client/src/rt-components/platform/platform.ts
There is a bug where every platform is evaluated as Finsemble
```
let FSBL: any
const isFinsemble = FSBL in window
```
which is effectively 
```
undefined in window // === true
```
This PR fixes that to restore the platforms
=> Fix FSBL platform check

src/client/src/ui/workspace/workspaceHeader/styled.tsx
Remove cursor pointer from live rates label
=> ARTP-636 - The Live Rates label, top left, should not be a clickable area

src/client/src/ui/analytics/components/analyticsBarChart/PNLBar.tsx, src/client/src/ui/analytics/components/analyticsBarChart/styled.tsx
- Removed Origin from PNLBar
- Refactored to functional component
**Before**
**After**
=> ARTP-637 - Remove the central zero on the PnL tab range indicators

src/client/src/rt-components/open-fin/OpenFinChrome.tsx, src/client/src/rt-components/platform/externalWindowDefault.ts, src/client/src/shell/routes/AnalyticsRoute.tsx
Updated css and config to enable scrollbar on pnl popout
**Before**
<a href="https://user-images.githubusercontent.com/50445182/58166371-95f50900-7c81-11e9-9d1b-35a3b28d9acf.PNG"><img src="https://user-images.githubusercontent.com/50445182/58166371-95f50900-7c81-11e9-9d1b-35a3b28d9acf.PNG" width="300" /></a>
**After**
<a href="https://user-images.githubusercontent.com/50445182/58166378-9b525380-7c81-11e9-9ddf-cf83803cac4b.PNG"><img src="https://user-images.githubusercontent.com/50445182/58166378-9b525380-7c81-11e9-9ddf-cf83803cac4b.PNG" width="300" /></a>
=> ARTP-639 - The P & L tile loses its scroll bar when popped out

src/client/src/rt-components/open-fin/OpenFinChrome.tsx
Disable user selection for tear out windows (OpenfinChrome)
=> ARTP-631 - When any tile is popped out, you can select and copy text (you should not be able to do so)

src/client/src/rt-components/index.ts, src/client/src/rt-components/open-fin/OpenFinChrome.tsx, src/client/src/rt-components/open-fin/index.ts, src/client/src/rt-components/platform/externalWindowDefault.ts, src/client/src/shell/routes/AnalyticsRoute.tsx, src/client/src/shell/routes/BlotterRoute.tsx, src/client/src/ui/workspace/selectors.ts
Updated `OpenfinChrome` css to align close icon and padding
=> ARTP-633 - On a popped tile, the x is too high, and not quite placed correctly

src/client/src/ui/spotTile/epics/combineSpotTileEpics.ts, src/client/src/ui/spotTile/epics/rfqEpics.test.ts, src/client/src/ui/spotTile/epics/rfqEpics.ts
- Fix rfq spread
- Remove random values from `rfqService` to make deterministic 
- Added `rfqEpics` tests
- Renamed `rfqTileEpics` to `rfqEpics`
=> Fixed RFQ spread, add RFQ epic tests

src/client/src/ui/spotTile/components/SpotTile.tsx, src/client/src/ui/spotTile/components/Tile/Tile.tsx, src/client/src/ui/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap, src/client/src/ui/spotTile/components/TileControls.tsx, src/client/src/ui/spotTile/components/TileHeader.tsx, src/client/src/ui/spotTile/components/TileSwitch.tsx, src/client/src/ui/spotTile/components/stories/TileSwitch.stories.tsx, src/client/src/ui/spotTile/components/styled.tsx, src/client/src/ui/spotTile/components/types.ts
Moved chartIQ button to fix some overlapping issues
**Before**
**After**
=> ARTP-629 - The reject button on an RFQ overlaps slightly on the chartIQ button

src/client/src/rt-components/index.ts, src/client/src/rt-components/open-fin/OpenFinBrowserLink.tsx, src/client/src/rt-components/open-fin/index.ts, src/client/src/ui/status-bar/StatusBar.tsx, src/client/src/ui/status-bar/styled.tsx
- Added `OpenFinBrowserLink` component to open `<a>` in a new browser window from OpenFin
- Link the OpenFin logo to OpenFin's website
=> ARTP-635 - Clicking the OpenFin logo, bottom right, should go straight to the OpenFin website

src/client/src/routes/MainRoute/MainRoute.tsx, src/client/src/rt-components/index.ts, src/client/src/rt-components/platform/adapters/index.ts, src/client/src/rt-components/platform/adapters/openfin/openFin.ts, src/client/src/rt-components/platform/adapters/openfin/window.ts, src/client/src/rt-components/platform/index.ts, src/client/src/rt-components/tear-off/TearOff.tsx, src/client/src/shell/index.ts, src/client/src/shell/layouts/layoutActions.ts, src/client/src/shell/layouts/reducer.ts, src/client/src/shell/layouts/selectors.ts, src/client/src/shell/routes/ShellRoute.tsx, src/client/src/ui/blotter/epics/blotterServiceEpic.ts, src/client/src/ui/workspace/Workspace.tsx, src/client/src/ui/workspace/selectors.ts
This MR is to have the Workspace feature of Openfin Cloud working correctly. To have a successful restore of a workspace, the applicatino has to implement the restore behavior for the child windows. In order to do that I had to refactor the way the application handles the child windows (popIn/popOut). This is now done via dispatch of actions.
=> ARTP-642 Openfin Cloud - Restore workspace

src/client/src/shell/routes/styled.tsx
**Problem:** stuttery scrolling on mobile, lack of momentum
**Solution:** add `-webkit-overflow-scrolling: touch`
https://weareadaptive.atlassian.net/browse/ARTP-646
=> add momentum scrolling to OverflowScroll

src/client/src/shell/routes/styled.tsx
issue: tiles bleed to the right edge on mobile
solution: add in padding with breakpoint at max 480px (should prevent double padding in browser sizes)
=> fix mobile tile padding issue

src/client/src/rt-components/platform/adapters/openfin/openFin.ts, src/client/src/rt-components/platform/adapters/openfin/window.ts
Uses `getChildWindows()` to get the position of the last torn out child window. Newly created child windows are then positioned with an offset.
=> ARTP-628: Correctly Position Torn-out Child Windows

src/client/src/ui/blotter/epics/blotterHighlightEpic.ts
After feedback from @stewart-adaptive and @bhavesh-desai-scratch this is a refactor of #1084.
We are no longer firing off actions with empty arrays in them, instead we filter out all entries that do not have trades; that is, an old `tradeId` that comes from the Notifications pane and no longer matches the `tradeId`'s in the blotter. 
Doing this avoids code duplication and allows us to simplify the `removeHighlightTradeEpic` - it will never be called with a missing trade and therefore doesn't need any logic.
I'm curious to hear your feedback on this @stewart-adaptive and @bhavesh-desai-scratch. Let me know if you'd like to see any changes.
=> ARTP-667: Blotter Highlight Logic Revisit

src/client/src/console.d.ts, src/client/tslint.json
Due to a bug with typescript, in the most recent update when you tab to autocomplete console.log it will automatically import console. To prevent this, here is a file to override the behavior.
see: https://github.com/Microsoft/TypeScript/issues/30471 for more information
=> Prevent Auto Import of Console

src/client/src/rt-platforms/openFin/adapter/openFin.ts
+ Fix openfin-notifications:
*** The create function from openfin-notification package requires a category property that was not being provided:
=> ARTP-698: Fix openfin notifications bug

src/client/package-lock.json, src/client/package.json, src/client/src/rt-platforms/openFin/adapter/openFin.ts
***Things done:
+ Updated `openfin-notifcations` package from version `0.10.1` to `0.11.0`
+ Fixed the `Highlight Trade In Blotter` button bug for OpenFin notifications
***See the changes in `openfin-notifcations` docs:
[0.10.1 docs](https://cdn.openfin.co/docs/services/notifications/0.10.1/api/modules/index.html)
[0.11.0 docs](https://cdn.openfin.co/docs/services/notifications/0.11.0/api/modules/notifications.html)
=> Artp 700: Fix Highlight Trade In Blotter button bug

src/client/src/apps/MainRoute/widgets/workspace/selectors.ts, src/client/src/rt-platforms/externalWindowDefault.ts, src/client/src/rt-platforms/openFin/adapter/window.ts, src/client/src/rt-platforms/types.ts
***Things done:
+ Fix resizing of tear out windows in openfin that make them disappear.
- added `minHeight`, `minWidth`, `maxHeight`, `maxWidth` to each tear out components
*BUG*
*FIX*
=> ARTP-703: Fix window resizing of tear outs in OpenFin

src/client/src/apps/MainRoute/widgets/spotTile/components/analyticsTile/AnalyticsTile.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/analyticsTile/AnalyticsTilePriceControl.tsx
- Prices are still "streaming" (should be unavailable) even when notional is greater than or equal to 10 million in Analytics Tile view
- Prices show "Streaming Price Unavailable" when notional is greater than or equal to 10 million
=> ARTP-715: fix to hide "unavailable" streaming prices when notional >= 10m

src/client/src/apps/MainRoute/routes/SpotRoute.tsx
cast queryString as `TileViews` to get rid of type error
=> fix minor type error

src/client/src/rt-platforms/symphony/adapter/index.ts, src/server/Adaptive.ReactiveTrader.Server.Bot/package.json
This is a low impact fix to address issue where the Symphony share hookup is attempted before the Symphony window object is available.
Not 100% sure how this looks under the new platform refactorings...
=> Fix Symphony share callback attachment

src/client/src/apps/MainRoute/widgets/spotTile/components/analyticsTile/AnalyticsTileChart.tsx
Analytics graph in tile was wriggling around meaninglessly:
I've removed animation to stop this:
JIRA: https://weareadaptive.atlassian.net/browse/ARTP-771
=> ARTP-771: Remove line animation on analytics tile chart

src/client/src/apps/MainRoute/widgets/analytics/components/analyticsBarChart/PNLBar.tsx, src/client/src/apps/MainRoute/widgets/analytics/components/analyticsBarChart/styled.tsx
- changed hover transition to use scale transform instead of font-size, makes animation smoother
- added thousand separators to hover price
=> ARTP-773: Improve PnL hover price format and transition

src/client/src/rt-platforms/browser/window.ts
Fixes issue where refreshing a torn-off spot ticket could lead to the ticket becoming lost entirely (see https://weareadaptive.atlassian.net/browse/ARTP-699 for full detail)
The `onClose` callback is now only called if the tear-off window is flagged as closed 100ms after the unload event fired.
=> ARTP-699: Don't call close callback on tear-off window refresh

src/client/src/apps/MainRoute/widgets/spotTile/components/RfqTimer.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/SpotTile.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/TileSwitch.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/test-resources/spotTileProps.ts, src/client/src/apps/MainRoute/widgets/spotTile/epics/rfqEpics.ts, src/client/src/apps/MainRoute/widgets/spotTile/model/rfqRequest.ts, src/client/src/apps/MainRoute/widgets/spotTile/model/spotTileData.ts, src/client/src/apps/MainRoute/widgets/spotTile/spotTileReducer.ts
If an RFQ was received and the tile was the unmounted and re-mounted (e.g. by changing the base currency at the top), the RFQ timer would restart at initial timeout. (The RFQ would still expire at the correct time, which would be before the timer counted down fully)
This PR adds the RFQ received time to the data store so it can be used to calculate the time left correctly.
=> ARTP-772: Store RFQ received time and use it in timer

src/client/src/apps/MainRoute/widgets/spotTile/components/analyticsTile/AnalyticsTile.tsx
Pass `displayCurrencyChart` prop to `TileHeader` component to enable chart-iq feature for `AnalyticsTile` 
See [**ARTP-710**: OpenFin installer - ChartIQ doesn't open if tile graph activated](https://weareadaptive.atlassian.net/browse/ARTP-710?atlOrigin=eyJpIjoiNTg1ZTk2M2QwZTMzNDZiMmE1N2U5MGViNmQxNWViZWUiLCJwIjoiaiJ9)
=> ARTP-710: OpenFin installer - ChartIQ doesn't open if tile graph activated

package-lock.json, package.json, src/client/package-lock.json, src/client/package.json, src/node-server/nlp/package-lock.json, src/node-server/nlp/package.json
I broke the start up command in #1196, this fixes it by adding cross-env back to the client project and pinning the verson of babel-eslint (which CRA checks on startup)
Similar fixes for the server projects
=> Fix dev dependencies after lerna PR

src/client/src/apps/MainRoute/widgets/spotTile/epics/rfqEpics.ts
if timer is not canceled when a RFQ_CANCEL action is dispatched then the RFQ_EXPIRE action will eventually get dispatched. This will result in a `null` price for the spot tile, leading to a `TypeError: Cannot read property 'bid' of null` that crashes the application
=> cancel RFQ timer when RFQ_CANCEL action is dispatched

.circleci/config.yml
This PR removes one of the step introduced by https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/1201, and which causes the deploy build to fail
=> remove nlp deployment step

src/client/.eslintrc.json
enable eslint to warn on missing hooks dependencies
=> enable eslint to warn on missing hooks dependencies

package.json, src/client/src/rt-util/asyncUtils.ts, src/client/src/rt-util/hooks/useMultiTimeoutPromises.ts, src/client/tsconfig.strictNullChecks.json
We want to switch on strict null checks in typescript, but doing so raises 250 type errors, so we want to do this over time, not in a single PR.
I've added a `tsconfig.strictNullChecks.json` which has `strictNullChecks: true` and `include`s only those dirs which pass strictNullChecks.
The npm script `client-strict-null-checks` runs typechecking using this config. This script is run in git pre-commit hook
Over time we can create PRs which remove strictNullCheck errors from more dirs. Those PRs should add the 'fixed' dirs to `tsconfig.strictNullChecks.json` to ensure we don't regress
=> ARTP-599 Typecheck with strict null checks on pre-commit

src/client/src/apps/MainRoute/widgets/analytics/components/Analytics.tsx, src/client/src/apps/MainRoute/widgets/analytics/components/analyticsLineChart/AnalyticsLineChart.tsx, src/client/src/apps/MainRoute/widgets/blotter/components/Blotter.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/TileHeader.tsx, src/client/src/rt-components/tear-off/ExternalWindow.tsx, src/client/src/rt-components/tear-off/TearOff.tsx, src/client/src/rt-util/hooks/useMultiTimeout.ts
[Enabling `eslint` to warn missing deps caused some components to throw warnings during compile time.](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/1212)
** I purposely put `// eslint-disable-next-line react-hooks/exhaustive-deps` on some `useEffect` hooks since I assumed they are being used as a `componentDidMount()` (empty deps array).
=> Address react-hooks/exhaustive-deps warnings

src/client/src/rt-components/adaptive-loader/AdaptiveLoader.tsx, src/client/src/rt-components/icons/ExpandIcon.tsx, src/client/src/rt-components/loadable/Loadable.tsx, src/client/src/rt-components/modal/Modal.tsx, src/client/src/rt-components/popup/Popup.tsx, src/client/src/rt-components/resizer/Resizer.tsx, src/client/src/rt-components/tear-off/TearOff.tsx
Refactored the following files from a class component to functional component with hooks:
- `Loadable.tsx`
- `Modal.tsx`
- `Popup.tsx`
- `Resizer.tsx`
Refactored `AdaptiveLoader.tsx` to use `React.memo()` instead of a `PureComponent` class
Minor changes in `TearOff.tsx` and `ExpandIcon.tsx`
=> Refactor UI components in rt-components

src/client/src/rt-components/modal/Modal.tsx
Removed unnecessary `onDismiss` function since it isn't being used to begin with.
For more context, `onDismiss` is being passed as a prop to the `<Modal />` component, however not one of the components that uses `<Modal />` passes down an `onDismiss` function.
=> Remove unnecessary onDismiss function

src/client/public/config/openfin/launcher-local.json, src/client/public/config/openfin/local-app-directory.json, src/client/public/config/openfin/local-blotter.json, src/client/public/config/openfin/local-fdc3.json, src/client/src/apps/SimpleLauncher/Launcher.tsx, src/client/src/apps/SpotlightRoute/Spotlight.tsx, src/client/src/apps/SpotlightRoute/fdc3/browserFdc3.ts, src/client/src/apps/SpotlightRoute/fdc3/context.ts, src/client/src/apps/SpotlightRoute/fdc3/fdc3.ts, src/client/src/apps/SpotlightRoute/fdc3/openfinFdc3.ts, src/client/src/apps/SpotlightRoute/index.tsx
Spotlight now shows results from the fdc3 app directory, along with existing results
(we might not want to keep that long term, but it does get us started with fdc3)
This PR lets us open the blotter using the fdc3 api.
The app directory is hosted by the launcher, using the following configuration:
```
// launcher.local.json
{
"name": "fdc3",
"manifestUrl": "http://localhost:3000/config/openfin/local-fdc3.json"
},
```
```
// local-fdc3.json
"serviceConfiguration": {
"applicationDirectory": "http://localhost:3000/config/openfin/local-app-directory.json"
}
```
=> Spotlight - basic fdc3 integration

src/client/src/apps/MainRoute/widgets/spotTile/components/TileSwitch.tsx, src/client/src/apps/MainRoute/widgets/spotTile/epics/rfqEpics.ts
[Jira ticket](https://weareadaptive.atlassian.net/browse/ARTP-808)
**Changed:**
- Accounted for `rfqRequote` action in `rfqRequestEpic`
- Added `rfqReject` action in `cancel$` observable
- Swapped location of `Cancel RFQ` and `Requote` tile booking pills.
_Before Fix:_
_After Fix:_
=> Bugfix/artp 808: RFQ: cancel not working on Requote

src/client/src/apps/SimpleLauncher/Launcher.tsx
**Before**
**After**
Fixes ARTP-816
=> fix application name display in launcher

src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/TileBusinessLogic.ts, src/client/src/apps/MainRoute/widgets/spotTile/epics/rfqEpics.test.ts, src/client/src/apps/MainRoute/widgets/spotTile/epics/rfqEpics.ts
[Jira ticket](https://weareadaptive.atlassian.net/browse/ARTP-802)
Two functions existed in the `TileBusinessLogic.ts` file, one `getDefaultNotionalValue` that **_did not_** account for `NZDUSD`'s initial value and another one `getDefaultInitialNotionalValue ` that did account for `NZDUSD`'s initial value (10m).
I replaced `getDefaultNotionalValue` with `getDefaultInitialNotionalValue` to the `rfqReceivedEpic` so that when timer runs out, it can `setNotional` to the correct default values - accounting for `NZDUSD` currency pair.
=> Bugfix/artp 802: reset NZDUSD notional to 10m instead of 1m

.circleci/config.yml, src/.env, src/client/Dockerfile, src/client/src/apps/MainRoute/widgets/footer-version/FooterVersion.tsx, src/client/src/apps/MainRoute/widgets/footer-version/index.ts, src/client/src/apps/MainRoute/widgets/status-connection/StatusButton.tsx, src/client/src/index.tsx, src/docker-compose.deploy.yml, src/docker-compose.e2e.yml, src/docker-compose.yml
Reworking of the build process to move towards _continous delivery_.
- All merges to master will create a new _semver_ minor  version (1.1.0, 1.2.0, 1.3.0...). 
- Master will be deployed to `dev` environment
- We will use the [circleapi](https://circleci.com/docs/2.0/env-vars/#injecting-environment-variables-with-the-api) (at this initial stage) to run the deployment job passing the environment variables `BUILD_TARGET=demo` `BUILD_VERSION=1.23.0`. 
There is a  significant reworking of how we were doing the build/run/test stages within ciricleci. This moves all the setup config to be done purely via docker-compose. Now, to run the server integration tests:
```
docker-compose -f docker-compose.e2e.yml run integration
```
This simplifies differences between local reproduction and from within …
=> feat: build and deploy using semver versioning

.circleci/config.yml
Silly mistake.
When the tag is a github release tag it is in the format of `1.1.0-9-g7112def2`.
This is a prerelease in semver therefore `semver minor 1.1.0-9-g7112def2` -> `1.1.0`.
=> fix(ci): semver fails when tag is a release tag due to hash

.circleci/config.yml
Using `env-<environment>` tag to deploy to the specified environment. 
The idea is that the semver versioned commit, is then tagged with the environment to deploy to.
```
git tag -a env-demo -m "Deployed `date`" 1.888.0
git push adaptive env-demo
```
This will trigger the `deploy_version_from_env_tag` build. 
The commit will then have the version & the environment listed:
=> feat(ci): deploying to an environment using env-* tags

.circleci/config.yml
Before there was an issue where if a commit had two tags it would get only the last tag not necessarily the highest. 
This is also a fix for when a `release/` branch is merged into master, as semver will give the highest valid tag version.
=> fix(ci): get highest semver version from current head

.circleci/config.yml
Yet another bug with the ci process.
=> fix(ci): exporting deploy variables to next stage

src/client/src/apps/MainRoute/widgets/spotTile/SpotTileContainer.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/SpotTile.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/Tile.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/TileBusinessLogic.ts, src/client/src/apps/MainRoute/widgets/spotTile/components/TileSwitch.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/analyticsTile/AnalyticsTile.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/test-resources/spotTileProps.ts, src/client/src/apps/MainRoute/widgets/spotTile/components/types.ts, src/client/src/apps/MainRoute/widgets/spotTile/epics/closePositionEpic.ts, src/client/src/apps/MainRoute/widgets/spotTile/epics/rfqEpics.test.ts, src/client/src/apps/MainRoute/widgets/spotTile/epics/rfqEpics.ts, src/client/src/apps/MainRoute/widgets/spotTile/index.ts, src/client/src/apps/MainRoute/widgets/spotTile/model/index.ts, src/client/src/apps/MainRoute/widgets/spotTile/model/spotTileData.ts, src/client/src/apps/MainRoute/widgets/spotTile/selectors.test.ts, src/client/src/apps/MainRoute/widgets/spotTile/selectors.ts, src/client/src/apps/MainRoute/widgets/spotTile/spotTileDataReducer.ts, src/client/src/apps/MainRoute/widgets/workspace/selectors.ts
- fixed the regression related to the default value of the notional
- reworked they way how the default values of `SpotTileData` are propagated through the data hierarchy (this is now controlled by selectors, not views)
see more comments inside the PR
=> Fixed for notional display

src/e2e/src/tests/trade.spec.ts
- we had a bug in notional after recent merge (all notionals were 0 by default)
- while our notional was broken, there was a fix to the test which now manually switched notional for NZDUSD curreny pair to 10,000,000. This was done to switch ticket to RFQ mode and it was working ok
- after we fixed the default value of notional to be 10,000,000 for NZDUSD, this test was still clearing text of notional and populating it with 10,000,000.
- unfortunately due to the structure of the animations in that piece code, we are temporarely having more than one element with the same selector on the screen when switching from and to RFQ quickly
- our e2e test (which is based on certain data-qa selectors) was not identifying elements to click correctly and was failing. 
Solution - just remove explicit …
=> fix: fixing e2e test (ARTP-832)

src/client/src/index.tsx, src/services/nginx/default.conf
The client is not always retrieving the most recent version. This change fixes this by:
- Configuring the caching policy in nginx
- Disabling the service worker
=> fix: updates caching policy in nginx, disables service worker (ARTP-854)

.circleci/config.yml
This installs the `gettext` package when the build is using the `google/cloud-sdk` image.
=> fix: install debian packages needed for deployment build (ARTP-859)

.circleci/config.yml
This PR introduces a few things to fix our CI process:
1) when building branches in PRs, we need to rebase with master first. This is to make sure that we do not allow false-positive build cases (this is when PR looks green, but after merging with master, it fails because master had changes that were not taken into account when PR was built)
2) when a PR gets merged into master, we need to rebuild all other opened PRs to make sure their status is correctly representing the latest code. This is solved by default in a lot of CI products but unfortunately in CircleCi we had to do this manually using a some API magic (call GitHub API, then CircleCI API). See details in the code 
PLEASE NOTE: for now it only works for PRs that have been opened for branches that are in the original repo (not …
=> fix: triggering build on PR branches on commit to master

src/client/src/rt-components/tear-off/ExternalWindow.tsx, src/client/src/rt-platforms/openFin/adapter/window.ts
Fixing an issue where old tear-off were closing when new ones were created. This was due to react hooks re-executing themselves in places where we don't expect them to do so
=> fix: fixing tear-off appearance (ARTP-825)

src/client/src/apps/MainRoute/data/referenceData/referenceDataService.ts, src/client/src/rt-system/ServiceStubWithLoadBalancer.ts
This change fixes a bug in handling service disconnections whereby the client fails to re-subscribe to a service after a network disconnection. This is what causes the pricing service to show the "pricing unavailable" message as the prices are now stale.
=> fix: handles service disconnections

src/client/src/apps/MainRoute/widgets/spotTile/components/PriceControls/PriceControls.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/SpotTile.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/TileSwitch.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/NotificationContainer.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/stories/PriceControls.stories.tsx
This PR shows icons in the pricing buttons instead of the red warning tile
=> feat: show indicator when pricing unavailable (ARTP-840)

src/client/src/apps/MainRoute/widgets/workspace/Workspace.tsx, src/client/src/apps/MainRoute/widgets/workspace/workspaceHeader/WorkspaceHeader.tsx
Just a minor refactor:
- spot tile now defaults to analytics view
- thus order of icons in spot tile workspace has flipped
=> refactor: spotTile chart now displayed by default - ARTP-892

.circleci/config.yml
I have now enabled that branches need to be up to date with master before merging, so we don't need these extra custom checkout and build steps any more.
=> feat(build): remove steps that try to merge pull requests with master

src/client/src/apps/SimpleLauncher/spotlight/intents/showCurrencyPair.ts
Now the NLP search (currency paid), tile should open in graphic view by default
=> Fix(client): search and tile open in graphic view by default (ARTP-914)

src/client/src/apps/MainRoute/widgets/spotTile/spotTileDataReducer.ts
- Limit graph points to 250
- Use slice indicating start and end index to improve array copy
=> Fix - reduce memory usage for analytics mode

src/client/src/apps/MainRoute/widgets/workspace/Workspace.tsx, src/client/src/apps/MainRoute/widgets/workspace/workspaceHeader/WorkspaceHeader.tsx
Re-submission of lost code due to merging error.
- spot tile graph view is now shown by default.
=> feat(client): spot tile graph view displayed by default (ARTP-892)

src/services/nginx/default.conf
The openfin-config server requires the host(name) to decide which config to generate.
=> Forward host to openfingconfig [ARTP-877]

src/client/src/apps/MainRoute/widgets/spotTile/components/PriceMovement.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/RfqTimer.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap, src/client/src/apps/MainRoute/widgets/spotTile/components/analyticsTile/styled.tsx
- Tile analytics view layout  not broken at large widths
- Add padding to priveMovement in analytics tile
=> Fix/analytics view layout (ARTP-934 & ARTP-958)

src/client/src/apps/MainRoute/widgets/spotTile/components/stories/Initialise.stories.tsx, src/client/src/apps/MainRoute/widgets/workspace/Workspace.tsx
=> fix(client): add decorator knobs in spottile storybook

src/client/src/rt-actions/index.ts, src/client/src/rt-actions/setupActions.ts, src/client/src/rt-actions/workspaceActions.ts, src/client/src/rt-platforms/openFin/adapter/epics.ts, src/client/src/rt-platforms/openFin/adapter/index.ts, src/client/src/rt-platforms/openFin/adapter/openFin.ts, src/client/src/rt-platforms/openFin/adapter/window.ts, src/client/src/rt-platforms/openFin/adapter/workspaces.ts, src/client/src/rt-platforms/openFin/index.ts
* Ensures workspace handlers (eg `setRestoreHandler`)  are setup properly on boot
* Persists workspace object to local storage on relevant application events eg resize, move, minimise, etc
=> Restore OpenFin workspace on boot

src/client/src/apps/MainRoute/components/notification/TradeNotification.stories.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/NotificationContainer.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/notifications/TileNotification.tsx
* Trades that have an error during execution are now highlighted yellow instead of red e.g a trade taking longer that expected to execute
* Trades that fail remain red
* Trades that succeed remain green
=> Client - Add yellow accent to trade notification [ARTP-941]

src/client/src/apps/MainRoute/widgets/blotter/components/BlotterGrid.tsx
This PR is to allow the row to have the same transition of background colour when the theme changes
=> fix(client): keep blotter row transition consistent

src/client/src/rt-platforms/glue/window.ts
External spot tiles where showing as blank because of the way URLs were created, which appears to have been broken when the app started loading on a non-root path (it seems that / has started redirecting to /ALL/Analytics)
=> Fix opening a spot tile in glue

src/client/src/rt-components/icons/UndockIcon.tsx, src/client/src/rt-platforms/openFin/adapter/index.ts, src/client/src/rt-platforms/openFin/adapter/openFin.ts, src/client/src/rt-platforms/openFin/adapter/window.ts, src/client/src/rt-platforms/openFin/components/OpenFinChrome.tsx
This PR is to fix the behaviour where after the popped out window tile is reloaded and missing the undock button while it is docked.
=> fix(openfin): make sure undock icon is available when reloaded (ARTP-1016)

src/client/src/apps/SimpleLauncher/Launcher.tsx, src/client/src/apps/SimpleLauncher/windowUtils.ts
before: when reload with result 
after: when reload with result
=> fix(launcher): reset bound size before unload (ARTP-1028)

src/client/lib/downloadInstaller.js
- using filename that is too long causes mac installer generator to fail, use default and only specify file name on our side when writing file
- include mac installer for platform version
=> fix: update installer generation script and mac installers

src/client/src/rt-interop/intents/showMarket.ts
This PR fixes the problem of not being able to reopen the market view after it has been opened once from the launcher.
=> fix(launcher): fix unable to reopen market view (ARTP-1046)

src/client/src/apps/MainRoute/Router.tsx, src/client/src/apps/MainRoute/routes/AnalyticsRoute.tsx, src/client/src/apps/MainRoute/widgets/blotter/components/BlotterHeader.tsx, src/client/src/rt-components/route-wrapper/RouteWrapper.tsx, src/client/src/rt-platforms/openFin/components/OpenFinChrome.tsx
This PR fixes the mismatch of the design as in 
https://app.zeplin.io/project/5b4660dc3b1097135eadcc35/screen/5e4d4c0a351535a8738b90d1
=> fix(client): align headers with UX (ARTP-1056)

src/client/src/rt-interop/util/getProvider.ts
Loading this was causing issues on initializing when running in a non-openfin environment. This change prevents those errors.
=> fix(finsemble): conditionally load openfinFDC3 (ARTP-1013)

src/client/src/apps/MainRoute/Router.tsx, src/client/src/apps/MainRoute/routes/ShellRoute.tsx, src/client/src/apps/MainRoute/widgets/workspace/Workspace.tsx, src/client/src/apps/MainRoute/widgets/workspace/workspaceHeader/ToggleView.tsx, src/client/src/apps/MainRoute/widgets/workspace/workspaceHeader/WorkspaceHeader.tsx, src/client/src/rt-components/icons/ChartIcon.tsx, src/client/src/rt-interop/intents/showMarket.ts, src/client/src/rt-platforms/externalWindowDefault.ts, src/docker-compose.e2e.yml
Url keeps the same when currencies or tile view is changed. However, when we pop out spot tiles it starts from default values.
=> fix(tiles): return to clean url for tiles state (ARTP-1075)

src/client/src/rt-interop/intents/defaultWindowConfig.ts, src/client/src/rt-interop/intents/showBlotter.ts, src/client/src/rt-interop/intents/showCurrencyPair.ts, src/client/src/rt-interop/intents/showMarket.ts, src/client/src/rt-platforms/openFin/adapter/window.ts, src/client/src/rt-platforms/openFin/adapter/workspaces.ts, src/client/src/rt-platforms/platformWindow.ts, src/client/src/rt-platforms/types.ts
- Add an updateposition handler when creating windows on openfin
- Keep updated position for windows opened from launcher
- If it's the first time windows opens, it opens on center of screen
=> fix(laucher): remember position for opened windows (ARTP-1060)

src/client/public/manifest.json, src/client/public/rtc-sw.js, src/client/src/apps/MainRoute/MainRoute.tsx, src/client/src/index.tsx, src/client/src/serviceWorker.js
This PR:
- Adds a service worker with the minimum requirements for installability and registers it.
- Updates the manifest.json to include higher res icons to meet installability requirements.
**Important**:
- To get this to work in Chrome, you need to enable chrome://flags/#bypass-app-banner-engagement-checks
- Edge (Chromium) should work out of the box
RTC Running in `standalone` mode
Chrome default install prompt. We can offer our own install button/prompt/flow if we want.
`chrome://apps` showing Reactive Trader
=> Minimum Viable Progressive Web App

src/client/src/apps/MainRoute/routes/ShellRoute.tsx, src/client/src/rt-components/resizer/Resizer.tsx
Fill space with blotter when live rates are popped out
=> ARTP-1114: Fix blotter to fill space when live rates are popped out

src/client/src/apps/MainRoute/components/app-header/Header.tsx, src/client/src/apps/MainRoute/components/app-header/LoginControls/styled.ts, src/client/src/rt-theme/colors.ts
Added a `dividerColor` to core theme
Fix header dividers to spec
=> chore(theme): Add divider color, and fix header dividers

src/client/src/apps/MainRoute/components/app-header/theme-switcher/ThemeSwitcher.tsx
This PR removes `onMouseEnter` and `onMouseLeave` handlers when using a touch-enabled device. It replaces them with a`onTouchStart` listener which then mimics the switching behavior. This should improve the experience and removes the requirement for multiple taps.
=> Better Mobile Theme Switching Experience

src/client/src/rt-platforms/openFin/components/OpenFinChrome.tsx
=> Artp 1145/poppedout header not visible in light mode

src/client/src/rt-interop/intents/showMarket.ts, src/client/src/rt-platforms/openFin/components/OpenFinChrome.tsx
- remove double titles on torn off components
- remove background color on torn off components
- change default height of market view from launcher
=> Artp 1147/bugfixes

src/client/src/rt-components/resizer/Resizer.tsx
- blotter will fill remaining space entirely when live rates are popped out
- resizer is hidden when live rates are popped out
=> ARTP-1141/fix blotter to fill space entirely when live rates are popped out

src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/Tile.test.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap, src/client/src/rt-components/route-wrapper/RouteWrapper.tsx, src/client/src/rt-platforms/index.ts, src/client/src/rt-platforms/openFin/adapter/index.ts, src/client/src/rt-platforms/openFin/adapter/launcherUtils.ts, src/client/src/rt-platforms/openFin/adapter/window.ts, src/client/src/rt-platforms/openFin/index.ts
- Renames `isParentAppLauncher` to `isParentAppOpenfinLauncher` for clarity
- Creates `/launcherUtils` to contain `isParentAppOpenfinLauncher` since the exports of `/openfin` were causing the error
=> bug(finsemble): fixes bug preventing finsemble from loading (ARTP-1136)

src/client/src/rt-platforms/openFin/components/OpenFinChrome.tsx
**Changes:**
- Fix theme switcher and logo being blocked by an absolutely positioned `div`
Screengrab at smallest possible size:
=> fix(workspace): fix openfin theme toggle (ARTP-1172)

src/client/src/apps/MainRoute/widgets/blotter/blotterTradesFilter.ts, src/client/src/apps/SimpleLauncher/spotlight/components/getInlineSuggestionsComponent.tsx, src/client/src/apps/SimpleLauncher/spotlight/components/useBlotterTrades.ts, src/client/src/rt-types/tradeMapper.ts
**Changes:**
- Allow NLP for a base or quote currency and show relevant trades in blotter
=> fix(workspace): fix trades filtering for NLP (ARTP-1168)

src/client/src/apps/MainRoute/components/app-header/PWAInstallPrompt/PWAInstallModal.tsx, src/client/src/apps/MainRoute/components/app-header/PWAInstallPrompt/PWAInstallPrompt.tsx, src/client/src/apps/MainRoute/components/app-header/PWAInstallPrompt/PWALaunchButton.tsx, src/client/src/apps/MainRoute/components/app-header/PWAInstallPrompt/usePWABannerPrompt.tsx, src/client/src/rt-components/icons/index.ts, src/client/src/rt-system/environment.ts
**Changes:**
- Remove the iOS banner on a PWA instance
- Remove code for Android specific modal (as we now install via native Android)
Tested on iPad Mini and Android 10
=> fix(client): pwa display on ios (ARTP-1228)

src/services/kubernetes/analytics-deployment.yaml, src/services/kubernetes/blotter-deployment.yaml, src/services/kubernetes/bot-deployment.yaml, src/services/kubernetes/broker-deployment.yaml, src/services/kubernetes/client-deployment.yaml, src/services/kubernetes/eventstore-deployment.yaml, src/services/kubernetes/nlp-deployment.yaml, src/services/kubernetes/pricehistory-deployment.yaml, src/services/kubernetes/pricing-deployment.yaml, src/services/kubernetes/referencedataread-deployment.yaml, src/services/kubernetes/tradeexecution-deployment.yaml, src/services/kubernetes/web-deployment.yaml
Added requests specifications for each pod. 
I had some issues setting the limits while using Kubernetes locally. The CPU usages I faced are higher from the one in our deployments and the pods were slow and tend to restart without hitting the memory limit.
=> feat: added cpu and memory requests for each pod ARTP-1112

docs/deployment/tls-key-for-ingress.md, src/services/kubernetes/deploy_locally.sh, src/services/kubernetes/ingress.yaml, src/services/kubernetes/web-backend-config.yaml, src/services/kubernetes/web-service.yaml
Added configuration that will replace `nsgate` with multiple Kubernetes ingresses (one for each namespace).
Since we will have multiple ingresses, I created a pre-shared certificate for the TLS certificate.
=> ARTP-1109 Replace nsgate with ingress

.github/workflows/ci.yml
Disabling end-to-end tests in the build script, as they are failing intermittently due to timing issues. As we are embarking on a re-architecting of the client code, they will be impacted and should be brought in line and re-enabled when ready.
=> chore(build): disable e2e tests

src/client/src/apps/MainRoute/components/windowFrame/WindowFrame.tsx, src/client/src/rt-platforms/openfin-platform/adapter/window.ts
Torn off windows now look like this:
Chrome styles (buttons and and title font) will be addressed in a future ticket
=> Artp 1302 popped out tiles dont have tabs

src/client/src/apps/MainRoute/routes/styled.tsx
The simple fix here seems to be to use parent element height as opposed to viewport in OverflowScroll (vh -> %). Scrolling now works as expected and I don't think this change causes unexpected side-issues.
=> ARTP-1313 Tile scrolling behavior fix

src/client/src/apps/MainRoute/widgets/spotTile/components/PriceButton/styled.tsx, src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/__snapshots__/Tile.test.tsx.snap, src/e2e/src/tests/trade.spec.ts
The lines that I removed where overwriting the pre-existing hover behavior of the trade buttons which is the desired behavior (sell button turns red on hover and buy button turns blue on hover). I simply removed those lines and now the desired behavior is achieved according to the zeplin mocks.
=> fixed tradebutton colors

src/client/public/openfin/launcher.json, src/client/src/rt-interop/intents/showBlotter.ts, src/client/src/rt-interop/intents/showCurrencyPair.ts, src/client/src/rt-interop/intents/showMarket.ts
host url prefix is added by the openfin-platform window.ts we were adding it twice
headers were not correct due to missing openfin-sub-window-frame in launchers defaultWindowOptions
=> fix: paths for new subwindows opened from launcher (ARTP-1323)

src/client/src/apps/MainRoute/layouts/AppLayout.tsx, src/client/src/rt-components/route-wrapper/RouteWrapper.tsx, src/client/src/rt-platforms/openFin/adapter/launcherUtils.ts, src/client/src/rt-platforms/openfin-platform/components/OpenFinSubWindowFrame.tsx, src/client/src/rt-platforms/openfin-platform/components/OpenFinWindowFrame.tsx
Removed PlatformHeader from the RouteWrapper, its never rendered as the check for windowType === 'sub' && !isChildView never === true
Moved check of isParentAppOpenfinLauncher into OpenFinSubWindowFrame and deleted from OpenFinWindowFrame
The check is used to determine if headerControlHandlers should show a close or popin button on the subframe windows
subwindow from launcher = close button
subwindow from !launcher = popin button
isParentAppOpenfinLauncher was throwing an exception, replaced check of fin.Window.getCurrent().getParentApplication with window.fin.me.uuid
=> fix: removed open fin specific code from RouteWrapper and AppLayout

src/client/src/apps/MainRoute/widgets/spotTile/components/Tile/Tile.test.tsx
We keep seeing this issue where someone in north-america updates the snapshots of the Tile and then the tests fail on the CI because the dates don't match.
This was happening because the date that was being set on `Tile.test.tsx` had a UTC offset of zero (`2019-04-07T00:00:00Z`). However, when the date is being formatted, it's being formatted using the local time-zone of the client. What that means is that the further you are from UTC-0, the higher the likelihood that when the test runs it will produce a different date of the one that's in the snapshot.
The "fix" (for now) is to use the timezone of the user also when setting up the date of the test.
=> fix(Tile): fix issue with flaky snapshop-tests with dates

src/client/public/openfin/launcher.json, src/client/src/apps/SimpleLauncher/SimpleLauncher.tsx, src/client/src/rt-platforms/browser/browser.ts, src/client/src/rt-platforms/finsemble/finsemble.ts, src/client/src/rt-platforms/glue/glue.ts, src/client/src/rt-platforms/glue/glueCore.ts, src/client/src/rt-platforms/noopAdapter.ts, src/client/src/rt-platforms/openFin/adapter/openFin.ts, src/client/src/rt-platforms/openfin-platform/adapter/openFinPlatform.ts, src/client/src/rt-platforms/openfin-platform/adapter/window.ts, src/client/src/rt-platforms/platformWindow.ts, src/client/src/rt-platforms/pwa/pwa.ts, src/client/src/rt-platforms/symphony/adapter/index.ts
Added show to PlatformWindowApi implemented in openfin platform only
Dont auto show the launcher, call show on render
=> fix: launcher autoShow = false, explicitly show on render

src/client/src/apps/MainRoute/widgets/footer-version/FooterVersion.tsx
Updated version of the clickable URL PR. 
Clickable when version number exists:
Not clickable when version number does not exist in responses: 
Tests passing locally:
=> ARTP-1288-Make-version-URL-clickable-v2

src/client/public/openfin/app.json
The npm package is pinned to `0.11.1`. We will want to upgrade that as soon as it is made available. This PR updates the service declaration in the manifest. This gives us access to the latest UI while maintaining all functionality.
=> chore(client): use latest OF notification service UI

.github/workflows/deploy.yml
No data still on `dev` after second deploy. I saw no build errors, just this deprecation warning.
=> chore(build): update gcloud action

src/client/src/apps/SimpleLauncher/LaunchButton.tsx, src/client/src/apps/SimpleLauncher/styles.ts
-launcher icons will be highlighted as soon as the icon text comes up, no overlap.
=> Fix launcher icon hover (ARTP-1362)

src/client/public/openfin/launcher.json
For reasons I don't yet understand, we need to set the permissions on both the parent and child windows (perhaps the IPC call is delegated via the platform window - I will clarify this with OpenFin). By setting the permission on both windows, the Limit Checker can now be opened.
=> fix(launcher): set permissions to launch Limit Checker (ARTP-1363)

src/client/src/rt-platforms/browser/utils/sendNotification.ts, src/client/src/rt-platforms/finsemble/finsemble.ts, src/client/src/rt-platforms/finsemble/finsembleClient.js
We currently aren't getting notifications when the blotter, which controls notifications, is used within the Finsemble demo. Since the current logic was implemented, Finsemble has released a new notification client that gives much more control over notifications than the previous service. This is the RT part of the implementation to get notifications working in this new service.
The notifications are based on those in the web app. I used the same icon, and reused the same logic for generating the title and message.
=> fix: rework notifications within Finsemble platform (ARTP-1212)

src/client/src/apps/MainRoute/widgets/footer-version/FooterVersion.tsx
We should be using `REACT_APP_BUILD_VERSION` instead of `REACT_APP_VERSION`
=> fix(client): use correct env var for build version

src/new-client/src/App/Analytics/ProfitAndLoss/LineChart/LineChart.tsx
I noticed that there was silly bug with the calculations that happen with the updates of the ProfitAndLoss chart, where the points of the xAxis where not moving correctly. This PR addresses that issue.
=> fix(new-client): fix ProfitAndLoss chart

src/new-client/package.json, src/new-client/yarn.lock
As @iprado78 pointed out yesterday: it would be nice to have `prettier --write` running automatically before we commit.
=> chore(new-client): prettier write on pre-commit

.github/workflows/ci.yml, .github/workflows/deploy.yml, src/docker-compose.yml
This removes the eventstore initialisation from the CI build and instead uses the existing (but currently unused) Kubernetes job. This change will mean that the eventstore is seeded at deploy time, against the running instance in k8s, instead of committing a modified image to docker.
=> fix: use k8s job to populate the event store (ARTP-1183)

.github/workflows/deploy.yml
This cleans up any existing (completed/failed/running) jobs in the deployment namespace. Currently, deployments fail if there is already a job deployed to initialise data.
=> fix: clean up existing jobs during deployment (ARTP-1371)

src/client/src/rt-platforms/openfin/adapter/openfin.ts
This was left over from the removal of the legacy OpenFin adapter. A side effect of this is that the Limit Checker subscription is never established, as this expects the platform name to be "openfin".
=> Use correct platform name for OpenFin adapter

src/new-client/src/App/Footer/Footer.tsx, src/new-client/src/App/Footer/StatusButton/Service.tsx, src/new-client/src/App/Footer/StatusButton/StatusButton.tsx, src/new-client/src/App/Footer/StatusButton/index.ts, src/new-client/src/App/Footer/StatusButton/styled.tsx, src/new-client/src/services/status.ts
-connection status components can display multiple services' connection status now
-service health and application connection status are independent: service health only depends on how many nodes are loaded, while application connection depends on the status of socket
-when connection is lost, status bar will show disconnected and when connection is back, app will reconnect and connection bar will show 'connecting --- connected'
=> feat(new-client)/connection-status-component(705)

src/new-client/public/index.html, src/new-client/src/App/Footer/StatusBar/Icon.tsx, src/new-client/src/App/Footer/StatusBar/styled.tsx, src/new-client/src/App/Trades/TradesHeader/QuickFilter.tsx
We were using a stylesheet for Font-Awesome icons (referenced via class names).  I think mainly for ag-grid.  Since we don't have that dependency anymore, we can remove the stylesheet and import FA (or other) icons individually through the react-icons library, so we don't have to ship all the icons to the browser.
=> chore(new-client): remove dependency on external stylesheet for icons

src/docker-compose.yml, src/server/node/bot/src/connection/StompConfig.ts, src/server/node/bot/src/connection/WsConnection.ts
Adds `connectionTimeout` to the existing bot config
Also adds `depends_on` to bot (depending on the broker)
=> chore(server): add connection timeout to node bot

src/new-client/src/App/LiveRates/Tiles/ExecutionStatusAlertSwitch/ExecutionStatusAlertSwitch.tsx, src/new-client/src/App/LiveRates/Tiles/ExecutionStatusAlertSwitch/Response.tsx, src/new-client/src/App/LiveRates/Tiles/ExecutionStatusAlertSwitch/styled.tsx, src/new-client/src/services/executions.ts
EUR/JPY request is intentionally set a 5 seconds delay in backend, in order to demo timeout situation. Now new client can deal with execution time out situations as the previous client.
=> chore(new-client): deal with execution timeout situation

src/new-client/.env.development, src/new-client/src/App/Trades/Trades.tsx, src/new-client/src/App/Trades/TradesFooter.tsx, src/new-client/src/App/Trades/TradesGrid/SetFilter.tsx, src/new-client/src/App/Trades/TradesGrid/TableHeadCell.tsx, src/new-client/src/App/Trades/TradesGrid/TradesGrid.tsx, src/new-client/src/App/Trades/TradesGrid/index.tsx, src/new-client/src/App/Trades/TradesHeader/AppliedFilters.tsx, src/new-client/src/App/Trades/TradesHeader/ExcelButton.tsx, src/new-client/src/App/Trades/TradesHeader/QuickFilter.tsx, src/new-client/src/App/Trades/TradesState/colConfig.ts, src/new-client/src/App/Trades/TradesState/filterState.ts, src/new-client/src/App/Trades/TradesState/index.ts, src/new-client/src/App/Trades/TradesState/sortState.ts, src/new-client/src/App/Trades/TradesState/tableTrades.ts, src/new-client/src/utils/mapObject.ts, src/new-client/src/utils/usePopUpMenu.ts
This implements a column "set filter" for the trades table.  Core part of the PR is:
1. Stage logic for managing the filters (and aggregating with the quick filter)
2. A provisional UI for a drop-down menu (based on the design we use for currency filters on the Tiles header in mobile view)
ToDo:
1. [Convert appliedFilters$ and distinctValues$ to parametric streams](https://adaptive.kanbanize.com/ctrl_board/18/cards/731/details/) - 
2. [Filter SetTypeFilter options with a text input](https://adaptive.kanbanize.com/ctrl_board/18/cards/732/details/)
3. [Create a "Select All" switch](https://adaptive.kanbanize.com/ctrl_board/18/cards/733/details/)
4. [Create a NumberTypeFilter](https://adaptive.kanbanize.com/ctrl_board/18/cards/736/details/)
5. [Create a …
=> feat(new-client): implement column filter for trades grid (719)

.github/workflows/deploy.yml, .github/workflows/pull-origin-up.yml, src/services/eventstore/Dockerfile, src/services/kubernetes/per-deployment/eventstore-deployment.yaml, src/services/kubernetes/per-deployment/eventstore-volume-claim.yaml, src/services/kubernetes/per-deployment/initialise/initialise-job.yaml
This improves the resiliency of the EventStore deployment with the following changes:
1. Data is now stored in a mounted persistent volume, which is retained across service restarts.
2. We no longer write server stats to the EventStore database. The docs suggest that this is off by default, but that was not the case. Stats are by far the heaviest part of the data, so this hugely slims down the resources used.
3. The initialisation job will restart on failure (with default backoff behaviour, failing fully after 6 unsuccessful attempts).
Once this has been deployed, I will monitor the effect on dev and uat, and then we can reduce the resource requests for this deployment. Currently, the pod scheduler sets aside 1GiB of memory for each EventStore. Without stats being written to the DB, we …
=> Improve EventStore resiliency

src/client/src/apps/MainRoute/routes/SpotRoute.tsx, src/client/src/rt-platforms/finsemble/finsemble.ts
This fixes two regressions relating to the Finsemble build:
1. We no longer need to deduct the height of the window title from the content height.
2. Spot tile views (normal or with analytics) should be toggled by query-string parameter in addition to local storage.
Tile views
Normal: https://pr1800.lb.adaptivecluster.com/spot/EURUSD?tileView=Normal
Analytics: https://pr1800.lb.adaptivecluster.com/spot/EURUSD?tileView=Analytics
Related:
https://github.com/AdaptiveConsulting/ReactiveTraderCloud-Finsemble/pull/40
=> Compatibility with Finsemble build

src/client/src/apps/SimpleLauncher/spotlight/components/TradeExecutionOverlay.tsx
The date formatting should match the inline quote table.
=> fix: date formatting in launcher trade execution overlay

src/new-client/package.json, src/new-client/yarn.lock
Yesterday I [upgraded the dependencies of the "new-client"](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/1812) and I also [added a commit for leveraging one of the new utils of `@react-rxjs/utils`](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/1812/commits/76b098521d01c3b6cb2e6eb6f5e35c4c2ab3f8a7). After each change I made sure that the production build was working properly and I did check whether we were having improvements on the Lighthouse metrics or not, and everything was working fine.
However, a few hours later I got messages from @iprado78 and from Julie letting me know that the `yarn start` script was no longer working:
The error on the image doesn't make any sense, because optional chaining it's in stage-4, it's supported by the current LTS …
=> Fix: yarn start

src/new-client/package-lock.json, src/new-client/package.json, src/new-client/vite.config.ts
Currently when we run the Lighthouse performance test we can appreciate the following suggestion: "Preload key requests", and then the report shows a list with 6-7 assets that should have been pre-loaded with a `<link rel="preload />` tag.
Lighthouse is correct, those assets are being loaded immediately after the parser evaluates the "shell" bundle, so it makes sense to have them as "preload" links in the `index.html` file. I thought that Vite would be able to do that automatically if instead of declaring our lazy components like this:
```ts
const LiveRatesCore = lazy(() => import("./LiveRatesCore"))
```
we declared them like this:
```ts
const mod = import("./LiveRatesCore")
const LiveRatesCore = lazy(() => mod)
```
The reason being that with the first declaration the bundler can't know …
=> chore(new-client): preload key requests

src/new-client/src/App/LiveRates/Tile/Rfq/RfqTimer.tsx
I thought that I could get away with having just one update... It turns out that I was wrong :sweat_smile: Also, I initially wanted to make the component resilient to prop-changes, but we don't really have that need ATM, and even if we had it, we could just use the key property to make it work, so I got rid of that logic too.
=> fix(new-client): Fix RFQ Timer on FF (#800)

src/new-client/src/App/Analytics/Positions/Positions.test.tsx, src/new-client/src/App/LiveRates/MainHeader/MainHeader.test.tsx, src/new-client/src/App/LiveRates/MainHeader/MainHeader.tsx, src/new-client/src/App/LiveRates/Tile/Tile.test.tsx, src/new-client/src/services/currencyPairs/__mocks__/currencyPairs.ts, src/new-client/src/services/currencyPairs/currencyPairs.ts
As I was working on the tests for #1839 I noticed that the mocks of the currency-pairs service are a lot more complicated than what they should be. I also noticed that there were was a hook that had been lifted into the service, that belonged into the `LivesRates` component.. So, I decided to address this first, instead of making things even more convoluted. My intention is to have this merged first, and then rebase #1839
=> chore(new-client): currencyPairs improvements

src/server/dotNet/Adaptive.ReactiveTrader.Messaging/Adaptive.ReactiveTrader.Messaging.csproj
We occasionally see the following error that crashes at runtime:
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference.
```
We use multiple versions of this package across different assemblies, which seems to cause problems if the packages when the packages are built in different orders (I believe this is parallel and so non-deterministic). This PR pins all assemblies to the same package version.
=> Prevent occasional runtime errors in dotnet services

src/new-client/package-lock.json, src/new-client/package.json, src/new-client/vite.config.ts
I've realized that "npm start" doesn't report ts errors, it only reports eslint warnings/errors. With this change vite will start reporting ts errors on `npm run start`/`npm run dev`
=> chore(new-client): report ts errors from vite dev

src/new-client/src/App/Analytics/Positions/Positions.test.tsx, src/new-client/src/App/Analytics/Positions/Positions.tsx, src/new-client/src/App/Analytics/Positions/__snapshots__/Positions.test.tsx.snap, src/new-client/src/App/Analytics/Positions/data.ts
I noticed some odd behaviors with the current implementation: mostly issues when there are no trades and therefore no positions and then new trades of different currencies add bubbles into the chart. This PR addresses that, while also makes an improvement so that the movement of the bubbles don't trigger long ending updates on the DOM.
=> fix(new-client): improve buble-chart

.github/workflows/ci.yml, .github/workflows/pull-origin-up.yml, deploy/build.sh, deploy/deploy.sh, deploy/push.sh, deploy/test.sh, src/docker-compose.e2e.yml, src/docker-compose.test.yml
This adds our server integration tests back into the CI workflows.
* For pull requests, the integration tests are run in parallel with the deployment phase, so there should be no slowdown in bringing up a preview environment for testing.
* During the main CI build (i.e. after a merge) the integration tests will run _before_ the deployment. This is to ensure that we do not deploy a broken build to any of our permanent environments.
* During the PR build, we do not necessarily build the server image (since we only build Docker images where the source has changed), so in this event we pull the relevant image from Docker Hub and use that for integration tests. Arguably we could skip integration tests altogether in this case.
Hopefully this will give the right balance between correctness and …
=> Run integration tests during PR and main CI workflows

src/new-client/src/App/LiveRates/Tile/Notional/Notional.tsx, src/new-client/src/App/LiveRates/Tile/PriceButton/PriceButton.tsx, src/new-client/src/App/LiveRates/Tile/Rfq/Rfq.state.ts, src/new-client/src/App/LiveRates/Tile/Rfq/Rfq.test.tsx, src/new-client/src/App/LiveRates/Tile/Rfq/RfqButton.tsx, src/new-client/src/App/LiveRates/Tile/Rfq/RfqTimer.tsx, src/new-client/src/App/LiveRates/Tile/Rfq/index.ts, src/new-client/src/App/LiveRates/Tile/Tile.state.ts, src/new-client/src/App/LiveRates/Tile/Tile.tsx
I'm preparing a presentation on react-rxjs and I'm planing to sue the rfq state as an example... Because of that, I decided to make a few improvements to make the code more readable and easier to understand, I also decided to be a bit more explicit about the types of the `useRfqState`.
One thing that I did notice, though, is that despite the fact that the behavior hasn't changed at all I've had to readjust the tests of `Rfq.test.ts`. I really think that those tests are kinda testing the internals and that we should be testing the rfq workflow through in the `Tile.test.tsx`, so let's create a task for that in our backlog.
=> chore(new-client): improve RFQ state management

package-lock.json, package.json, src/client/package-lock.json, src/e2e/.eslintrc.json
I noticed there was a really nasty vulnerability message at the top of the github project.  Lerna was updated a while ago to remove this issue. I found this to be a seamless upgrade on other projects.
I also disabled the eslint rule for the e2e tests for functions to have an explicit `return`, which doesn't make sense for tests, and it was creating so much noise that other linting issues could be missed.
=> chore: upgrade lerna

src/new-client/src/App/LiveRates/Tile/Rfq/RfqTimer.tsx, src/new-client/src/App/LiveRates/Tile/Tile.styles.tsx, src/new-client/src/App/LiveRates/Tile/Tile.tsx
The notional input should be center-aligned in the normal tile view and left-aligned in the analytics tile view.
=> fix(new-client): center-align notional input in normal tile view

src/new-client/src/services/executions/executions.ts, src/new-client/src/services/trades/trades.ts, src/new-client/src/sw-notifications.ts
I thought that we were supposed to notify the user about all new trades that were taking place... @garyadaptive told me that the user is only supposed to be notified about the executions that they trigger from that particular browser, sorry about that! :sweat_smile: 
Anyways this should fix it! :slightly_smiling_face: j
I've added other fixes like: preventing an odd issue with some chrome versions and fixing the notifications for Safari.
=> fix(notifications): fixes for notifications

src/new-client/src/sw.js
Once registered, the service worker of the new client intercepts requests to /storybook and /styleguide and redirects to the Reactive Trader UI. This PR adds exceptions for those two path prefixes.
For comparison, visit: https://www.reactivetrader.com/storybook and https://pr1887.lb.adaptivecluster.com/storybook. In the former, it is not possible to open storybook once the service worker is registered (without force-reloading). The latter always works.
=> Exclude storybook and styleguide from service worker routing

src/new-client/src/App/Analytics/Analytics.tsx, src/new-client/src/App/Analytics/index.tsx, src/new-client/src/App/LiveRates/LiveRates.tsx, src/new-client/src/App/LiveRates/index.ts, src/new-client/src/App/Trades/Trades.tsx, src/new-client/src/App/Trades/index.tsx, src/new-client/src/index.tsx
If the SW got updated, then we have to be careful. We can't immediately skip the waiting phase, because if there are requests on the fly that could be a disaster. In an ideal world we should display a message to the user letting them know that a new version is available and whenever the user confirms that they want to update then we can skip the waiting phase and we reload the App. However, before we implement that feature what we can do is to skip the waiting phase after all the async chunks have been loaded. This is only an option because all our async chunks get always preloaded from the main chunk.
=> feat(new-client): improve service workers updates

src/client/src/rt-util/getEnvironment.ts
The environment matcher currently falls back to "UNKNOWN" for classic environments. Aside from breaking the title in platform windows, this prevents Launcher from opening Reactive Analytics, as the URL is derived from the current environment.
=> Environment matcher should detect "classic" URLs

src/new-client/package-lock.json, src/new-client/package.json, src/new-client/src/App/Trades/TradesGrid/TradesGrid.tsx
When clicking the blotter row, broadcast the currency pair symbol as FDC3 context (if an FDC3 Desktop Agent is running).
=> feat(new-client): broadcast symbol on blotter row click

src/new-client/src/OpenFin/index.tsx, src/new-client/src/Web/index.tsx, src/new-client/src/services/analytics/analytics-mock.ts, src/new-client/src/services/analytics/analytics.service-mock.ts, src/new-client/src/services/analytics/analytics.ts, src/new-client/src/services/connection.ts, src/new-client/src/services/currencyPairs/currencyPairs.service-mock.ts, src/new-client/src/services/executions/executions.service-mock.ts, src/new-client/src/services/executions/executions.ts, src/new-client/src/services/executions/index.ts, src/new-client/src/services/executions/types.ts, src/new-client/src/services/prices/prices.service-mock.ts, src/new-client/src/services/trades/trades.service-mock.ts, src/new-client/vite.config.ts
Habemus mocks!
How to use the mocks?
```bash
VITE_MOCKS=true npm start
```
One of the goals was that I wanted to make sure that the code of the mocks didn't end up being bundle into the production build. In order to accomplish that I've created (with the help of @voliva ) a vite plugin that  what it does is: whenever we are running with the `VITE_MOCKS` env variable, then when importing a file, if that file has a sibling that ends with `.service-mock`, then it would load that file instead of the original one... That's it.
Some parts of the mocks try to mimic a little bit the real UX, like when a trade is executed/rejecte it appears in the blotter, other parts (analytics) are completely disconnected from user actions... These things can be improved in the future. At least now we can work …
=> chore(new-client): mock services

.github/workflows/branch.yml, .github/workflows/commit.yml, .github/workflows/pull.yml, src/new-client/package.json, src/new-client/src/Finsemble/FinsembleApp.tsx, src/new-client/src/Finsemble/TileContent.tsx, src/new-client/src/Finsemble/index.tsx, src/new-client/src/index.tsx
Simplest entry point app for Finsemble, and script entries.
Tested out with `VITE_MOCKS=true`  running with https://github.com/AdaptiveConsulting/ReactiveTraderCloud-Finsemble configured to address `http://localhost:1917` as root.
Update: now tested against the deployed target: 
`		"componentRoot": "https://finsemble.env.reactivetrader.com/pull/1923",`
=> 1185 finsemble target, basic app with router to support rtc-finsemble

src/new-client/src/App/LiveRates/Tile/PriceButton/PriceButton.styles.tsx, src/new-client/src/App/LiveRates/Tile/PriceButton/PriceButton.tsx
Match the previous behaviour when quoting an RFQ
**Before:**
**After:**
=> fix: rfq pricing colours (BUG-1189)

src/new-client/vite.config.ts
couple of small fixes for Windows dev env
- @ -> src alias in vite config updated to find/replacement form fixes import failures and now works across the o/s platforms
- path mod in mocks resolution (always POSIX paths)
=> fix: vite config for Windows (BUG-1193)

src/new-client/src/App/LiveRates/Tile/ExecutionResponse/Pending.tsx, src/new-client/src/App/LiveRates/Tile/ExecutionResponse/Response.styles.tsx, src/new-client/src/services/trades/index.ts
Position `ExecutionMessage` & `Pending` absolutely to fix trade confirmation UI on safari (mobile and desktop
**Before**
**After**
=> fix(client): Mobile > Trade confirmation cuts off

src/new-client/src/App/LiveRates/Tiles.tsx, src/new-client/vite.config.ts
Adds vite plugin to replace imported files with platform specific files if they exist.
`import { openWindow } from '@utils/window/openWindow'` will import from `@utils/window/openWindow.openfin.ts` when building for the OpenFin target.
Note - The behavior between dev and build in the `resolveId` plugin function is different. This PR gets our solution working, but more work towards  stable'er solution is needed.
=> fix(new-client): Platform bundle rewrite

src/new-client/src/Web/MainRoute.tsx, src/new-client/src/Web/cacheUpdateModal.tsx, src/new-client/src/Web/index.tsx, src/new-client/src/Web/serviceWorkerRegistration.ts, src/new-client/src/components/Modal/Modal.tsx, src/new-client/vite.config.ts
Show a modal to the user when service worker has pre-cached new updates. The user can then reload the page so they're not looking at an old version.
=> feat(new-client): Show modal when service worker has pre-cached

src/new-client/src/App/LiveRates/Tile/Notional/Notional.tsx
Notional negative values handled, we take the absolute value. 
The notional input already takes care of all characters that are not numeric but if we Ctrl+C Ctrl+V a negative value the latter is accepted when it shouldn't.
=> fix(new-client): Notional negative values handled

src/new-client/src/App/Trades/TradesState/tableTrades.ts
Added defensive code around `newTradeId$` to fix white screen of death when reconnecting to Hydra after a service restart
=> fix(new-client): Reconnection loop whit screen of death

src/new-client/src/App/Footer/ContactUsButton/ContactUs.tsx, src/new-client/src/Launcher/applicationConfigurations.ts, src/new-client/src/Launcher/utils/url.ts, src/new-client/src/constants.ts, src/new-client/src/notifications.openfin.ts, src/new-client/src/services/currentUser.ts, src/new-client/src/utils/url.ts
Replaces `BASE_URL` with `location.origin` throughout the app so we construct urls based on the current origin (allows us to have multiple domains for the same build - web.prod.|www.|reactivetrader.com)
=> fix: replace BASE_URL with location.origin 

src/new-client/src/components/DraggableTearOut/DraggableTearOut.tsx, src/new-client/src/components/DraggableTearOut/canDrag.openfin.ts, src/new-client/src/components/DraggableTearOut/canDrag.ts, src/new-client/src/components/DraggableTearOut/supportsDragToTearOut.openfin.ts, src/new-client/src/components/DraggableTearOut/supportsDragToTearOut.ts
While I was working with the virtualized table, I disabled the tearout to test something but saw that I could still drag, since the draggable components are just an extension of the already implemented tearout, I don't know if its an expected behaviour to be able to drag a component but not tear it out
Besides, there's also the issue that if we drag and a new window appears, we wouldn't be able to revert it unless we close it, since the tearIn would also be disabled.
I just added to the canDrag constant the need for supportsTearOut to be enabled, I don't know which would be the preferred behaviour for openfin so I left that as it is.
**Changed branch name and fixed previous requested changes**
=> Can tear and drag

src/new-client/src/App/Trades/TradesState/tableTrades.ts
*Note - this is my first contributions - please let me know if anything is not following the conventions!*
*Also note - raised MR from main repo b/c PRs from a private fork don't work with the builds at the moment*
- Convert string to number for tradeId comparisons
- Fixes === and !== operations
- For the tradeId column, the `numberFilterTrueOfTrade` is being called on filter change, and the value in the tradeId column is coming as a string and is typed as string|number.  Less than/greater than operator were evaluating the comparison between the number inputted and string value correctly but === and !== were always returning false
- The fix converts the string value found on the field to a number with parseFloat to allow the exact comparisons to compare correctly when the field value is …
=> fix(client): grid number filter (RT-1657-1658)

src/new-client/src/App/Trades/TradesGrid/components/ComparatorSelect.tsx
- On Windows, select options were rending with white background and text was white on white
- Fix - apply theme background color directly to option child element on styled.select
- *Note - did not consult with a UI/PO, assumed theme light background would be acceptable*
- *Note - I would like to fix the padding around the text in the option tags but a quick check on adding margin/padding was not working and from what I found on the internet margin/padding on option tags are generally not supported across browsers*
- *Concern - this was working with Windows 11 but I'd wonder if older Windows/browser versions might not receive the options background color, is there a way for me to test this (e.g. browserstack)?*
- No impacts to MacOS select for light or dark mode
=> fix(client): Filter Text (RT-1651)

src/new-client/src/App/Footer/StatusButton/StatusButton.tsx, src/new-client/src/components/DisconnectionOverlay.tsx, src/new-client/src/services/connection.ts
*Please review carefully - new to working with Reactive Trader and I have limited experience with RXJS.   Open to ideas like moving the internet connection stuff to another file or combining the offline/online connection observables into one, etc.*
- Created connection status observable from window offline/online events
- Update status to OFFLINE_DISCONNECTED when going offline if Hyrda status is connected
- Update status to latest Hydra status when user connects (if not connected, keep not connected)
- Update indicator to handle OFFLINE_DISCONNECTED status
- Update message to accurately describe disconnection reason
- When the user would loose internet connection, the `$ConnectionStatus` imported from Hydra was not updating that the user disconnected.  Instead,  the websocket remained …
=> fix(client) Connection Status Indicator (RT-1652)

src/new-client/src/App/LiveRates/Tile/Notional/Notional.tsx, src/new-client/src/components/DraggableTearOut/DraggableTearOut.tsx, src/new-client/src/components/DraggableTearOut/nonDraggableChildProps.ts
- Created nonDraggableChildProps for child elements that should not be draggable
- Spread props on notional input
- Drag movements on the input element were firing the ondragstart event on the notional tile, which was undesirable as the user could not easily highlight/copy parts of the input
- Followed this Stack Overflow article for an approach on the fix - https://stackoverflow.com/questions/6848140/how-do-i-prevent-drag-on-a-child-but-allow-drag-on-the-parent
- draggable must be set to true on the element that should not be dragged and `event.preventDefault()` and `event.stopPropagation()` called in the drag start handler (Drag event is triggered on the input element, then it is cancelled and not propagated to the parent)
- Chose to use a  `nonDraggableChildProps` and spread it so that …
=> fix(new-client): Tiles undock on notional input select (RT-1653)

src/new-client/src/App/LiveRates/MainHeader/ToggleView/ToggleView.tsx, src/new-client/src/App/LiveRates/Tiles.tsx, src/new-client/src/App/LiveRates/selectedView.ts
- Updated `useSelectedTileView` to use bind factory constructor
- Pass in current view from window object as initial value to the hook
- Upon re-docking, Live Rates tiles were getting the initView/defautValue for the tile view because the existing subscription to the source observable was closed when the tiles were un-docked
- New window initializes new observable
- `initView` value default for the bind was set when the user first opened the app, so it was always re-docking to have that very initial value from when the user first loaded the page (either from window object or default Analytics)
- The defaultValue/initView for the bind needed to be dynamic, based off the current selected tile view value
- I found that the only way to do this was using the factory bind initializer, where the …
=> fix (new-client): Re-Docking Live Rates tiles view fix

src/new-client/src/App/Header/theme-switcher/ThemeSwitcher.tsx
- `ThemeSwitcher` is configured to call `toggleTheme` when the `onChange` event is fired from `react-switch`
- `ThemeSwitcher` is also configured to call `themeToggle` for `onTouchStart` on devices that support touch
- This was working to support different devices:
- Mac/PC fire `toggleTheme` event from `react-switch`, only
- iPhone fires from the `onTouchStart` event, only
- Android touch was firing the `onChange` event AND `onTouchStart` event, causing the theme to switch and unswitch shortly after
- Created `handleChange` handler function for `onChange` to only call `toggleTheme` for non-touch devices so that it would not get misfired by Android
https://user-images.githubusercontent.com/10551665/150604860-525447f0-412b-489a-ae7f-633a94f37a7b.mov …
=> fix(new-client): Android day/light mode (RT-1663)

src/new-client/src/App/LiveRates/Tile/Notional/Notional.tsx, src/new-client/src/utils/__tests__/formatNumber.test.ts, src/new-client/src/utils/formatNumber.ts
- Tester was unable to enter more than 4 characters, the issue was that the `Intl` utility was detecting Russian on their Android device and the Notional controlled input formatter was not supporting the `" "` characters used as the Russian thousands separator
- Needed to generalized the thousands and decimal separators
- Modified `formatNumber.ts` to have the locale as a variable so that it can re-used and changed for testing (left as default but locally I can run RU and DE for example)
- Export values for the thousands/decimal separator, had to create a way to find them with functions because it appears `Intl` does not have any exposed functions for getting directly
- Exported the helper functions to unit test them (did not love this but I think its okay - open to ideas)
- Using lodash …
=> fix(new-client): Notional amount internationalized (RT-1664)

src/new-client/src/App/Trades/TradesHeader/ExcelButton.tsx, src/new-client/src/App/Trades/TradesState/colConfig.ts
- The suspected cause is that the version and language/region configurations on the Excel being used to read the CSV could not interpret the thousands separator in the exported CSV
- I suspect the thousand separator was the "thin whitespace" character used in Russian
- It was decided that the thousands separator would be removed from the notional column in the Excel export altogether
- This introduced the requirement that the formatting for Excel could be different from the formatting for the table
- I decided to make an `excelValueFormatter` function field on the `ColConfig` interface
- In `ExcelButton.tsx`, if `excelValueFormatter` is defined, it is used to format the value, otherwise the existing format functionality is followed (`valueFormatter` is used, otherwise the raw value is …
=> fix(new-client): Export to Excel notional column

src/new-client/src/App/LiveRates/Tile/PriceButton/PriceButton.tsx
- Problem: For AUD/USD and NZD/USD conversions, `formatTo3Digits` was appending a trailing 0 on the first part of the buy/sell numbers, a rate of .82671 would render as .820 67 1, since .82 only has 2 significant digits.
- Fix: Added a check for `bigFigureNumber < 1 && pipsPosition === 4`, which accurately finds scenarios where the `bigFigureNumber` only has 2 significant digits and use `formatTo2Digits` in this scenario
- Problem: When the pips number is 2 (JPY currencies), the decimal separator is manually added between `bigFigureNumber` and the pips because the `bigFigureNumber` is a whole number and the separator is not added by the formatter.  It was hard coded to `.`
- Fix: Use calculated internationalized `DECIMAL_SEPARATOR`
- Problem: The Tenths (final) digit was rendering as a …
=> fix(new-client): miscellaneous buy/sell numbers

src/client/package.json, src/client/setupTests.ts, src/client/src/App/Analytics/ProfitAndLoss/LastPosition.test.tsx, src/client/src/App/Analytics/ProfitAndLoss/LastPosition.tsx, src/client/src/App/LiveRates/Tile/Tile.rfq.test.tsx, src/client/src/App/LiveRates/Tile/Tile.test.tsx, src/client/src/services/prices/__mocks__/prices.ts, src/client/src/services/trades/__mocks__/mockTrades.ts, src/client/src/services/trades/__mocks__/trades.ts
Added TextDecoder API and missing mocks to price and trade services to be able to run all tests and see which are failing.
Then created missing mocks (getIsSymbolDataStale$ and isBlotterDataStale$) and fixed multiple assertions for the 3 test suites which were failing.
=> Fix/tests: Fixed existing failing tests to pass

src/client/src/App/Trades/TradesGrid/NumFilter.tsx, src/client/src/App/Trades/TradesGrid/SetFilter.tsx, src/client/src/App/Trades/TradesHeader/QuickFilter.tsx
- Used nonDraggableChildProps for child elements that should not be draggable within Trades (Blotter) section.
- Spread props on QuickFilter, NumFilter, and SetFilter inputs to prevent dragging from within input.
- Drag movements on the input elements were firing the ondragstart event on the Trades filter input fields, which was undesirable as the user could not easily highlight/copy parts of the input
- nonDraggableChildProps was created in [this](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/2027) fix, and now it is extended to input elements within Trades.
https://user-images.githubusercontent.com/42718557/158416878-8e873e53-30e8-4650-a43f-7a45e4b66a20.mov
https://user-images.githubusercontent.com/42718557/158416772-2c1cdb5f-d510-436a-a876-19b269ebe568.mov
=> fix(client): fixed draggable inputs in trades (blotter)

src/client/src/App/LiveRates/Tile/Notional/Notional.tsx
moved nonDraggableChildProps from input to wrapper to fix notional input in safari
=> fix(client): notional input on safari

src/client/src/styleguide/index.tsx
Fixes a bug in the /styleguide caused by https://github.com/AdaptiveConsulting/ReactiveTraderCloud/pull/2070 where the body is not scrolling.
=> fix(styleguide): add global style override to stylguide to enable scroll

src/client/src/utils/__tests__/formatNumber.test.ts, src/client/src/utils/formatNumber.ts
When getDecimalSeparator and getThousandsSeparator functions were implemented to correctly export the numbers from blotter to CSV(Excel), a magic number had to be used to detect each locale's separators. This magic number (1000.5) was flawed in es-ES locale, because 4-digit numbers do not have thousands separator in Spain.
Unfortunately, there is no way to do this detection without a magic number yet, therefore I changed the magic number to include thousands separator after checking in over 20 locales, and implemented a few more tests.
=> Es locale fix

src/client/src/App/Analytics/Positions/Positions.tsx
d3Effect function where the svg for the positions bubbles are created, is running before the encompassing div gets correct width and height leading to an error in the detection of the size of this div(it is 0 when the function runs on load/reload of the page). 
For demo purposes it is conditioned to get a fixed width and height(288px) temporarily as the dimensions of this element do not change with resizing.
=> fix(positions): bubbles div size fix

src/client/README.md, src/client/src/App/Credit/CreditRfqForm/RfqParameters.tsx, src/client/src/App/Credit/CreditSellSideTicket/CreditSellSideParameters.tsx, src/client/src/utils/formatNumber.ts
early view of precision rework for Credit - aside from the dodgy rounding that was going on, we clarified that the quantity should be limited to whole numbers of 000s of bonds.
*refactoring unit test setup/dependencies and related tests is deferred to ticket 3001*
=> fix(credit): correct precision on quantity and price inputs

src/client/src/Web/serviceWorkerRegistration.ts
.. this still leaves the "env" deployments broken
I am not too concerned about that for now as we can test fully in Dev (non-"env" deployment) - the app was working fine in Dev up till now, apart from the SW registration failure if you refreshed when address was on /credit
=> fix(serviceworker): service worker base url as origin for most cases

src/client/src/App/Trades/TradesGrid/TradesGrid.tsx
minimal fix for ticket 3800 (iOS poor blotter performance with more than a few hundred rows)
* seems ok in testing, some concerns from @ivanfalanga-adaptive regarding cross-browser compatibility, which I share .. this is a HINT rather than a command, so is not a permanent fix.
* considering applying to other sections - this was the minimal change required to bring iOS browsers under control when blotter rows started exceeding the 500 mark (although we start to perceive degradation after only a few 100)
* this has been debugged a fair bit in Safari with attached device, and the layout phase is almost totally dominant when performance is bad .. hence the optimisations in the CSS .. this particular attribute chosen for cross-browser compatibility
=> fix(blotter): add CSS containment directive for blotter performance

.github/workflows/branch.yml, .github/workflows/pull.yml, .github/workflows/tag.yml
We have not needed authentication to access Hydra libs in Artifactory for at least a year - removing this now as it is preventing external contributions (Ignacio) and we can clean up some GCP config and permissions into the bargain
=> chore(ci): remove npmrc decrypt from builds

src/client/src/OpenFin/apps/Launcher/NlpSuggestions/styles.ts
.. another quick fix for Launcher
This time, discovered that typing `/last` in Launcher gets all the trades back .. which can overwhelm the Suggestion box .. so limited this to 800px (guess)
=> fix(launcher): limit launcher NPL suggestion height to 800 with overflow

src/client/src/App/Credit/CreditRfqs/CreditRfqCards/CardFooter.tsx, src/client/src/App/Credit/CreditRfqs/CreditRfqCards/handleViewTrade.ts, src/client/src/App/Trades/TradesGrid/TradesGrid.tsx, src/client/src/App/Trades/TradesState/tableTrades.ts, src/client/src/notifications.openfin.ts, src/client/src/services/trades/__mocks__/creditTrades.ts, src/client/src/services/trades/__mocks__/trades.mock.ts, src/client/src/services/trades/__tests__/trades.test.ts, src/client/src/services/trades/trades.ts, src/client/src/services/trades/types.ts
The highlight row signal was emitting the tradeId as a string which failed against a strict equality check. Comparison was between emitted tradeId (string) and backend tradeId (number).
=> fix: fx notification button to highlight blotter

src/client/package-lock.json, src/client/package.json, src/client/src/App/Footer/common-styles.ts, src/client/src/theme/globals.ts, src/client/vite.config.ts
The issue where the PWA banner style is not applying immediately on load seem to be more widespread than initially thought & has been there for some time.
This PR removes the deprecated `typeface-lato, typeface-roboto & typeface-montserrat` and replaced it with Google's font CDN. The issue seems to be that when a page is first requested, the font is queued & downloaded at the tail end of the request. The default behaviour of `@font-face` is that the `font-display` is set to `swap`. This means that if the font is not available, the browser user agent will apply a font of its choice until ours is available, which explains why we see a Flash of Unstyled Text (FOUT). 
The fix is to add to preloading mechanism `<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>` or enable …
=> fix: Flash of unstyled Text (FOUT)

src/client/src/OpenFin/Window/WindowFrameBase.tsx, src/client/src/OpenFin/Window/WindowViewport.tsx, src/client/src/services/limitChecker/limitChecker.openfin.ts
The Limit Checker PR introduced a bug where each trade would wait for the limit check stream to timeout before executing, this is quick pr to fix that.
=> fix: limit check stream is skipped over if limit checker is closed

src/client/src/OpenFin/utils/templates/fxTemplateLayouts.ts
mismatched names in manifest and template layouts
=> fix: match blotter name in template layouts to manifest

src/client/index.html, src/client/package.json, src/client/src/App.tsx, src/client/src/App/Footer/ContactUsButton/ContactUs.tsx, src/client/src/App/Footer/ContactUsButton/FollowUs.tsx, src/client/src/App/Header/Header.tsx, src/client/src/App/LiveRates/Tile/Tile.state.ts, src/client/src/constants.ts, src/client/src/dom.d.ts, src/client/src/setupTests.ts, src/client/vite.config.ts
Upgraded from UA to GA4, which for RT just means getting the Google Analytics source from a different address, including the G-xxxxx "tag" in the URL along with slightly modified script logic using conditional HTML insertion in the Vite build.
Then doing the same in the GA config setup in the main app in code.
Demonstrates switch to using a "dev" property for all but Prod, to keep stuff like local testing out of the reports that can track external usage of RT + friends
_Tested locally and on the PR deploy, per std bot comment below - if you have GA access, can be tracked in GA realtime report [here](https://analytics.google.com/analytics/web/#/p383903600/realtime/overview)_
_Deferring E2E against Prod to follow on - plan at the moment is to use a query param or something .._
=> Google Analytics upgrade

src/client/public-openfin/limit-checker.json, src/client/src/App/LiveRates/Tile/Notional/Notional.tsx, src/client/src/OpenFin/apps/LimitChecker/LimitCheckResults.tsx, src/client/src/OpenFin/apps/LimitChecker/LimitChecker.tsx, src/client/src/OpenFin/apps/LimitChecker/LimitInput.tsx, src/client/src/OpenFin/apps/LimitChecker/state.ts, src/client/src/services/trades/types.ts, src/client/src/utils/formatNotional.ts
https://github.com/AdaptiveConsulting/ReactiveTraderCloud/assets/67154337/40738151-c06b-420a-a7f1-82fa5d303ed9
Notional in table is also formatted now
=> feat: formatting and shortcuts on limit checker inputs

src/client/e2e/spot-tile.spec.ts
1.  Did assertion strategy change to confirm element is visible.  Previous strategy was asserting the variable was not null
2. Moved execution spinner assertion to timeout test as it is too flaky to validate on success transaction
3. Removed `tilePage.waitForTimeout(10000)` and replaced with a dynamic wait instead
4. Did few other improvements around selectors strategy
Ran both `e2e:web` and `e2e:web:smoke` multiple times to validate stability ✅
=> test(playwright): Change assertions strategy and other improvements

src/client/e2e/credit.spec.ts, src/client/playwright.config.ts
1. Replaced existing static wait `rfqsPage.waitForTimeout(15000)` with a dynamic one that will resume test execution only once a first quote response is received. This is speeding up test execution substantially
2. Optimised the use of `getByTestId`
3. Added html reporter to playwright.config
Ran both `e2e:web` and `e2e:web:smoke` multiple times to validate stability ✅
=> test(playwright): replace static wait with a dynamic one and added html reporter

src/client/OpenFin/Window/WindowHeader.tsx, src/client/OpenFin/apps/LimitChecker/LimitCheckResults.tsx, src/client/OpenFin/index.tsx
I've also been looking at [5038](https://adaptive.kanbanize.com/ctrl_board/18/cards/5038/details/) and it looks like the white screen isn't caused by the `backgroundColor` option in `defaultWindowOptions`/`defaultViewOptions`. When I set backgroundColor to red for example and start the FX app (video attached below), the app is red for a second, before it becomes white, and then it loads the app as usual. The views inside the app load in the same way. From inspection, this looks like it's because nothing has been loaded so the view is blank (white). Going to just submit this PR for [5041](https://adaptive.kanbanize.com/ctrl_board/18/cards/5041/details/) now and look at alternative solutions to 5038 separately.
https://github.com/AdaptiveConsulting/ReactiveTraderCloud/assets/10549511/6c9a8ec …
=> fix: force dark theme for launcher and limit checker

.github/workflows/e2e-full.yml, .github/workflows/e2e-smoke.yml, .github/workflows/pull.yml, playwright.config.ts
updated yml workflow files to include html reporter as an artifact to github actions with 7 retention days . This allows to download playwright html report to help in troubleshooting failing tests
Output example -> https://github.com/AdaptiveConsulting/ReactiveTraderCloud/actions/runs/5881522557 
html outcome in case of failure:
Also added `list` reporter for more verbose console output
=> Test(playwright): Added Playwright html reporter to github actions

.github/workflows/e2e-full.yml, .github/workflows/e2e-smoke.yml, .github/workflows/pull.yml
Changes done to upload html report artifact ONLY when e2e tests fail. Previous condition was set to `always()` in order to force uploading artifact step to be executed on both e2e success and failure. without this condition the default behaviour is to execute only if previous step was successful 
https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
> You can use the following status check functions as expressions in if conditionals. A default status check of success() is applied unless you include one of these functions.
sucess()
always()
cancelled()
failure()
=> test(playwright): remove always() condition from workflow

packages/client/e2e/blotter.spec.ts, packages/client/e2e/credit.spec.ts, packages/client/e2e/fx.spec.ts, packages/client/e2e/limit-checker.spec.ts, packages/client/e2e/spot-tile.spec.ts, packages/client/e2e/utils.ts, packages/client/playwright.config.ts
Performed scripts maintenance to allow existing scripts to run successfully against both web and openfin 
1. changed `credit.spec` strategy to interact with credit-sellside openfin window
2. did `fx.spec` maintenance (openfin specific).  test is now stable but it will fail when run while credit window is open at the same time (and make subsequent tests fail too). I will address this issue with the team.  Meanwhile I made it skipped until a resolution is found
3. few minor tweaks to improve suite resiliency 
4. removed unnecessary test timeout and set default to 30 seconds. This will prevent long hanging time in case of test case failure.  Current tests take less 20 seconds to run at the most
Ran whole suite against both openfin and web ✅
=> Test(maintenance): Update Playwright scripts for openfin 

packages/client/src/workspace/home/respondWithIntent.ts
Broken state, showing first trades:
Fixed state, showing last trades:
=> fix: showing last trades instead of first trade in ws nlp

packages/client/e2e/credit.spec.ts
Added an `afterEach` step to close all residual sell-side window for both openfin and web context. 
Tested both web and openfin ✅
=> Rt 5578: Fix credit.spec test failure on openfin

packages/client/src/services/connection.ts, packages/client/src/services/credit/creditRfqs.ts
"cleanup" during blotter highlighting work introduced a subtle but lethal bug in the reconnect flow, where the RFQ store was not reset ... this has been restored
(for future ref, this hit us in an Error thrown in `useQuoteState` .. might want to make this a bit more lenient in future)
=> fix: credit start sow, restore reset on re-connect

.github/workflows/e2e-full.yml, .github/workflows/pull.yml, packages/client/e2e/blotter.spec.ts, packages/client/e2e/credit.spec.ts, packages/client/e2e/fixtures.ts, packages/client/e2e/fx.spec.ts, packages/client/e2e/limit-checker.spec.ts, packages/client/e2e/spot-tile.spec.ts, packages/client/e2e/utils.ts, packages/client/package.json, packages/client/playwright.config.ts
Latest investigated  PR and scheduled e2e test failure show high failure occurrences in regards to `New RFQ/Create RFQ for GOOGL @smoke` test case. 
**Facts**
1. Failures are happening more frequently on CI, while it was rarely happening when test being ran on local
2. Playwright report output is frequently about test timing out after default 30 seconds. No specific step causing the failure are reported
3. Screenshots are showing some quotes being available, but the test didn't select one for execution
4. At the moment of interacting with the UI, it may have other quotes rendering as selectable, potentially causing erratic behaviour with hoving and clicking on accept button
**Troubleshooting**
1. I've set the test to run in loop 10 times to find a frequency and to have few occurrences to …
=> Test: 5581 Improve "New RFQ/Create RFQ for GOOGL @smoke" test resiliency

packages/client/e2e/blotter.spec.ts
Mitigation for low frequency but periodical false negative on both scheduled e2e or pull request e2e.  Since the failure occurence is erratic and is tend to be related to timing issue the countermeasure is to retry until it times out
Ran tests on both web and openfin ✅
=> Test: 5590 Improve "when user buys a currency, the new row should flash briefly" test resiliency

.github/workflows/pull-fork.yml, .github/workflows/pull.yml
Avoid running build/deploy/test on draft PR.  The skipped steps are then executed once the PR is moved to `review` state
=> Chore: added condition to avoid build/deploy/test against draft pr

.github/workflows/pull.yml, packages/client/e2e/credit.spec.ts
Serializing `web` -> `openfin` e2e tests on a PR basis to prevent intermittent concurrency issues that cause false negative results
=> chore: Serialise web and openfin e2e tests execution

packages/client/playwright/components/blotter.component.ts, packages/client/playwright/tests/spot-tile.spec.ts
Removed the code to retrieve the latest TradeId from the Spec file and moved it to the blotter Component. Also created a similar function to retrieve the newly created Trade Status (to verify specially the rejected Trades).
=> New functions for getting newest TradeId and Status from the blotter

packages/client/package-lock.json, packages/client/package.json, packages/client/src/client/OpenFin/apps/Launcher/NlpSuggestions/intents/index.tsx, packages/client/src/generated/TradingGateway.ts, packages/client/src/services/connection.ts, packages/client/src/workspace/provider.ts, packages/client/vite.config.ts
- Update to latest hydra web libs
- Use direct Hydra address (wss://...) rather than Nginx or local proxy - that part of deployment to be retired soon
- Separate codegen as dev dependency
- re-run codegen
- re-work connection to use new connectToTradingGateway
See web deployment [here](https://web.env.reactivetrader.com/branch/chore_update-hydra)
=> chore: update hydra-platform to 4.57.0, rework connection

packages/client/.gitignore, packages/client/eslint.config.js, packages/client/package-lock.json, packages/client/package.json, packages/client/src/client/App/Credit/CreditRfqs/CreditRfqCards/CardFooter.tsx, packages/client/src/client/App/Credit/CreditRfqs/CreditRfqCards/Quote/CardQuote.tsx, packages/client/src/client/App/Credit/SellSide/SellSideTradeTicket/SellSideTradeTicketHeader.tsx, packages/client/src/client/App/Credit/SellSide/SellSideTradeTicket/SellSideTradeTicketParameters.tsx, packages/client/src/client/App/Credit/SellSide/sellSideState.ts, packages/client/src/client/setupTests.ts, packages/client/src/client/styleguide/components/Button.tsx, packages/client/src/services/executions/__mocks__/executions.ts, packages/client/tsconfig.json, packages/client/vite.config.ts
- use vitest v2 (latest 2.0.3) and latest vite, adjust imports
- test browser mode (can also do this in vitest v1.6.0 but v2 is a better experience
- had to bypass RT's HTML injector plugin for `test` mode - otherwise all hell broke loose in the main vitest page
MAIN issue is that it won't finish - so a bit of a dealbreaker for CI 😞 - had to switch off browser mode, but vitest 2 upgrade still stands.
=> chore: upgrade vitest to v2 and test browser mode

.github/workflows/e2e-smoke.yml
use static tag to identify Prod current commit - and check this code out in the Prod E2E workflow
=> chore: run E2E from Prod code against Prod deployment

packages/client/package-lock.json, packages/client/package.json, packages/client/vite.config.ts
.. small one to finally retire the custom modulepreload hack from early vite days .. vite does modulepreload now out of the box, for dynamic imports - but added a small mod to include the main js file per general examples
=> chore: vite, remove custom modulepreload plugin

packages/client/src/client/App/Analytics/Positions/BubbleChart.tsx
Seemed to just need tear down logic for deleting the graph
=> fix: stop bubble graph duplicating on reconnect
